.TH "/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/morphology Directory Reference" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/morphology Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB__init__\&.py\fP"
.br
.ti -1c
.RI "file \fBcomponent\&.py\fP"
.br
.ti -1c
.RI "file \fBlemma\&.py\fP"
.br
.ti -1c
.RI "file \fBlist_of_components\&.py\fP"
.br
.ti -1c
.RI "file \fBrelated_form\&.py\fP"
.br
.ti -1c
.RI "file \fBstem\&.py\fP"
.br
.ti -1c
.RI "file \fBword_form\&.py\fP"
.br
.in -1c
