.TH "/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/resources Directory Reference" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/resources Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB__init__\&.py\fP"
.br
.ti -1c
.RI "file \fBaudio\&.py\fP"
.br
.ti -1c
.RI "file \fBhuman_resource\&.py\fP"
.br
.ti -1c
.RI "file \fBmaterial\&.py\fP"
.br
.ti -1c
.RI "file \fBpicture\&.py\fP"
.br
.ti -1c
.RI "file \fBresource\&.py\fP"
.br
.ti -1c
.RI "file \fBspeaker\&.py\fP"
.br
.ti -1c
.RI "file \fBvideo\&.py\fP"
.br
.in -1c
