.TH "/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/utils/attr.py" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/utils/attr.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlmf\&.src\&.utils\&.attr\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBlmf\&.src\&.utils\&.attr\&.check_attr_type\fP"
.br
.RI "\fICheck that attribute value is of specified type\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.utils\&.attr\&.check_attr_range\fP"
.br
.RI "\fICheck that attribute value is in specified range\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.utils\&.attr\&.check_date_format\fP"
.br
.RI "\fIVerify that date format is composed as follows: YYYY-MM-DD (ISO 8601)\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.utils\&.attr\&.check_time_format\fP"
.br
.RI "\fIVerify that time format is composed as follows: THH:MM:SS,MSMS (ISO 8601: 'T' for Time)\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.utils\&.attr\&.check_duration_format\fP"
.br
.RI "\fIVerify that duration format is composed as follows: PTxxHxxMxxS (ISO 8601: 'P' for Period)\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
