.TH "/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/mrd/context.py" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/mrd/context.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlmf\&.src\&.mrd\&.context\&.Context\fP"
.br
.RI "\fI'Context is a class representing a text string that provides authentic context for the use of the word form managed by the Lemma\&. This class is to be distinguished from Sense Example\&.' (LMF) \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlmf\&.src\&.mrd\&.context\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
