.TH "/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/core/definition.py" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/core/definition.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlmf\&.src\&.core\&.definition\&.Definition\fP"
.br
.RI "\fI'Definition is a class representing a narrative description of a sense\&. It is provided to help human users understand the meaning of a lexical entry\&. A Sense instance can have zero to many definitions\&. Each Definition instance may be associated with zero to many Text Representation instances in order to manage the text defintion in more than one language or script\&. In addition, the narrative description can be expressed in a different language or script than the one in the Lexical Entry instance\&.' (LMF) \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlmf\&.src\&.core\&.definition\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
