.TH "/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/utils/error_handling.py" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/utils/error_handling.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlmf\&.src\&.utils\&.error_handling\&.Error\fP"
.br
.RI "\fIBase class for exceptions in this library\&. \fP"
.ti -1c
.RI "class \fBlmf\&.src\&.utils\&.error_handling\&.InputError\fP"
.br
.RI "\fIException raised for errors in the input\&. \fP"
.ti -1c
.RI "class \fBlmf\&.src\&.utils\&.error_handling\&.OutputError\fP"
.br
.RI "\fIException raised for errors in the output\&. \fP"
.ti -1c
.RI "class \fBlmf\&.src\&.utils\&.error_handling\&.Warning\fP"
.br
.RI "\fIBase class for warnings in this library\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlmf\&.src\&.utils\&.error_handling\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
