.TH "/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/resources/human_resource.py" 3 "Thu Nov 27 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/resources/human_resource.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlmf\&.src\&.resources\&.human_resource\&.HumanResource\fP"
.br
.RI "\fI\fBHumanResource\fP is a Resource subclass\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlmf\&.src\&.resources\&.human_resource\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
