.TH "/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/utils/io.py" 3 "Thu Sep 18 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/utils/io.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsrc\&.utils\&.io\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBsrc\&.utils\&.io\&.open_file\fP"
.br
.RI "\fIOpen file in specified mode (automatically decode file in unicode)\&. \fP"
.ti -1c
.RI "def \fBsrc\&.utils\&.io\&.open_read\fP"
.br
.RI "\fIOpen file in read mode (automatically decode file in unicode)\&. \fP"
.ti -1c
.RI "def \fBsrc\&.utils\&.io\&.open_write\fP"
.br
.RI "\fIOpen file in write mode (automatically decode file in unicode)\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
