.TH "/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/core/lexicon.py" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/core/lexicon.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlmf\&.src\&.core\&.lexicon\&.Lexicon\fP"
.br
.RI "\fI'Lexicon is a class containing all the lexical entries of a given language within the entire resource\&.' (LMF) \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlmf\&.src\&.core\&.lexicon\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
