.TH "/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/core/lexicon.py" 3 "Thu Sep 18 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/core/lexicon.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsrc\&.core\&.lexicon\&.Lexicon\fP"
.br
.RI "\fIThis class represents a lexicon containing lexical entries\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsrc\&.core\&.lexicon\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
