.TH "/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/core/lexical_entry.py" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/core/lexical_entry.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\fP"
.br
.RI "\fI'Lexical Entry is a class representing a lexeme in a given language and is a container for managing the Form and Sense classes\&. A Lexical Entry instance can contain one to many different forms and can have from zero to many different senses\&.' (LMF) \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlmf\&.src\&.core\&.lexical_entry\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
