.TH "lmf.src.core.definition" 3 "Thu Nov 27 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.core.definition \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDefinition\fP"
.br
.RI "\fI'Definition is a class representing a narrative description of a sense\&. It is provided to help human users understand the meaning of a lexical entry\&. A Sense instance can have zero to many definitions\&. Each Definition instance may be associated with zero to many Text Representation instances in order to manage the text defintion in more than one language or script\&. In addition, the narrative description can be expressed in a different language or script than the one in the Lexical Entry instance\&.' (LMF) \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
