.TH "lmf.src.core.lexical_resource" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.core.lexical_resource \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLexicalResource\fP"
.br
.RI "\fI'Lexical Resource is a class representing the entire resource and is a container for one or more lexicons\&. There is only one Lexical Resource instance\&.' (LMF) \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
