.TH "lmf.src.core.text_representation.TextRepresentation" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.core.text_representation.TextRepresentation \- 
.PP
'Text Representation is a class representing the textual content of definition or statement\&. When there is more than one variant orthography, the Text Representation instance contains a Unicode string representing the textual content as well as unique attribute-value pairs that describe the specific language, script and orthography\&.' (LMF)  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Representation\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "def \fBset_comment\fP"
.br
.RI "\fISet written form comment\&. \fP"
.ti -1c
.RI "def \fBget_comment\fP"
.br
.RI "\fIGet written form comment\&. \fP"
.ti -1c
.RI "def \fBset_writtenForm\fP"
.br
.RI "\fISet written form and language\&. \fP"
.ti -1c
.RI "def \fBget_writtenForm\fP"
.br
.RI "\fIGet written form\&. \fP"
.ti -1c
.RI "def \fBset_language\fP"
.br
.RI "\fISet language used for written form\&. \fP"
.ti -1c
.RI "def \fBget_language\fP"
.br
.RI "\fIGet language used for written form\&. \fP"
.ti -1c
.RI "def \fBset_scriptName\fP"
.br
.RI "\fISet script name\&. \fP"
.ti -1c
.RI "def \fBget_scriptName\fP"
.br
.RI "\fIGet script name\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfont\fP"
.br
.ti -1c
.RI "\fBcomment\fP"
.br
.ti -1c
.RI "\fBwrittenForm\fP"
.br
.ti -1c
.RI "\fBlanguage\fP"
.br
.ti -1c
.RI "\fBscriptName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
'Text Representation is a class representing the textual content of definition or statement\&. When there is more than one variant orthography, the Text Representation instance contains a Unicode string representing the textual content as well as unique attribute-value pairs that describe the specific language, script and orthography\&.' (LMF) 
.PP
Definition at line 9 of file text_representation\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.core\&.text_representation\&.TextRepresentation\&.__init__ (self)"

.PP
Constructor\&. \fBTextRepresentation\fP instances are owned by Definition and Statement\&. 
.PP
\fBReturns:\fP
.RS 4
A \fBTextRepresentation\fP instance\&. 
.RE
.PP

.PP
Definition at line 12 of file text_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.text_representation\&.TextRepresentation\&.__del__ (self)"

.PP
Destructor\&. 
.PP
Definition at line 21 of file text_representation\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lmf\&.src\&.core\&.text_representation\&.TextRepresentation\&.get_comment (self)"

.PP
Get written form comment\&. 
.PP
\fBReturns:\fP
.RS 4
Representation attribute 'comment'\&. 
.RE
.PP

.PP
Definition at line 36 of file text_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.text_representation\&.TextRepresentation\&.get_language (self)"

.PP
Get language used for written form\&. 
.PP
\fBReturns:\fP
.RS 4
Representation attribute 'language'\&. 
.RE
.PP

.PP
Definition at line 73 of file text_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.text_representation\&.TextRepresentation\&.get_scriptName (self)"

.PP
Get script name\&. 
.PP
\fBReturns:\fP
.RS 4
Representation attribute 'scriptName'\&. 
.RE
.PP

.PP
Definition at line 89 of file text_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.text_representation\&.TextRepresentation\&.get_writtenForm (self, language = \fCNone\fP)"

.PP
Get written form\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlanguage\fP If this argument is given, get written form only if written in this language\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The filtered Representation attribute 'writtenForm'\&. 
.RE
.PP

.PP
Definition at line 55 of file text_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.text_representation\&.TextRepresentation\&.set_comment (self, comment)"

.PP
Set written form comment\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcomment\fP Comment about the written form\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBTextRepresentation\fP instance\&. 
.RE
.PP

.PP
Definition at line 26 of file text_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.text_representation\&.TextRepresentation\&.set_language (self, language)"

.PP
Set language used for written form\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlanguage\fP Language used for the written form\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBTextRepresentation\fP instance\&. 
.RE
.PP

.PP
Definition at line 63 of file text_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.text_representation\&.TextRepresentation\&.set_scriptName (self, script_name)"

.PP
Set script name\&. 
.PP
\fBParameters:\fP
.RS 4
\fIscript_name\fP The script name to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBTextRepresentation\fP instance\&. 
.RE
.PP

.PP
Definition at line 79 of file text_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.text_representation\&.TextRepresentation\&.set_writtenForm (self, written_form, language = \fCNone\fP)"

.PP
Set written form and language\&. 
.PP
\fBParameters:\fP
.RS 4
\fIwritten_form\fP The written form to set\&. 
.br
\fIlanguage\fP Language used for the written form\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBTextRepresentation\fP instance\&. 
.RE
.PP

.PP
Definition at line 42 of file text_representation\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.core\&.text_representation\&.TextRepresentation\&.comment"

.PP
Definition at line 33 of file text_representation\&.py\&.
.SS "lmf\&.src\&.core\&.text_representation\&.TextRepresentation\&.font"

.PP
Definition at line 19 of file text_representation\&.py\&.
.SS "lmf\&.src\&.core\&.text_representation\&.TextRepresentation\&.language"

.PP
Definition at line 70 of file text_representation\&.py\&.
.SS "lmf\&.src\&.core\&.text_representation\&.TextRepresentation\&.scriptName"

.PP
Definition at line 86 of file text_representation\&.py\&.
.SS "lmf\&.src\&.core\&.text_representation\&.TextRepresentation\&.writtenForm"

.PP
Definition at line 50 of file text_representation\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
