.TH "lmf.src.resources.picture.Picture" 3 "Thu Nov 27 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.resources.picture.Picture \- 
.PP
\fBPicture\fP is a Material subclass representing a picture\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Material\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIDestructor\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfilename\fP"
.br
.ti -1c
.RI "\fBreference\fP"
.br
.ti -1c
.RI "\fBwidth\fP"
.br
.ti -1c
.RI "\fBheight\fP"
.br
.ti -1c
.RI "\fBformat\fP"
.br
.ti -1c
.RI "\fBstatement\fP"
.br
.RI "\fIStatement instances are owned by \fBPicture\fP There is zero to many Statement instances per \fBPicture\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBPicture\fP is a Material subclass representing a picture\&. 
.PP
Definition at line 8 of file picture\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.resources\&.picture\&.Picture\&.__init__ (self)"

.PP
Constructor\&. \fBPicture\fP instances are owned by ?\&. 
.PP
\fBReturns:\fP
.RS 4
A \fBPicture\fP instance\&. 
.RE
.PP

.PP
Definition at line 11 of file picture\&.py\&.
.SS "def lmf\&.src\&.resources\&.picture\&.Picture\&.__del__ (self)"

.PP
Destructor\&. Release Statement instances\&. 
.PP
Definition at line 27 of file picture\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.resources\&.picture\&.Picture\&.filename"

.PP
Definition at line 18 of file picture\&.py\&.
.SS "lmf\&.src\&.resources\&.picture\&.Picture\&.format"

.PP
Definition at line 22 of file picture\&.py\&.
.SS "lmf\&.src\&.resources\&.picture\&.Picture\&.height"

.PP
Definition at line 21 of file picture\&.py\&.
.SS "lmf\&.src\&.resources\&.picture\&.Picture\&.reference"

.PP
Definition at line 19 of file picture\&.py\&.
.SS "lmf\&.src\&.resources\&.picture\&.Picture\&.statement"

.PP
Statement instances are owned by \fBPicture\fP There is zero to many Statement instances per \fBPicture\fP\&. 
.PP
Definition at line 25 of file picture\&.py\&.
.SS "lmf\&.src\&.resources\&.picture\&.Picture\&.width"

.PP
Definition at line 20 of file picture\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
