.TH "lmf.src.core.lexicon.Lexicon" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.core.lexicon.Lexicon \- 
.PP
'Lexicon is a class containing all the lexical entries of a given language within the entire resource\&.' (LMF)  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "def \fBset_id\fP"
.br
.RI "\fISet lexicon identifier\&. \fP"
.ti -1c
.RI "def \fBget_id\fP"
.br
.RI "\fIGet identifier\&. \fP"
.ti -1c
.RI "def \fBset_entrySource\fP"
.br
.RI "\fISet lexicon entry source\&. \fP"
.ti -1c
.RI "def \fBget_entrySource\fP"
.br
.RI "\fIGet entry source\&. \fP"
.ti -1c
.RI "def \fBset_language\fP"
.br
.RI "\fISet lexicon language\&. \fP"
.ti -1c
.RI "def \fBget_language\fP"
.br
.RI "\fIGet language\&. \fP"
.ti -1c
.RI "def \fBset_languageScript\fP"
.br
.RI "\fISet lexicon language script\&. \fP"
.ti -1c
.RI "def \fBget_languageScript\fP"
.br
.RI "\fIGet language script\&. \fP"
.ti -1c
.RI "def \fBset_label\fP"
.br
.RI "\fISet lexicon label\&. \fP"
.ti -1c
.RI "def \fBget_label\fP"
.br
.RI "\fIGet label\&. \fP"
.ti -1c
.RI "def \fBset_lexiconType\fP"
.br
.RI "\fISet lexicon type\&. \fP"
.ti -1c
.RI "def \fBget_lexiconType\fP"
.br
.RI "\fIGet lexicon type\&. \fP"
.ti -1c
.RI "def \fBset_vowelHarmony\fP"
.br
.ti -1c
.RI "def \fBget_vowelHarmony\fP"
.br
.ti -1c
.RI "def \fBset_localPath\fP"
.br
.RI "\fISet lexicon local path\&. \fP"
.ti -1c
.RI "def \fBget_localPath\fP"
.br
.RI "\fIGet lexicon local path\&. \fP"
.ti -1c
.RI "def \fBget_lexical_entries\fP"
.br
.RI "\fIGet all lexical entries maintained by the lexicon\&. \fP"
.ti -1c
.RI "def \fBadd_lexical_entry\fP"
.br
.RI "\fIAdd a lexical entry to the lexicon\&. \fP"
.ti -1c
.RI "def \fBremove_lexical_entry\fP"
.br
.RI "\fIRemove a lexical entry from the lexicon\&. \fP"
.ti -1c
.RI "def \fBcount_lexical_entries\fP"
.br
.RI "\fICount number of lexical entries of the lexicon\&. \fP"
.ti -1c
.RI "def \fBsort_homonym_numbers\fP"
.br
.RI "\fISort similar given items of lexical entries contained in the lexicon according to their homonym number\&. \fP"
.ti -1c
.RI "def \fBsort_lexical_entries\fP"
.br
.RI "\fISort given items of lexical entries contained in the lexicon according to a certain order\&. \fP"
.ti -1c
.RI "def \fBfind_lexical_entries\fP"
.br
.RI "\fIFind all lexical entries which characteristics meet the given condition\&. \fP"
.ti -1c
.RI "def \fBcheck_cross_references\fP"
.br
.RI "\fICheck all cross-references in the lexicon\&. \fP"
.ti -1c
.RI "def \fBreset_check\fP"
.br
.RI "\fIReset boolean to be able to check all cross-references in the lexicon again\&. \fP"
.ti -1c
.RI "def \fBconvert_to_latex\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlanguage\fP"
.br
.ti -1c
.RI "\fBlanguageScript\fP"
.br
.ti -1c
.RI "\fBlabel\fP"
.br
.ti -1c
.RI "\fBlexiconType\fP"
.br
.ti -1c
.RI "\fBentrySource\fP"
.br
.ti -1c
.RI "\fBvowelHarmony\fP"
.br
.ti -1c
.RI "\fBlocalPath\fP"
.br
.ti -1c
.RI "\fBlexical_entry\fP"
.br
.RI "\fIAll LexicalEntry instances are maintained by \fBLexicon\fP There is one or more LexicalEntry instances per \fBLexicon\fP\&. \fP"
.ti -1c
.RI "\fBid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
'Lexicon is a class containing all the lexical entries of a given language within the entire resource\&.' (LMF) 
.PP
Definition at line 9 of file lexicon\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.__init__ (self, id = \fCNone\fP)"

.PP
Constructor\&. \fBLexicon\fP instances are owned by LexicalResource\&. 
.PP
\fBReturns:\fP
.RS 4
A \fBLexicon\fP instance\&. 
.RE
.PP

.PP
Definition at line 12 of file lexicon\&.py\&.
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.__del__ (self)"

.PP
Destructor\&. Release LexicalEntry instances\&. 
.PP
Definition at line 31 of file lexicon\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.add_lexical_entry (self, lexical_entry)"

.PP
Add a lexical entry to the lexicon\&. 
.PP
\fBParameters:\fP
.RS 4
\fI\fBlexical_entry\fP\fP A LexicalEntry instance to add to the \fBLexicon\fP\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLexicon\fP instance\&. 
.RE
.PP

.PP
Definition at line 149 of file lexicon\&.py\&.
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.check_cross_references (self)"

.PP
Check all cross-references in the lexicon\&. Fill the private attribute '__lexicalEntry' of each RelatedForm instance for all lexical entries\&. 
.PP
\fBReturns:\fP
.RS 4
\fBLexicon\fP instance\&. 
.RE
.PP

.PP
Definition at line 283 of file lexicon\&.py\&.
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.convert_to_latex (self)"

.PP
.nf
This method converts the lexicon into LaTeX format.

.fi
.PP
 
.PP
Definition at line 349 of file lexicon\&.py\&.
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.count_lexical_entries (self)"

.PP
Count number of lexical entries of the lexicon\&. 
.PP
\fBReturns:\fP
.RS 4
The number of lexical entries without duplicates maintained by the lexicon\&. 
.RE
.PP

.PP
Definition at line 165 of file lexicon\&.py\&.
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.find_lexical_entries (self, filter)"

.PP
Find all lexical entries which characteristics meet the given condition\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfilter\fP Function or lambda function taking a lexical entry as argument, and returning True or False; for instance 'lambda \fBlexical_entry\fP: lexical_entry\&.get_lexeme() == 'Hello''\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A Python list of LexicalEntry instances\&. 
.RE
.PP

.PP
Definition at line 272 of file lexicon\&.py\&.
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.get_entrySource (self)"

.PP
Get entry source\&. 
.PP
\fBReturns:\fP
.RS 4
\fBLexicon\fP attribute 'entrySource'\&. 
.RE
.PP

.PP
Definition at line 61 of file lexicon\&.py\&.
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.get_id (self)"

.PP
Get identifier\&. 
.PP
\fBReturns:\fP
.RS 4
\fBLexicon\fP attribute 'id'\&. 
.RE
.PP

.PP
Definition at line 47 of file lexicon\&.py\&.
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.get_label (self)"

.PP
Get label\&. 
.PP
\fBReturns:\fP
.RS 4
\fBLexicon\fP attribute 'label'\&. 
.RE
.PP

.PP
Definition at line 103 of file lexicon\&.py\&.
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.get_language (self)"

.PP
Get language\&. 
.PP
\fBReturns:\fP
.RS 4
\fBLexicon\fP attribute 'language'\&. 
.RE
.PP

.PP
Definition at line 75 of file lexicon\&.py\&.
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.get_languageScript (self)"

.PP
Get language script\&. 
.PP
\fBReturns:\fP
.RS 4
\fBLexicon\fP attribute 'languageScript'\&. 
.RE
.PP

.PP
Definition at line 89 of file lexicon\&.py\&.
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.get_lexical_entries (self)"

.PP
Get all lexical entries maintained by the lexicon\&. 
.PP
\fBReturns:\fP
.RS 4
A Python set of lexical entries\&. 
.RE
.PP

.PP
Definition at line 143 of file lexicon\&.py\&.
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.get_lexiconType (self)"

.PP
Get lexicon type\&. 
.PP
\fBReturns:\fP
.RS 4
\fBLexicon\fP attribute 'lexiconType'\&. 
.RE
.PP

.PP
Definition at line 117 of file lexicon\&.py\&.
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.get_localPath (self)"

.PP
Get lexicon local path\&. 
.PP
\fBReturns:\fP
.RS 4
\fBLexicon\fP attribute 'localPath'\&. 
.RE
.PP

.PP
Definition at line 137 of file lexicon\&.py\&.
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.get_vowelHarmony (self)"

.PP
Definition at line 126 of file lexicon\&.py\&.
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.remove_lexical_entry (self, lexical_entry)"

.PP
Remove a lexical entry from the lexicon\&. 
.PP
\fBParameters:\fP
.RS 4
\fI\fBlexical_entry\fP\fP The LexicalEntry instance to remove from the \fBLexicon\fP\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLexicon\fP instance\&. 
.RE
.PP

.PP
Definition at line 157 of file lexicon\&.py\&.
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.reset_check (self)"

.PP
Reset boolean to be able to check all cross-references in the lexicon again\&. Reset the private attribute '__checked'\&. 
.PP
\fBReturns:\fP
.RS 4
\fBLexicon\fP instance\&. 
.RE
.PP

.PP
Definition at line 341 of file lexicon\&.py\&.
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.set_entrySource (self, entry_source)"

.PP
Set lexicon entry source\&. 
.PP
\fBParameters:\fP
.RS 4
\fIentry_source\fP The entry source to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLexicon\fP instance\&. 
.RE
.PP

.PP
Definition at line 53 of file lexicon\&.py\&.
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.set_id (self, id)"

.PP
Set lexicon identifier\&. 
.PP
\fBParameters:\fP
.RS 4
\fIid\fP The identifier to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLexicon\fP instance\&. 
.RE
.PP

.PP
Definition at line 39 of file lexicon\&.py\&.
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.set_label (self, label)"

.PP
Set lexicon label\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlabel\fP The label to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLexicon\fP instance\&. 
.RE
.PP

.PP
Definition at line 95 of file lexicon\&.py\&.
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.set_language (self, language)"

.PP
Set lexicon language\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlanguage\fP The language to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLexicon\fP instance\&. 
.RE
.PP

.PP
Definition at line 67 of file lexicon\&.py\&.
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.set_languageScript (self, language_script)"

.PP
Set lexicon language script\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlanguage_script\fP The language script to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLexicon\fP instance\&. 
.RE
.PP

.PP
Definition at line 81 of file lexicon\&.py\&.
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.set_lexiconType (self, lexicon_type)"

.PP
Set lexicon type\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexicon_type\fP The lexicon type to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLexicon\fP instance\&. 
.RE
.PP

.PP
Definition at line 109 of file lexicon\&.py\&.
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.set_localPath (self, local_path)"

.PP
Set lexicon local path\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlocal_path\fP The absolute path to audio files to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLexicon\fP instance\&. 
.RE
.PP

.PP
Definition at line 129 of file lexicon\&.py\&.
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.set_vowelHarmony (self, vowel_harmony)"

.PP
Definition at line 123 of file lexicon\&.py\&.
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.sort_homonym_numbers (self, items = \fClambda lexical_entry: lexical_entry\&.get_lexeme()\fP, condition = \fClambda lexical_entry: True\fP)"

.PP
Sort similar given items of lexical entries contained in the lexicon according to their homonym number\&. 
.PP
\fBParameters:\fP
.RS 4
\fIitems\fP Lambda function giving the item to sort\&. Default value is 'lambda \fBlexical_entry\fP: lexical_entry\&.get_lexeme()', which means that the items to sort are lexemes\&. 
.br
\fIcondition\fP Lambda function giving a condition to apply classification\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The sorted Python list of lexical entries\&. 
.RE
.PP

.PP
Definition at line 171 of file lexicon\&.py\&.
.SS "def lmf\&.src\&.core\&.lexicon\&.Lexicon\&.sort_lexical_entries (self, items = \fClambda lexical_entry: lexical_entry\&.get_lexeme()\fP, sort_order = \fCNone\fP, comparison = \fCNone\fP)"

.PP
Sort given items of lexical entries contained in the lexicon according to a certain order\&. 
.PP
\fBParameters:\fP
.RS 4
\fIitems\fP Lambda function giving the item to sort\&. Default value is 'lambda \fBlexical_entry\fP: lexical_entry\&.get_lexeme()', which means that the items to sort are lexemes\&. 
.br
\fIsort_order\fP Default value is 'None', which means that the lexicographical ordering uses the ASCII ordering\&. 
.br
\fIcomparison\fP Function to compare items\&. If 'None', a default function to compare character by character is provided\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The sorted Python list of lexical entries\&. 
.RE
.PP

.PP
Definition at line 201 of file lexicon\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.core\&.lexicon\&.Lexicon\&.entrySource"

.PP
Definition at line 22 of file lexicon\&.py\&.
.SS "lmf\&.src\&.core\&.lexicon\&.Lexicon\&.id"

.PP
Definition at line 44 of file lexicon\&.py\&.
.SS "lmf\&.src\&.core\&.lexicon\&.Lexicon\&.label"

.PP
Definition at line 20 of file lexicon\&.py\&.
.SS "lmf\&.src\&.core\&.lexicon\&.Lexicon\&.language"

.PP
Definition at line 18 of file lexicon\&.py\&.
.SS "lmf\&.src\&.core\&.lexicon\&.Lexicon\&.languageScript"

.PP
Definition at line 19 of file lexicon\&.py\&.
.SS "lmf\&.src\&.core\&.lexicon\&.Lexicon\&.lexical_entry"

.PP
All LexicalEntry instances are maintained by \fBLexicon\fP There is one or more LexicalEntry instances per \fBLexicon\fP\&. 
.PP
Definition at line 27 of file lexicon\&.py\&.
.SS "lmf\&.src\&.core\&.lexicon\&.Lexicon\&.lexiconType"

.PP
Definition at line 21 of file lexicon\&.py\&.
.SS "lmf\&.src\&.core\&.lexicon\&.Lexicon\&.localPath"

.PP
Definition at line 24 of file lexicon\&.py\&.
.SS "lmf\&.src\&.core\&.lexicon\&.Lexicon\&.vowelHarmony"

.PP
Definition at line 23 of file lexicon\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
