.TH "lmf.src.config.mdf" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.config.mdf \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBset_bw\fP"
.br
.RI "\fIFunctions to process some MDF fields (input) \fP"
.ti -1c
.RI "def \fBget_bw\fP"
.br
.RI "\fIFunctions to process some MDF fields (output) \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBmdf_lmf\fP"
.br
.RI "\fIMapping between MDF markers and LMF representation (input) \fP"
.ti -1c
.RI "list \fBmdf_order\fP"
.br
.RI "\fIOrder in which MDF markers must be written (output) This is the standard order defined in Appendix B of 'Making Dictionaries\&. A guide to lexicography and the Multi-Dictionary Formatter', Software version 1\&.0, David F\&. \fP"
.ti -1c
.RI "tuple \fBlmf_mdf\fP"
.br
.RI "\fIMapping between LMF representation and MDF markers (output) \fP"
.ti -1c
.RI "tuple \fBps_range\fP"
.br
.RI "\fIPossible values allowed for 'ps' MDF marker\&. \fP"
.ti -1c
.RI "tuple \fBps_partOfSpeech\fP"
.br
.RI "\fIMapping between 'ps' MDF marker value and LMF part of speech LexicalEntry attribute value (input) Source: http://www.isocat.org/rest/dcs/119\&. \fP"
.ti -1c
.RI "tuple \fBmdf_semanticRelation\fP"
.br
.RI "\fIMapping between MDF markers and LMF semantic relation RelatedForm attribute value (input) \fP"
.ti -1c
.RI "tuple \fBpd_person\fP"
.br
.RI "\fIMapping between 'pd' MDF markers and LMF person WordForm attribute value (input) \fP"
.ti -1c
.RI "tuple \fBpd_anymacy\fP"
.br
.RI "\fIMapping between 'pd' MDF markers and LMF anymacy WordForm attribute value (input) \fP"
.ti -1c
.RI "tuple \fBpd_grammaticalNumber\fP"
.br
.RI "\fIMapping between 'pd' MDF markers and LMF grammatical number WordForm attribute value (input) \fP"
.ti -1c
.RI "tuple \fBpd_clusivity\fP"
.br
.RI "\fIMapping between 'pd' MDF markers and LMF clusivity WordForm attribute value (input) \fP"
.ti -1c
.RI "tuple \fBpdl_paradigmLabel\fP"
.br
.RI "\fIMapping between 'pdl' MDF marker value and LMF paradigm label Paradigm attribute value (input) \fP"
.ti -1c
.RI "tuple \fBsd_range\fP"
.br
.RI "\fIPossible values allowed for 'sd' MDF marker\&. \fP"
.ti -1c
.RI "tuple \fBlf_range\fP"
.br
.RI "\fIPossible values allowed for 'lf' MDF marker\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "def lmf\&.src\&.config\&.mdf\&.get_bw (lexical_entry)"

.PP
Functions to process some MDF fields (output) 
.PP
Definition at line 245 of file mdf\&.py\&.
.SS "def lmf\&.src\&.config\&.mdf\&.set_bw (bw, lexical_entry)"

.PP
Functions to process some MDF fields (input) 
.PP
Definition at line 7 of file mdf\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "tuple lmf\&.src\&.config\&.mdf\&.lf_range"

.PP
Possible values allowed for 'lf' MDF marker\&. 
.PP
Definition at line 632 of file mdf\&.py\&.
.SS "tuple lmf\&.src\&.config\&.mdf\&.lmf_mdf"

.PP
Mapping between LMF representation and MDF markers (output) 
.PP
Definition at line 252 of file mdf\&.py\&.
.SS "tuple lmf\&.src\&.config\&.mdf\&.mdf_lmf"

.PP
Mapping between MDF markers and LMF representation (input) 
.PP
Definition at line 19 of file mdf\&.py\&.
.SS "list lmf\&.src\&.config\&.mdf\&.mdf_order"

.PP
Order in which MDF markers must be written (output) This is the standard order defined in Appendix B of 'Making Dictionaries\&. A guide to lexicography and the Multi-Dictionary Formatter', Software version 1\&.0, David F\&. Coward, Charles E\&. Grimes, SIL International, Waxhaw, North Carolina, 2000 
.PP
Definition at line 128 of file mdf\&.py\&.
.SS "tuple lmf\&.src\&.config\&.mdf\&.mdf_semanticRelation"
\fBInitial value:\fP
.PP
.nf
1 = dict({
2     "sy" : "synonym",
3     "an" : "antonym",
4     "hm" : "homonym",
5     "et" : "etymology",
6     "se" : "subentry",
7     "mn" : "main entry",
8     "cf" : "simple link",
9     "cp" : "complex predicate",
10     "lf" : None,
11     "ev" : None,
12     "ee" : None,
13     "en" : None,
14     "er" : None
15     # "derived form",
16     # "root",
17     # "stem",
18     # "collocation"
19 })
.fi
.PP
Mapping between MDF markers and LMF semantic relation RelatedForm attribute value (input) 
.PP
Definition at line 512 of file mdf\&.py\&.
.SS "tuple lmf\&.src\&.config\&.mdf\&.pd_anymacy"
\fBInitial value:\fP
.PP
.nf
1 = dict({
2     4 : "inanimate"
3 })
.fi
.PP
Mapping between 'pd' MDF markers and LMF anymacy WordForm attribute value (input) 
.PP
Definition at line 540 of file mdf\&.py\&.
.SS "tuple lmf\&.src\&.config\&.mdf\&.pd_clusivity"
\fBInitial value:\fP
.PP
.nf
1 = dict({
2     'i'     : "inclusive",
3     'e'     : "exclusive"
4 })
.fi
.PP
Mapping between 'pd' MDF markers and LMF clusivity WordForm attribute value (input) 
.PP
Definition at line 554 of file mdf\&.py\&.
.SS "tuple lmf\&.src\&.config\&.mdf\&.pd_grammaticalNumber"
\fBInitial value:\fP
.PP
.nf
1 = dict({
2     'd'     : "dual",
3     'p'     : "plural",
4     "pl"    : "plural",
5     's'     : "singular",
6     "sg"    : "singular"
7 })
.fi
.PP
Mapping between 'pd' MDF markers and LMF grammatical number WordForm attribute value (input) 
.PP
Definition at line 545 of file mdf\&.py\&.
.SS "tuple lmf\&.src\&.config\&.mdf\&.pd_person"
\fBInitial value:\fP
.PP
.nf
1 = dict({
2     1 : "first person",
3     2 : "second person",
4     3 : "third person"
5 })
.fi
.PP
Mapping between 'pd' MDF markers and LMF person WordForm attribute value (input) 
.PP
Definition at line 533 of file mdf\&.py\&.
.SS "tuple lmf\&.src\&.config\&.mdf\&.pdl_paradigmLabel"
\fBInitial value:\fP
.PP
.nf
1 = dict({
2     "la"        : "lexicalized affix",
3     "cc"        : "conjugation class",
4     "past"      : "past stem",
5     "comit"     : "comitative",
6     "constr"    : "construction",
7     "dir"       : "directional",
8     "ir"        : "irregularity",
9     "cl"        : "classifier"
10 })
.fi
.PP
Mapping between 'pdl' MDF marker value and LMF paradigm label Paradigm attribute value (input) 
.PP
Definition at line 560 of file mdf\&.py\&.
.SS "tuple lmf\&.src\&.config\&.mdf\&.ps_partOfSpeech"

.PP
Mapping between 'ps' MDF marker value and LMF part of speech LexicalEntry attribute value (input) Source: http://www.isocat.org/rest/dcs/119\&. 
.PP
Definition at line 438 of file mdf\&.py\&.
.SS "tuple lmf\&.src\&.config\&.mdf\&.ps_range"

.PP
Possible values allowed for 'ps' MDF marker\&. 
.PP
Definition at line 363 of file mdf\&.py\&.
.SS "tuple lmf\&.src\&.config\&.mdf\&.sd_range"

.PP
Possible values allowed for 'sd' MDF marker\&. 
.PP
Definition at line 572 of file mdf\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
