.TH "lmf.src.morphology.lemma.Lemma" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.morphology.lemma.Lemma \- 
.PP
'Lemma is a Form subclass representing a form chosen by convention to designate the Lexical Entry\&. The lemma is usually equivalent to one of the inflected forms, the root, stem or compound phrase\&.' (LMF)\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "def \fBset_lexeme\fP"
.br
.RI "\fISet lexeme\&. \fP"
.ti -1c
.RI "def \fBget_lexeme\fP"
.br
.RI "\fIGet lexeme\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhyphenation\fP"
.br
.ti -1c
.RI "\fBlexeme\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
'Lemma is a Form subclass representing a form chosen by convention to designate the Lexical Entry\&. The lemma is usually equivalent to one of the inflected forms, the root, stem or compound phrase\&.' (LMF)\&. 
.PP
Definition at line 8 of file lemma\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.__init__ (self)"

.PP
Constructor\&. \fBLemma\fP instance is owned by LexicalEntry\&. 
.PP
\fBReturns:\fP
.RS 4
A \fBLemma\fP instance\&. 
.RE
.PP

.PP
Definition at line 11 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.__del__ (self)"

.PP
Destructor\&. 
.PP
Definition at line 21 of file lemma\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.get_lexeme (self)"

.PP
Get lexeme\&. 
.PP
\fBReturns:\fP
.RS 4
\fBLemma\fP attribute 'lexeme'\&. 
.RE
.PP

.PP
Definition at line 34 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.set_lexeme (self, lexeme)"

.PP
Set lexeme\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexeme\fP The lexeme to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLemma\fP instance\&. 
.RE
.PP

.PP
Definition at line 26 of file lemma\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.morphology\&.lemma\&.Lemma\&.hyphenation"

.PP
Definition at line 18 of file lemma\&.py\&.
.SS "lmf\&.src\&.morphology\&.lemma\&.Lemma\&.lexeme"

.PP
Definition at line 19 of file lemma\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
