.TH "lmf.src.utils.log" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.utils.log \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBlog\fP"
.br
.RI "\fIWrite message into log file if any, or to standard output if verbose mode is on\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "def lmf\&.src\&.utils\&.log\&.log (msg, options = \fCNone\fP)"

.PP
Write message into log file if any, or to standard output if verbose mode is on\&. 
.PP
\fBParameters:\fP
.RS 4
\fImsg\fP String to log\&. 
.br
\fIoptions\fP User options\&. 
.RE
.PP

.PP
Definition at line 6 of file log\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
