.TH "lmf.src.config.xml" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.config.xml \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBsort_order_read\fP"
.br
.RI "\fIRead an XML file giving sort order\&. \fP"
.ti -1c
.RI "def \fBconfig_read\fP"
.br
.RI "\fIRead an XML file giving the user configuration\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "def lmf\&.src\&.config\&.xml\&.config_read (filename)"

.PP
Read an XML file giving the user configuration\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP The name of the XML file to read with full path, for instance 'user/default/config\&.xml'\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A Lexical Resource\&. 
.RE
.PP

.PP
Definition at line 45 of file xml\&.py\&.
.SS "def lmf\&.src\&.config\&.xml\&.sort_order_read (filename)"

.PP
Read an XML file giving sort order\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP The name of the XML file to read with full path, for instance 'user/default/sort_order\&.xml'\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A Python dictionary of ordered characters\&. 
.RE
.PP

.PP
Definition at line 19 of file xml\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
