.TH "lmf.src.mrd.context" 3 "Thu Nov 27 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.mrd.context \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBContext\fP"
.br
.RI "\fI'Context is a class representing a text string that provides authentic context for the use of the word form managed by the Lemma\&. This class is to be distinguished from Sense Example\&.' (LMF) \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
