.TH "lmf.src.common.defs" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.common.defs \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBVERNACULAR\fP = 'vernacular'"
.br
.RI "\fIDefine languages\&. \fP"
.ti -1c
.RI "string \fBENGLISH\fP = 'English'"
.br
.ti -1c
.RI "string \fBNATIONAL\fP = 'national'"
.br
.ti -1c
.RI "string \fBREGIONAL\fP = 'regional'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string lmf\&.src\&.common\&.defs\&.ENGLISH = 'English'"

.PP
Definition at line 5 of file defs\&.py\&.
.SS "string lmf\&.src\&.common\&.defs\&.NATIONAL = 'national'"

.PP
Definition at line 6 of file defs\&.py\&.
.SS "string lmf\&.src\&.common\&.defs\&.REGIONAL = 'regional'"

.PP
Definition at line 7 of file defs\&.py\&.
.SS "string lmf\&.src\&.common\&.defs\&.VERNACULAR = 'vernacular'"

.PP
Define languages\&. 
.PP
Definition at line 4 of file defs\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
