.TH "lmf.src.core.lexical_resource.LexicalResource" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.core.lexical_resource.LexicalResource \- 
.PP
'Lexical Resource is a class representing the entire resource and is a container for one or more lexicons\&. There is only one Lexical Resource instance\&.' (LMF)  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "def \fBget_lexicons\fP"
.br
.RI "\fIGet all lexicons maintained by the lexical resource\&. \fP"
.ti -1c
.RI "def \fBadd_lexicon\fP"
.br
.RI "\fIAdd a lexicon to the lexical resource\&. \fP"
.ti -1c
.RI "def \fBremove_lexicon\fP"
.br
.RI "\fIRemove a lexicon from the lexical resource\&. \fP"
.ti -1c
.RI "def \fBget_lexicon\fP"
.br
.ti -1c
.RI "def \fBset_dtdVersion\fP"
.br
.RI "\fISet DTD version\&. \fP"
.ti -1c
.RI "def \fBget_dtdVersion\fP"
.br
.RI "\fIGet DTD version\&. \fP"
.ti -1c
.RI "def \fBset_language_code\fP"
.br
.RI "\fISet language code\&. \fP"
.ti -1c
.RI "def \fBget_language_code\fP"
.br
.RI "\fIGet language code\&. \fP"
.ti -1c
.RI "def \fBset_version\fP"
.br
.RI "\fISet version\&. \fP"
.ti -1c
.RI "def \fBget_version\fP"
.br
.RI "\fIGet version\&. \fP"
.ti -1c
.RI "def \fBset_license\fP"
.br
.RI "\fISet license\&. \fP"
.ti -1c
.RI "def \fBget_license\fP"
.br
.RI "\fIGet license\&. \fP"
.ti -1c
.RI "def \fBset_character_encoding\fP"
.br
.RI "\fISet character encoding\&. \fP"
.ti -1c
.RI "def \fBget_character_encoding\fP"
.br
.RI "\fIGet character encoding\&. \fP"
.ti -1c
.RI "def \fBset_date_coding\fP"
.br
.RI "\fISet date coding\&. \fP"
.ti -1c
.RI "def \fBget_date_coding\fP"
.br
.RI "\fIGet date coding\&. \fP"
.ti -1c
.RI "def \fBset_project_name\fP"
.br
.RI "\fISet project name\&. \fP"
.ti -1c
.RI "def \fBget_project_name\fP"
.br
.RI "\fIGet project name\&. \fP"
.ti -1c
.RI "def \fBset_creation_date\fP"
.br
.RI "\fISet creation date\&. \fP"
.ti -1c
.RI "def \fBget_creation_date\fP"
.br
.RI "\fIGet creation date\&. \fP"
.ti -1c
.RI "def \fBset_last_update\fP"
.br
.RI "\fISet last update\&. \fP"
.ti -1c
.RI "def \fBget_last_update\fP"
.br
.RI "\fIGet last update\&. \fP"
.ti -1c
.RI "def \fBset_author\fP"
.br
.RI "\fISet author\&. \fP"
.ti -1c
.RI "def \fBget_author\fP"
.br
.RI "\fIGet author\&. \fP"
.ti -1c
.RI "def \fBset_description\fP"
.br
.RI "\fISet description\&. \fP"
.ti -1c
.RI "def \fBget_description\fP"
.br
.RI "\fIGet description\&. \fP"
.ti -1c
.RI "def \fBget_bibliographic_citation\fP"
.br
.RI "\fIGet bibliographic citation\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdtdVersion\fP"
.br
.ti -1c
.RI "\fBglobal_information\fP"
.br
.RI "\fIGlobalInformation instance is owned by \fBLexicalResource\fP There is one GlobalInformation for one \fBLexicalResource\fP\&. \fP"
.ti -1c
.RI "\fBlexicon\fP"
.br
.RI "\fILexicon instances are owned by \fBLexicalResource\fP There is one or more Lexicon instances for one unique \fBLexicalResource\fP\&. \fP"
.ti -1c
.RI "\fBspeaker\fP"
.br
.RI "\fISpeaker instances are owned by \fBLexicalResource\fP There is zero to many Speaker instances for one unique \fBLexicalResource\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
'Lexical Resource is a class representing the entire resource and is a container for one or more lexicons\&. There is only one Lexical Resource instance\&.' (LMF) 
.PP
Definition at line 8 of file lexical_resource\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.__init__ (self, dtd_version = \fC16\fP)"

.PP
Constructor\&. 
.PP
\fBReturns:\fP
.RS 4
A \fBLexicalResource\fP instance\&. 
.RE
.PP

.PP
Definition at line 11 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.__del__ (self)"

.PP
Destructor\&. Release GlobalInformation, Lexicon, Speaker instances\&. 
.PP
Definition at line 26 of file lexical_resource\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.add_lexicon (self, lexicon)"

.PP
Add a lexicon to the lexical resource\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexicon\fP A Lexicon instance to add to the Lexical Resource\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Lexical Resource instance\&. 
.RE
.PP

.PP
Definition at line 45 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.get_author (self)"

.PP
Get author\&. Attribute 'author' is owned by GlobalInformation\&. 
.PP
\fBReturns:\fP
.RS 4
GlobalInformation attribute 'author'\&. 
.RE
.PP

.PP
Definition at line 221 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.get_bibliographic_citation (self)"

.PP
Get bibliographic citation\&. Attribute 'bibliographicCitation' is owned by GlobalInformation\&. 
.PP
\fBReturns:\fP
.RS 4
GlobalInformation attribute 'bibliographicCitation'\&. 
.RE
.PP

.PP
Definition at line 244 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.get_character_encoding (self)"

.PP
Get character encoding\&. Attribute 'characterEncoding' is owned by GlobalInformation\&. 
.PP
\fBReturns:\fP
.RS 4
GlobalInformation attribute 'characterEncoding'\&. 
.RE
.PP

.PP
Definition at line 141 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.get_creation_date (self)"

.PP
Get creation date\&. Attribute 'creationDate' is owned by GlobalInformation\&. 
.PP
\fBReturns:\fP
.RS 4
GlobalInformation attribute 'creationdDate'\&. 
.RE
.PP

.PP
Definition at line 189 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.get_date_coding (self)"

.PP
Get date coding\&. Attribute 'dateCoding' is owned by GlobalInformation\&. 
.PP
\fBReturns:\fP
.RS 4
GlobalInformation attribute 'dateCoding'\&. 
.RE
.PP

.PP
Definition at line 157 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.get_description (self)"

.PP
Get description\&. Attribute 'description' is owned by GlobalInformation\&. 
.PP
\fBReturns:\fP
.RS 4
GlobalInformation attribute 'description'\&. 
.RE
.PP

.PP
Definition at line 237 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.get_dtdVersion (self)"

.PP
Get DTD version\&. 
.PP
\fBReturns:\fP
.RS 4
\fBLexicalResource\fP attribute 'dtdVersion'\&. 
.RE
.PP

.PP
Definition at line 78 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.get_language_code (self)"

.PP
Get language code\&. Attribute 'languageCode' is owned by GlobalInformation\&. 
.PP
\fBReturns:\fP
.RS 4
GlobalInformation attribute 'languageCode'\&. 
.RE
.PP

.PP
Definition at line 93 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.get_last_update (self)"

.PP
Get last update\&. Attribute 'lastUpdate' is owned by GlobalInformation\&. 
.PP
\fBReturns:\fP
.RS 4
GlobalInformation attribute 'lastUpdate'\&. 
.RE
.PP

.PP
Definition at line 205 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.get_lexicon (self, id)"

.PP
.nf
Retrieve a lexicon from its identifier.
@param id The identifier of the lexicon to retrieve.
@result A Lexicon instance, or None if not found.

.fi
.PP
 
.PP
Definition at line 61 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.get_lexicons (self)"

.PP
Get all lexicons maintained by the lexical resource\&. 
.PP
\fBReturns:\fP
.RS 4
A Python list of lexicons\&. 
.RE
.PP

.PP
Definition at line 39 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.get_license (self)"

.PP
Get license\&. Attribute 'license' is owned by GlobalInformation\&. 
.PP
\fBReturns:\fP
.RS 4
GlobalInformation attribute 'license'\&. 
.RE
.PP

.PP
Definition at line 125 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.get_project_name (self)"

.PP
Get project name\&. Attribute 'projectName' is owned by GlobalInformation\&. 
.PP
\fBReturns:\fP
.RS 4
GlobalInformation attribute 'projectName'\&. 
.RE
.PP

.PP
Definition at line 173 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.get_version (self)"

.PP
Get version\&. Attribute 'version' is owned by GlobalInformation\&. 
.PP
\fBReturns:\fP
.RS 4
GlobalInformation attribute 'version'\&. 
.RE
.PP

.PP
Definition at line 109 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.remove_lexicon (self, lexicon)"

.PP
Remove a lexicon from the lexical resource\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexicon\fP The Lexicon instance to remove from the Lexical Resource\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Lexical Resource instance\&. 
.RE
.PP

.PP
Definition at line 53 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.set_author (self, author)"

.PP
Set author\&. Attribute 'author' is owned by GlobalInformation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIauthor\fP The author's name to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLexicalResource\fP instance\&. 
.RE
.PP

.PP
Definition at line 212 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.set_character_encoding (self, character_encoding)"

.PP
Set character encoding\&. Attribute 'characterEncoding' is owned by GlobalInformation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcharacter_encoding\fP The character encoding to use\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLexicalResource\fP instance\&. 
.RE
.PP

.PP
Definition at line 132 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.set_creation_date (self, date)"

.PP
Set creation date\&. Attribute 'creationDate' is owned by GlobalInformation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdate\fP The date to set, in format YYYY-MM-DD\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLexicalResource\fP instance\&. 
.RE
.PP

.PP
Definition at line 180 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.set_date_coding (self, date_coding)"

.PP
Set date coding\&. Attribute 'dateCoding' is owned by GlobalInformation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdate_coding\fP The date coding to use\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLexicalResource\fP instance\&. 
.RE
.PP

.PP
Definition at line 148 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.set_description (self, description)"

.PP
Set description\&. Attribute 'description' is owned by GlobalInformation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdescription\fP The description to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLexicalResource\fP instance\&. 
.RE
.PP

.PP
Definition at line 228 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.set_dtdVersion (self, dtd_version)"

.PP
Set DTD version\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdtd_version\fP The DTD version to use\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLexicalResource\fP instance\&. 
.RE
.PP

.PP
Definition at line 70 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.set_language_code (self, language_code)"

.PP
Set language code\&. Attribute 'languageCode' is owned by GlobalInformation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlanguage_code\fP The language code to use\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLexicalResource\fP instance\&. 
.RE
.PP

.PP
Definition at line 84 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.set_last_update (self, date)"

.PP
Set last update\&. Attribute 'lastUpdate' is owned by GlobalInformation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdate\fP The date to set, in format YYYY-MM-DD\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLexicalResource\fP instance\&. 
.RE
.PP

.PP
Definition at line 196 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.set_license (self, license)"

.PP
Set license\&. Attribute 'license' is owned by GlobalInformation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlicense\fP The license to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLexicalResource\fP instance\&. 
.RE
.PP

.PP
Definition at line 116 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.set_project_name (self, project_name)"

.PP
Set project name\&. Attribute 'projectName' is owned by GlobalInformation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIproject_name\fP The project's name to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLexicalResource\fP instance\&. 
.RE
.PP

.PP
Definition at line 164 of file lexical_resource\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.set_version (self, version)"

.PP
Set version\&. Attribute 'version' is owned by GlobalInformation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIversion\fP The version to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLexicalResource\fP instance\&. 
.RE
.PP

.PP
Definition at line 100 of file lexical_resource\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.dtdVersion"

.PP
Definition at line 15 of file lexical_resource\&.py\&.
.SS "lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.global_information"

.PP
GlobalInformation instance is owned by \fBLexicalResource\fP There is one GlobalInformation for one \fBLexicalResource\fP\&. 
.PP
Definition at line 18 of file lexical_resource\&.py\&.
.SS "lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.lexicon"

.PP
Lexicon instances are owned by \fBLexicalResource\fP There is one or more Lexicon instances for one unique \fBLexicalResource\fP\&. 
.PP
Definition at line 21 of file lexical_resource\&.py\&.
.SS "lmf\&.src\&.core\&.lexical_resource\&.LexicalResource\&.speaker"

.PP
Speaker instances are owned by \fBLexicalResource\fP There is zero to many Speaker instances for one unique \fBLexicalResource\fP\&. 
.PP
Definition at line 24 of file lexical_resource\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
