.TH "lmf.src.output.mdf" 3 "Thu Nov 27 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.output.mdf \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmdf_write\fP"
.br
.RI "\fIWrite an MDF file\&. \fP"
.ti -1c
.RI "def \fBparse_list\fP"
.br
.RI "\fIParse a group of markers and write them into an MDF file\&. \fP"
.ti -1c
.RI "def \fBwrite_line\fP"
.br
.RI "\fIWrite a line into an MDF file\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "def lmf\&.src\&.output\&.mdf\&.mdf_write (object, filename, lmf2mdf = \fClmf_mdf\fP, order = \fCmdf_order\fP)"

.PP
Write an MDF file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIobject\fP The LMF instance to convert into MDF output format\&. 
.br
\fIfilename\fP The name of the MDF file to write with full path, for instance 'user/output\&.txt'\&. 
.br
\fIlmf2mdf\fP A Python dictionary describing the mapping between LMF representation and MDF markers\&. Default value is 'lmf_mdf' dictionary defined in '\fBsrc/config/mdf\&.py\fP'\&. Please refer to it as an example\&. 
.br
\fIorder\fP A Python list defining the order in which MDF markers must be written, for instance ['lx', 'ps']\&. Default value is 'mdf_order' list defined in '\fBsrc/config/mdf\&.py\fP'\&. 
.RE
.PP

.PP
Definition at line 7 of file mdf\&.py\&.
.SS "def lmf\&.src\&.output\&.mdf\&.parse_list (mdf_file, lmf2mdf, marker, object)"

.PP
Parse a group of markers and write them into an MDF file\&. 
.PP
\fBParameters:\fP
.RS 4
\fImdf_file\fP The file to write in\&. 
.br
\fIlmf2mdf\fP A Python dictionary describing the mapping between LMF representation and MDF markers\&. 
.br
\fImarker\fP The MDF marker\&. 
.br
\fIobject\fP The current processed object\&. 
.RE
.PP

.PP
Definition at line 31 of file mdf\&.py\&.
.SS "def lmf\&.src\&.output\&.mdf\&.write_line (mdf_file, marker, value)"

.PP
Write a line into an MDF file\&. 
.PP
\fBParameters:\fP
.RS 4
\fImdf_file\fP The file to write in\&. 
.br
\fImarker\fP The MDF marker\&. 
.br
\fIvalue\fP The corresponding value\&. 
.RE
.PP

.PP
Definition at line 49 of file mdf\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
