.TH "lmf.src.resources.speaker.Speaker" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.resources.speaker.Speaker \- 
.PP
\fBSpeaker\fP is a HumanResource subclass\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits HumanResource\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIDestructor\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBspeakerID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBSpeaker\fP is a HumanResource subclass\&. 

The \fBSpeaker\fP is a class representing a speaker\&. 
.PP
Definition at line 8 of file speaker\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.resources\&.speaker\&.Speaker\&.__init__ (self)"

.PP
Constructor\&. \fBSpeaker\fP instances are owned by LexicalResource\&. 
.PP
\fBReturns:\fP
.RS 4
A \fBSpeaker\fP instance\&. 
.RE
.PP

.PP
Definition at line 11 of file speaker\&.py\&.
.SS "def lmf\&.src\&.resources\&.speaker\&.Speaker\&.__del__ (self)"

.PP
Destructor\&. 
.PP
Definition at line 20 of file speaker\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.resources\&.speaker\&.Speaker\&.speakerID"

.PP
Definition at line 18 of file speaker\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
