.TH "lmf.src.mrd.context.Context" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.mrd.context.Context \- 
.PP
'Context is a class representing a text string that provides authentic context for the use of the word form managed by the Lemma\&. This class is to be distinguished from Sense Example\&.' (LMF)  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "def \fBset_type\fP"
.br
.RI "\fISet context type\&. \fP"
.ti -1c
.RI "def \fBget_type\fP"
.br
.RI "\fIGet context type\&. \fP"
.ti -1c
.RI "def \fBcreate_text_representation\fP"
.br
.RI "\fICreate a text representation\&. \fP"
.ti -1c
.RI "def \fBadd_text_representation\fP"
.br
.RI "\fIAdd a text representation to the context\&. \fP"
.ti -1c
.RI "def \fBget_text_representations\fP"
.br
.RI "\fIGet all text representations maintained by the context\&. \fP"
.ti -1c
.RI "def \fBget_last_text_representation\fP"
.br
.RI "\fIGet the previously registered TextRepresentation instance\&. \fP"
.ti -1c
.RI "def \fBfind_written_forms\fP"
.br
.RI "\fIFind written forms\&. \fP"
.ti -1c
.RI "def \fBget_comments\fP"
.br
.RI "\fIGet comments\&. \fP"
.ti -1c
.RI "def \fBset_written_form\fP"
.br
.RI "\fISet text representation written form, language and script\&. \fP"
.ti -1c
.RI "def \fBset_comment\fP"
.br
.RI "\fISet text representation comment\&. \fP"
.ti -1c
.RI "def \fBget_speakerID\fP"
.br
.RI "\fIGet related speaker identifier\&. \fP"
.ti -1c
.RI "def \fBget_speaker\fP"
.br
.RI "\fIGet speaker\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlanguage\fP"
.br
.ti -1c
.RI "\fBtype\fP"
.br
.ti -1c
.RI "\fBtext_representation\fP"
.br
.RI "\fITextRepresentation instances are owned by \fBContext\fP There is zero to many TextRepresentation instances per \fBContext\fP\&. \fP"
.ti -1c
.RI "\fBtargets\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
'Context is a class representing a text string that provides authentic context for the use of the word form managed by the Lemma\&. This class is to be distinguished from Sense Example\&.' (LMF) 
.PP
Definition at line 10 of file context\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.mrd\&.context\&.Context\&.__init__ (self, speakerID = \fCNone\fP)"

.PP
Constructor\&. \fBContext\fP instances are owned by Sense\&. 
.PP
\fBParameters:\fP
.RS 4
\fIspeakerID\fP Related speaker identifier\&. If not provided, default value is None\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A \fBContext\fP instance\&. 
.RE
.PP

.PP
Definition at line 13 of file context\&.py\&.
.SS "def lmf\&.src\&.mrd\&.context\&.Context\&.__del__ (self)"

.PP
Destructor\&. Release TextRepresentation instances\&. 
.PP
Definition at line 30 of file context\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lmf\&.src\&.mrd\&.context\&.Context\&.add_text_representation (self, text_representation)"

.PP
Add a text representation to the context\&. 
.PP
\fBParameters:\fP
.RS 4
\fItext_representation\fP The TextRepresentation instance to add to the context\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBContext\fP instance\&. 
.RE
.PP

.PP
Definition at line 65 of file context\&.py\&.
.SS "def lmf\&.src\&.mrd\&.context\&.Context\&.create_text_representation (self)"

.PP
Create a text representation\&. 
.PP
\fBReturns:\fP
.RS 4
TextRepresentation instance\&. 
.RE
.PP

.PP
Definition at line 59 of file context\&.py\&.
.SS "def lmf\&.src\&.mrd\&.context\&.Context\&.find_written_forms (self, language = \fCNone\fP, script_name = \fCNone\fP)"

.PP
Find written forms\&. This attribute is owned by TextRepresentation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlanguage\fP If given, the language to consider to retrieve the written form\&. 
.br
\fIscript_name\fP If given, the script to consider to retrieve the written form\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A Python list of found TextRepresentation attributes 'writtenForm'\&. 
.RE
.PP

.PP
Definition at line 86 of file context\&.py\&.
.SS "def lmf\&.src\&.mrd\&.context\&.Context\&.get_comments (self)"

.PP
Get comments\&. This attribute is owned by TextRepresentation\&. 
.PP
\fBReturns:\fP
.RS 4
A Python list of found TextRepresentation attributes 'comment'\&. 
.RE
.PP

.PP
Definition at line 100 of file context\&.py\&.
.SS "def lmf\&.src\&.mrd\&.context\&.Context\&.get_last_text_representation (self)"

.PP
Get the previously registered TextRepresentation instance\&. 
.PP
\fBReturns:\fP
.RS 4
The last element of \fBContext\fP attribute 'text_representation'\&. 
.RE
.PP

.PP
Definition at line 79 of file context\&.py\&.
.SS "def lmf\&.src\&.mrd\&.context\&.Context\&.get_speaker (self)"

.PP
Get speaker\&. 
.PP
\fBReturns:\fP
.RS 4
\fBContext\fP private attribute '__speaker'\&. 
.RE
.PP

.PP
Definition at line 150 of file context\&.py\&.
.SS "def lmf\&.src\&.mrd\&.context\&.Context\&.get_speakerID (self)"

.PP
Get related speaker identifier\&. 
.PP
\fBReturns:\fP
.RS 4
\fBContext\fP attribute 'targets'\&. 
.RE
.PP

.PP
Definition at line 144 of file context\&.py\&.
.SS "def lmf\&.src\&.mrd\&.context\&.Context\&.get_text_representations (self)"

.PP
Get all text representations maintained by the context\&. 
.PP
\fBReturns:\fP
.RS 4
A Python list of text representations\&. 
.RE
.PP

.PP
Definition at line 73 of file context\&.py\&.
.SS "def lmf\&.src\&.mrd\&.context\&.Context\&.get_type (self)"

.PP
Get context type\&. 
.PP
\fBReturns:\fP
.RS 4
\fBContext\fP attribute 'type'\&. 
.RE
.PP

.PP
Definition at line 53 of file context\&.py\&.
.SS "def lmf\&.src\&.mrd\&.context\&.Context\&.set_comment (self, comment)"

.PP
Set text representation comment\&. Attribute 'comment' is owned by TextRepresentation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcomment\fP The comment to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBContext\fP instance\&. 
.RE
.PP

.PP
Definition at line 128 of file context\&.py\&.
.SS "def lmf\&.src\&.mrd\&.context\&.Context\&.set_type (self, type)"

.PP
Set context type\&. 
.PP
\fBParameters:\fP
.RS 4
\fItype\fP Type of text representations, in range 'type_example_range' defined in '\fBcommon/range\&.py\fP'\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBContext\fP instance\&. 
.RE
.PP

.PP
Definition at line 40 of file context\&.py\&.
.SS "def lmf\&.src\&.mrd\&.context\&.Context\&.set_written_form (self, written_form, language = \fCNone\fP, script_name = \fCNone\fP)"

.PP
Set text representation written form, language and script\&. Attributes 'writtenForm', 'language' and 'scriptName' are owned by TextRepresentation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIwritten_form\fP The written form to set\&. 
.br
\fIlanguage\fP Language of the written form\&. 
.br
\fIscript_name\fP The name of the script used to write the form, e\&.g\&. devanagari\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBContext\fP instance\&. 
.RE
.PP

.PP
Definition at line 111 of file context\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.mrd\&.context\&.Context\&.language"

.PP
Definition at line 19 of file context\&.py\&.
.SS "lmf\&.src\&.mrd\&.context\&.Context\&.targets"

.PP
Definition at line 25 of file context\&.py\&.
.SS "lmf\&.src\&.mrd\&.context\&.Context\&.text_representation"

.PP
TextRepresentation instances are owned by \fBContext\fP There is zero to many TextRepresentation instances per \fBContext\fP\&. 
.PP
Definition at line 23 of file context\&.py\&.
.SS "lmf\&.src\&.mrd\&.context\&.Context\&.type"

.PP
Definition at line 20 of file context\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
