.TH "lmf.src.resources.audio.Audio" 3 "Thu Nov 27 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.resources.audio.Audio \- 
.PP
\fBAudio\fP is a Material subclass representing an audio recording\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Material\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIDestructor\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBquality\fP"
.br
.ti -1c
.RI "\fBsound\fP"
.br
.ti -1c
.RI "\fBstartPosition\fP"
.br
.ti -1c
.RI "\fBdurationOfEffectiveSpeech\fP"
.br
.ti -1c
.RI "\fBexternalReference\fP"
.br
.ti -1c
.RI "\fBaudioFileFormat\fP"
.br
.ti -1c
.RI "\fBtranscription\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAudio\fP is a Material subclass representing an audio recording\&. 
.PP
Definition at line 8 of file audio\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.resources\&.audio\&.Audio\&.__init__ (self)"

.PP
Constructor\&. \fBAudio\fP instances are owned by FormRepresentation\&. 
.PP
\fBReturns:\fP
.RS 4
An \fBAudio\fP instance\&. 
.RE
.PP

.PP
Definition at line 11 of file audio\&.py\&.
.SS "def lmf\&.src\&.resources\&.audio\&.Audio\&.__del__ (self)"

.PP
Destructor\&. 
.PP
Definition at line 26 of file audio\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.resources\&.audio\&.Audio\&.audioFileFormat"

.PP
Definition at line 23 of file audio\&.py\&.
.SS "lmf\&.src\&.resources\&.audio\&.Audio\&.durationOfEffectiveSpeech"

.PP
Definition at line 21 of file audio\&.py\&.
.SS "lmf\&.src\&.resources\&.audio\&.Audio\&.externalReference"

.PP
Definition at line 22 of file audio\&.py\&.
.SS "lmf\&.src\&.resources\&.audio\&.Audio\&.quality"

.PP
Definition at line 18 of file audio\&.py\&.
.SS "lmf\&.src\&.resources\&.audio\&.Audio\&.sound"

.PP
Definition at line 19 of file audio\&.py\&.
.SS "lmf\&.src\&.resources\&.audio\&.Audio\&.startPosition"

.PP
Definition at line 20 of file audio\&.py\&.
.SS "lmf\&.src\&.resources\&.audio\&.Audio\&.transcription"

.PP
Definition at line 24 of file audio\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
