.TH "lmf.src.output.xml_lmf" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.output.xml_lmf \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBxml_lmf_write\fP"
.br
.RI "\fIWrite an XML LMF file\&. \fP"
.ti -1c
.RI "def \fBbuild_sub_elements\fP"
.br
.RI "\fICreate XML sub-elements to an existing XML element by parsing an LMF object instance\&. \fP"
.ti -1c
.RI "def \fBadd_link\fP"
.br
.RI "\fIFunctions to process XML/XHTML layout\&. \fP"
.ti -1c
.RI "def \fBhandle_reserved\fP"
.br
.ti -1c
.RI "def \fBhandle_fv\fP"
.br
.ti -1c
.RI "def \fBhandle_fn\fP"
.br
.ti -1c
.RI "def \fBhandle_font\fP"
.br
.ti -1c
.RI "def \fBhandle_pinyin\fP"
.br
.ti -1c
.RI "def \fBhandle_caps\fP"
.br
.ti -1c
.RI "def \fBhandle_tones\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def lmf\&.src\&.output\&.xml_lmf\&.add_link (object, element)"

.PP
Functions to process XML/XHTML layout\&. 
.PP
.nf
Insert an hyperlink <a href=xxx>xxx<a/> in XML.

.fi
.PP
 
.PP
Definition at line 66 of file xml_lmf\&.py\&.
.SS "def lmf\&.src\&.output\&.xml_lmf\&.build_sub_elements (object, element)"

.PP
Create XML sub-elements to an existing XML element by parsing an LMF object instance\&. 
.PP
\fBParameters:\fP
.RS 4
\fIobject\fP An LMF object instance\&. 
.br
\fIelement\fP XML element for which sub-elements have to be created according to LMF object attributes\&. 
.RE
.PP

.PP
Definition at line 19 of file xml_lmf\&.py\&.
.SS "def lmf\&.src\&.output\&.xml_lmf\&.handle_caps (element)"

.PP
.nf
Handle small caps.
Replace '°xxx' by '<span class="sc">xxx</span>'.

.fi
.PP
 
.PP
Definition at line 236 of file xml_lmf\&.py\&.
.SS "def lmf\&.src\&.output\&.xml_lmf\&.handle_fn (element)"

.PP
.nf
Replace 'fn:xxx' and '|fn{xxx}' by '<span class="national">xxx</span>'.

.fi
.PP
 
.PP
Definition at line 131 of file xml_lmf\&.py\&.
.SS "def lmf\&.src\&.output\&.xml_lmf\&.handle_font (element)"

.PP
.nf
Replace '{xxx}' by '<span class="ipa">xxx</span>'.

.fi
.PP
 
.PP
Definition at line 168 of file xml_lmf\&.py\&.
.SS "def lmf\&.src\&.output\&.xml_lmf\&.handle_fv (element)"

.PP
.nf
Replace 'fv:xxx' and '|fv{xxx}' by '<span class="vernacular">xxx</span>'.

.fi
.PP
 
.PP
Definition at line 92 of file xml_lmf\&.py\&.
.SS "def lmf\&.src\&.output\&.xml_lmf\&.handle_pinyin (element)"

.PP
.nf
Replace '@xxx' by '<span class="pinyin">xxx</span>'.

.fi
.PP
 
.PP
Definition at line 202 of file xml_lmf\&.py\&.
.SS "def lmf\&.src\&.output\&.xml_lmf\&.handle_reserved (element)"

.PP
.nf
Handle reserved characters.

.fi
.PP
 
.PP
Definition at line 87 of file xml_lmf\&.py\&.
.SS "def lmf\&.src\&.output\&.xml_lmf\&.handle_tones (element)"

.PP
.nf
Replace tones subscripts by '<sub>xxx</sub>'.

.fi
.PP
 
.PP
Definition at line 271 of file xml_lmf\&.py\&.
.SS "def lmf\&.src\&.output\&.xml_lmf\&.xml_lmf_write (object, filename)"

.PP
Write an XML LMF file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIobject\fP The LMF instance to write as XML\&. 
.br
\fIfilename\fP The name of the XML LMF file to write with full path, for instance 'user/output\&.xml'\&. 
.RE
.PP

.PP
Definition at line 7 of file xml_lmf\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
