.TH "lmf.src.resources.video.Video" 3 "Thu Nov 27 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.resources.video.Video \- 
.PP
\fBVideo\fP is a Material subclass representing a video\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Material\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIDestructor\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdescription\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBVideo\fP is a Material subclass representing a video\&. 
.PP
Definition at line 8 of file video\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.resources\&.video\&.Video\&.__init__ (self)"

.PP
Constructor\&. \fBVideo\fP instances are owned by ?\&. 
.PP
\fBReturns:\fP
.RS 4
A \fBVideo\fP instance\&. 
.RE
.PP

.PP
Definition at line 11 of file video\&.py\&.
.SS "def lmf\&.src\&.resources\&.video\&.Video\&.__del__ (self)"

.PP
Destructor\&. 
.PP
Definition at line 20 of file video\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.resources\&.video\&.Video\&.description"

.PP
Definition at line 18 of file video\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
