.TH "lmf.src.utils.error_handling" 3 "Thu Nov 27 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.utils.error_handling \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBError\fP"
.br
.RI "\fIBase class for exceptions in this library\&. \fP"
.ti -1c
.RI "class \fBInputError\fP"
.br
.RI "\fIException raised for errors in the input\&. \fP"
.ti -1c
.RI "class \fBOutputError\fP"
.br
.RI "\fIException raised for errors in the output\&. \fP"
.ti -1c
.RI "class \fBWarning\fP"
.br
.RI "\fIBase class for warnings in this library\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
