.TH "lmf.src.input.mdf" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.input.mdf \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmdf_read\fP"
.br
.RI "\fIRead an MDF file\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "def lmf\&.src\&.input\&.mdf\&.mdf_read (filename = \fCNone\fP, mdf2lmf = \fCmdf_lmf\fP, lexicon = \fCNone\fP, id = \fCNone\fP, encoding = \fCENCODING\fP)"

.PP
Read an MDF file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP The name of the MDF file to read with full path, for instance 'user/input\&.txt'\&. 
.br
\fImdf2lmf\fP A Python dictionary describing the mapping between MDF markers and LMF representation\&. Default value is 'mdf_lmf' dictionary defined in '\fBsrc/config/mdf\&.py\fP'\&. Please refer to it as an example\&. 
.br
\fIlexicon\fP An existing Lexicon to fill with lexical entries to read\&. 
.br
\fIid\fP A Python string identifying the lexicon to create\&. 
.br
\fIencoding\fP Use 'utf-8' encoding by default\&. Otherwise, user has to precise the native encoding of its document\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A Lexicon instance containing all lexical entries\&. 
.RE
.PP

.PP
Definition at line 13 of file mdf\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
