.TH "lmf.src.utils.xml_format" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.utils.xml_format \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBprettify\fP"
.br
.RI "\fIReturn a pretty-printed XML string for the given XML element\&. \fP"
.ti -1c
.RI "def \fBwrite_result\fP"
.br
.RI "\fIWrite an XML element into a pretty XML output file\&. \fP"
.ti -1c
.RI "def \fBparse_xml\fP"
.br
.RI "\fIParse an XML file\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "def lmf\&.src\&.utils\&.xml_format\&.parse_xml (filename)"

.PP
Parse an XML file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP The name of the XML file to parse with full path, for instance 'user/input\&.xml'\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The root XML element\&. 
.RE
.PP

.PP
Definition at line 31 of file xml_format\&.py\&.
.SS "def lmf\&.src\&.utils\&.xml_format\&.prettify (element)"

.PP
Return a pretty-printed XML string for the given XML element\&. 
.PP
\fBParameters:\fP
.RS 4
\fIelement\fP An XML element\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A Python string containing the printed version of the XML element\&. 
.RE
.PP

.PP
Definition at line 10 of file xml_format\&.py\&.
.SS "def lmf\&.src\&.utils\&.xml_format\&.write_result (element, filename, encoding = \fCNone\fP)"

.PP
Write an XML element into a pretty XML output file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIelement\fP An XML element\&. 
.br
\fIfilename\fP The name of the XML file to write with full path, for instance 'user/output\&.xml'\&. 
.br
\fIencoding\fP Encoding mode\&. Default value is None\&. 
.RE
.PP

.PP
Definition at line 20 of file xml_format\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
