.TH "lmf.src.output.doc" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.output.doc \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBdoc_write\fP"
.br
.RI "\fIWrite a document file\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "def lmf\&.src\&.output\&.doc\&.doc_write (object, filename, items = \fClambda lexical_entry: lexical_entry\&.get_lexeme()\fP, sort_order = \fCNone\fP, paradigms = \fCFalse\fP, reverse = \fCFalse\fP)"

.PP
Write a document file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIobject\fP The LMF instance to convert into document output format\&. 
.br
\fIfilename\fP The name of the document file to write with full path, for instance 'user/output\&.doc'\&. 
.br
\fIitems\fP Lambda function giving the item to sort\&. Default value is 'lambda lexical_entry: lexical_entry\&.get_lexeme()', which means that the items to sort are lexemes\&. 
.br
\fIsort_order\fP Python list\&. Default value is 'None', which means that the document output is alphabetically ordered\&. 
.RE
.PP

.PP
Definition at line 14 of file doc\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
