.TH "lmf.src.morphology.component.Component" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.morphology.component.Component \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "def \fBget_lexical_entry\fP"
.br
.RI "\fIGet pointed lexical entry\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBposition\fP"
.br
.ti -1c
.RI "\fBtargets\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file component\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.morphology\&.component\&.Component\&.__init__ (self)"

.PP
Constructor\&. \fBComponent\fP instances are owned by ListOfComponents\&. 
.PP
\fBReturns:\fP
.RS 4
A \fBComponent\fP instance\&. 
.RE
.PP

.PP
Definition at line 7 of file component\&.py\&.
.SS "def lmf\&.src\&.morphology\&.component\&.Component\&.__del__ (self)"

.PP
Destructor\&. 
.PP
Definition at line 19 of file component\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lmf\&.src\&.morphology\&.component\&.Component\&.get_lexical_entry (self)"

.PP
Get pointed lexical entry\&. 
.PP
\fBReturns:\fP
.RS 4
\fBComponent\fP private attribute '__lexical_entry'\&. 
.RE
.PP

.PP
Definition at line 25 of file component\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.morphology\&.component\&.Component\&.position"

.PP
Definition at line 12 of file component\&.py\&.
.SS "lmf\&.src\&.morphology\&.component\&.Component\&.targets"

.PP
Definition at line 14 of file component\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
