.TH "lmf.src.resources.human_resource.HumanResource" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.resources.human_resource.HumanResource \- 
.PP
\fBHumanResource\fP is a Resource subclass\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Resource\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIAs \fBHumanResource\fP is an abstract class, constructor raises an error\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIAs \fBHumanResource\fP is an abstract class, desctructor raises an error\&. \fP"
.ti -1c
.RI "def \fB__new__\fP"
.br
.RI "\fIPrivate initialization called from \fBHumanResource\fP subclasses\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBanonymizationFlag\fP"
.br
.ti -1c
.RI "\fBreference\fP"
.br
.ti -1c
.RI "\fBsource\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBHumanResource\fP is a Resource subclass\&. 

\fBHumanResource\fP is an abstract class representing a speaker\&. The \fBHumanResource\fP class allows subclasses\&. 
.PP
Definition at line 8 of file human_resource\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.resources\&.human_resource\&.HumanResource\&.__init__ (self)"

.PP
As \fBHumanResource\fP is an abstract class, constructor raises an error\&. 
.PP
Definition at line 11 of file human_resource\&.py\&.
.SS "def lmf\&.src\&.resources\&.human_resource\&.HumanResource\&.__del__ (self)"

.PP
As \fBHumanResource\fP is an abstract class, desctructor raises an error\&. 
.PP
Definition at line 16 of file human_resource\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lmf\&.src\&.resources\&.human_resource\&.HumanResource\&.__new__ (self)"

.PP
Private initialization called from \fBHumanResource\fP subclasses\&. \fBHumanResource\fP subinstances are owned by LexicalResource\&. 
.PP
Definition at line 21 of file human_resource\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.resources\&.human_resource\&.HumanResource\&.anonymizationFlag"

.PP
Definition at line 26 of file human_resource\&.py\&.
.SS "lmf\&.src\&.resources\&.human_resource\&.HumanResource\&.name"

.PP
Definition at line 25 of file human_resource\&.py\&.
.SS "lmf\&.src\&.resources\&.human_resource\&.HumanResource\&.reference"

.PP
Definition at line 27 of file human_resource\&.py\&.
.SS "lmf\&.src\&.resources\&.human_resource\&.HumanResource\&.source"

.PP
Definition at line 28 of file human_resource\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
