.TH "lmf.src.core.text_representation.TextRepresentation" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.core.text_representation.TextRepresentation \- 
.PP
'Text Representation is a class representing the textual content of definition or statement\&. When there is more than one variant orthography, the Text Representation instance contains a Unicode string representing the textual content as well as unique attribute-value pairs that describe the specific language, script and orthography\&.' (LMF)  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Representation\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIDestructor\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfont\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
'Text Representation is a class representing the textual content of definition or statement\&. When there is more than one variant orthography, the Text Representation instance contains a Unicode string representing the textual content as well as unique attribute-value pairs that describe the specific language, script and orthography\&.' (LMF) 
.PP
Definition at line 8 of file text_representation\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.core\&.text_representation\&.TextRepresentation\&.__init__ (self)"

.PP
Constructor\&. \fBTextRepresentation\fP instances are owned by Definition and Statement\&. 
.PP
\fBReturns:\fP
.RS 4
A \fBTextRepresentation\fP instance\&. 
.RE
.PP

.PP
Definition at line 11 of file text_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.text_representation\&.TextRepresentation\&.__del__ (self)"

.PP
Destructor\&. 
.PP
Definition at line 20 of file text_representation\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.core\&.text_representation\&.TextRepresentation\&.font"

.PP
Definition at line 18 of file text_representation\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
