.TH "lmf.src.input.xml_lmf" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.input.xml_lmf \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBcompute_name\fP"
.br
.RI "\fICompute attribute/module name from object name as follows: 'ObjectName' attribute/module name is 'object_name'\&. \fP"
.ti -1c
.RI "def \fBfactory\fP"
.br
.RI "\fIThis function is an object factory\&. \fP"
.ti -1c
.RI "def \fBxml_lmf_read\fP"
.br
.RI "\fIRead an XML LMF file\&. \fP"
.ti -1c
.RI "def \fBget_sub_elements\fP"
.br
.RI "\fIThis function recursively parses the given XML element and creates corresponding LMF instances with their attributes\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "def lmf\&.src\&.input\&.xml_lmf\&.compute_name (object_name)"

.PP
Compute attribute/module name from object name as follows: 'ObjectName' attribute/module name is 'object_name'\&. 
.PP
\fBParameters:\fP
.RS 4
\fIobject_name\fP String containing name of the object, e\&.g\&. 'LexicalEntry'\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The corresponding attribute/module name, e\&.g\&. 'lexical_entry'\&. 
.RE
.PP

.PP
Definition at line 6 of file xml_lmf\&.py\&.
.SS "def lmf\&.src\&.input\&.xml_lmf\&.factory (object_name, attributes)"

.PP
This function is an object factory\&. Indeed, from an object name and its attributes, it creates a Python object and sets its attributes\&. 
.PP
\fBParameters:\fP
.RS 4
\fIobject_name\fP A Python string containing the object name, for instance 'LexicalEntry'\&. 
.br
\fIattributes\fP A Python dictionary containing pairs of attribute name (as a Python string) and value, for instance {'partOfSpeech': 'n'}\&. 
.RE
.PP

.PP
Definition at line 21 of file xml_lmf\&.py\&.
.SS "def lmf\&.src\&.input\&.xml_lmf\&.get_sub_elements (instance, element)"

.PP
This function recursively parses the given XML element and creates corresponding LMF instances with their attributes\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinstance\fP An LMF object instance\&. 
.br
\fIelement\fP An XML element\&. 
.RE
.PP

.PP
Definition at line 69 of file xml_lmf\&.py\&.
.SS "def lmf\&.src\&.input\&.xml_lmf\&.xml_lmf_read (filename)"

.PP
Read an XML LMF file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP The name of the XML LMF file to read with full path, for instance 'user/input\&.xml'\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A Lexicon instance containing all lexical entries\&. 
.RE
.PP

.PP
Definition at line 57 of file xml_lmf\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
