.TH "lmf.src.morphology.stem" 3 "Thu Nov 27 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.morphology.stem \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStem\fP"
.br
.RI "\fI'Stem is a Form subclass representing a morph, thus manages the sublexme parts' (LMF) \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
