.TH "lmf.src.mrd.equivalent.Equivalent" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.mrd.equivalent.Equivalent \- 
.PP
'Equivalent is a class representing the translation equivalent of the word form managed by the Lemma class\&.' (LMF)  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIDestructor\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlanguage\fP"
.br
.ti -1c
.RI "\fBtranslation\fP"
.br
.ti -1c
.RI "\fBtext_representation\fP"
.br
.RI "\fITextRepresentation instances are owned by \fBEquivalent\fP There is zero to many TextRepresentation instances per \fBEquivalent\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
'Equivalent is a class representing the translation equivalent of the word form managed by the Lemma class\&.' (LMF) 
.PP
Definition at line 6 of file equivalent\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.mrd\&.equivalent\&.Equivalent\&.__init__ (self)"

.PP
Constructor\&. \fBEquivalent\fP instances are owned by Sense\&. 
.PP
\fBReturns:\fP
.RS 4
An \fBEquivalent\fP instance\&. 
.RE
.PP

.PP
Definition at line 9 of file equivalent\&.py\&.
.SS "def lmf\&.src\&.mrd\&.equivalent\&.Equivalent\&.__del__ (self)"

.PP
Destructor\&. Release TextRepresentation instances\&. 
.PP
Definition at line 20 of file equivalent\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.mrd\&.equivalent\&.Equivalent\&.language"

.PP
Definition at line 14 of file equivalent\&.py\&.
.SS "lmf\&.src\&.mrd\&.equivalent\&.Equivalent\&.text_representation"

.PP
TextRepresentation instances are owned by \fBEquivalent\fP There is zero to many TextRepresentation instances per \fBEquivalent\fP\&. 
.PP
Definition at line 18 of file equivalent\&.py\&.
.SS "lmf\&.src\&.mrd\&.equivalent\&.Equivalent\&.translation"

.PP
Definition at line 15 of file equivalent\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
