.TH "lmf.src.morphology.related_form.RelatedForm" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.morphology.related_form.RelatedForm \- 
.PP
'Related Form is a Form subclass representing a word form or a morph that can be related to the Lexical Entry\&. There is no asumption that the Related Form is associated with the Sense class in the Lexical Entry\&.' (LMF)  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "def \fBset_semanticRelation\fP"
.br
.RI "\fISet semantic relation\&. \fP"
.ti -1c
.RI "def \fBget_semanticRelation\fP"
.br
.RI "\fIGet semantic relation\&. \fP"
.ti -1c
.RI "def \fBget_lexeme\fP"
.br
.RI "\fIGet related LexicalEntry lexeme\&. \fP"
.ti -1c
.RI "def \fBset_lexical_entry\fP"
.br
.RI "\fISet pointer to the related lexical entry instance\&. \fP"
.ti -1c
.RI "def \fBget_lexical_entry\fP"
.br
.RI "\fIGet related LexicalEntry\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsemanticRelation\fP"
.br
.ti -1c
.RI "\fBtargets\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
'Related Form is a Form subclass representing a word form or a morph that can be related to the Lexical Entry\&. There is no asumption that the Related Form is associated with the Sense class in the Lexical Entry\&.' (LMF) 
.PP
Definition at line 10 of file related_form\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.morphology\&.related_form\&.RelatedForm\&.__init__ (self, lexeme = \fCNone\fP)"

.PP
Constructor\&. \fBRelatedForm\fP instances are owned by LexicalEntry\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexeme\fP Related lexeme\&. If not provided, default value is None\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A \fBRelatedForm\fP instance\&. 
.RE
.PP

.PP
Definition at line 13 of file related_form\&.py\&.
.SS "def lmf\&.src\&.morphology\&.related_form\&.RelatedForm\&.__del__ (self)"

.PP
Destructor\&. 
.PP
Definition at line 28 of file related_form\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lmf\&.src\&.morphology\&.related_form\&.RelatedForm\&.get_lexeme (self)"

.PP
Get related LexicalEntry lexeme\&. 
.PP
\fBReturns:\fP
.RS 4
\fBRelatedForm\fP attribute 'targets'\&. 
.RE
.PP

.PP
Definition at line 51 of file related_form\&.py\&.
.SS "def lmf\&.src\&.morphology\&.related_form\&.RelatedForm\&.get_lexical_entry (self)"

.PP
Get related LexicalEntry\&. 
.PP
\fBReturns:\fP
.RS 4
\fBRelatedForm\fP private attribute '__lexical_entry'\&. 
.RE
.PP

.PP
Definition at line 65 of file related_form\&.py\&.
.SS "def lmf\&.src\&.morphology\&.related_form\&.RelatedForm\&.get_semanticRelation (self)"

.PP
Get semantic relation\&. 
.PP
\fBReturns:\fP
.RS 4
\fBRelatedForm\fP attribute 'semanticRelation'\&. 
.RE
.PP

.PP
Definition at line 45 of file related_form\&.py\&.
.SS "def lmf\&.src\&.morphology\&.related_form\&.RelatedForm\&.set_lexical_entry (self, lexical_entry)"

.PP
Set pointer to the related lexical entry instance\&. This function can only be called once the full dictionary has been parsed\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The related LexicalEntry\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBRelatedForm\fP instance\&. 
.RE
.PP

.PP
Definition at line 57 of file related_form\&.py\&.
.SS "def lmf\&.src\&.morphology\&.related_form\&.RelatedForm\&.set_semanticRelation (self, semantic_relation)"

.PP
Set semantic relation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsemantic_relation\fP The semantic relation to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBRelatedForm\fP instance\&. 
.RE
.PP

.PP
Definition at line 34 of file related_form\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.morphology\&.related_form\&.RelatedForm\&.semanticRelation"

.PP
Definition at line 21 of file related_form\&.py\&.
.SS "lmf\&.src\&.morphology\&.related_form\&.RelatedForm\&.targets"

.PP
Definition at line 23 of file related_form\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
