.TH "lmf.src.core.global_information.GlobalInformation" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.core.global_information.GlobalInformation \- 
.PP
'Global Information is a class for administrative information and other general attributes, such as /language coding/ or /script coding/, which are valid for the entire lexical resource\&.' (LMF)  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "def \fBset_languageCode\fP"
.br
.RI "\fISet global information language code\&. \fP"
.ti -1c
.RI "def \fBget_languageCode\fP"
.br
.RI "\fIGet global information language code\&. \fP"
.ti -1c
.RI "def \fBset_version\fP"
.br
.RI "\fISet global information version\&. \fP"
.ti -1c
.RI "def \fBget_version\fP"
.br
.RI "\fIGet global information version\&. \fP"
.ti -1c
.RI "def \fBset_license\fP"
.br
.RI "\fISet global information license\&. \fP"
.ti -1c
.RI "def \fBget_license\fP"
.br
.RI "\fIGet global information license\&. \fP"
.ti -1c
.RI "def \fBset_characterEncoding\fP"
.br
.RI "\fISet global information character encoding\&. \fP"
.ti -1c
.RI "def \fBget_characterEncoding\fP"
.br
.RI "\fIGet global information character encoding\&. \fP"
.ti -1c
.RI "def \fBset_dateCoding\fP"
.br
.RI "\fISet global information date coding\&. \fP"
.ti -1c
.RI "def \fBget_dateCoding\fP"
.br
.RI "\fIGet global information date coding\&. \fP"
.ti -1c
.RI "def \fBset_projectName\fP"
.br
.RI "\fISet global information project name\&. \fP"
.ti -1c
.RI "def \fBget_projectName\fP"
.br
.RI "\fIGet global information project name\&. \fP"
.ti -1c
.RI "def \fBset_creationDate\fP"
.br
.RI "\fISet global information creation date\&. \fP"
.ti -1c
.RI "def \fBget_creationDate\fP"
.br
.RI "\fIGet global information creation date\&. \fP"
.ti -1c
.RI "def \fBset_lastUpdate\fP"
.br
.RI "\fISet global information last update\&. \fP"
.ti -1c
.RI "def \fBget_lastUpdate\fP"
.br
.RI "\fIGet global information last update\&. \fP"
.ti -1c
.RI "def \fBset_author\fP"
.br
.RI "\fISet global information author\&. \fP"
.ti -1c
.RI "def \fBget_author\fP"
.br
.RI "\fIGet global information author\&. \fP"
.ti -1c
.RI "def \fBset_description\fP"
.br
.RI "\fISet global information description\&. \fP"
.ti -1c
.RI "def \fBget_description\fP"
.br
.RI "\fIGet global information description\&. \fP"
.ti -1c
.RI "def \fBcompute_bibliographicCitation\fP"
.br
.RI "\fICompute bibliographic citation from date and author\&. \fP"
.ti -1c
.RI "def \fBget_bibliographicCitation\fP"
.br
.RI "\fIGet global information bibliographic citation\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlanguageCode\fP"
.br
.ti -1c
.RI "\fBauthor\fP"
.br
.ti -1c
.RI "\fBversion\fP"
.br
.ti -1c
.RI "\fBlastUpdate\fP"
.br
.ti -1c
.RI "\fBlicense\fP"
.br
.ti -1c
.RI "\fBcharacterEncoding\fP"
.br
.ti -1c
.RI "\fBdateCoding\fP"
.br
.ti -1c
.RI "\fBcreationDate\fP"
.br
.ti -1c
.RI "\fBprojectName\fP"
.br
.ti -1c
.RI "\fBdescription\fP"
.br
.ti -1c
.RI "\fBbibliographicCitation\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
'Global Information is a class for administrative information and other general attributes, such as /language coding/ or /script coding/, which are valid for the entire lexical resource\&.' (LMF) 
.PP
Definition at line 8 of file global_information\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.__init__ (self)"

.PP
Constructor\&. \fBGlobalInformation\fP instance is owned by LexicalResource\&. 
.PP
\fBReturns:\fP
.RS 4
A \fBGlobalInformation\fP instance\&. 
.RE
.PP

.PP
Definition at line 11 of file global_information\&.py\&.
.SS "def lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.__del__ (self)"

.PP
Destructor\&. 
.PP
Definition at line 28 of file global_information\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.compute_bibliographicCitation (self)"

.PP
Compute bibliographic citation from date and author\&. Set \fBGlobalInformation\fP attribute 'bibliographicCitation'\&. 
.PP
Definition at line 175 of file global_information\&.py\&.
.SS "def lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.get_author (self)"

.PP
Get global information author\&. 
.PP
\fBReturns:\fP
.RS 4
\fBGlobalInformation\fP attribute 'author'\&. 
.RE
.PP

.PP
Definition at line 155 of file global_information\&.py\&.
.SS "def lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.get_bibliographicCitation (self)"

.PP
Get global information bibliographic citation\&. 
.PP
\fBReturns:\fP
.RS 4
\fBGlobalInformation\fP attribute 'bibliographicCitation'\&. 
.RE
.PP

.PP
Definition at line 185 of file global_information\&.py\&.
.SS "def lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.get_characterEncoding (self)"

.PP
Get global information character encoding\&. 
.PP
\fBReturns:\fP
.RS 4
\fBGlobalInformation\fP attribute 'characterEncoding'\&. 
.RE
.PP

.PP
Definition at line 83 of file global_information\&.py\&.
.SS "def lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.get_creationDate (self)"

.PP
Get global information creation date\&. 
.PP
\fBReturns:\fP
.RS 4
\fBGlobalInformation\fP attribute 'creationDate'\&. 
.RE
.PP

.PP
Definition at line 126 of file global_information\&.py\&.
.SS "def lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.get_dateCoding (self)"

.PP
Get global information date coding\&. 
.PP
\fBReturns:\fP
.RS 4
\fBGlobalInformation\fP attribute 'dateCoding'\&. 
.RE
.PP

.PP
Definition at line 97 of file global_information\&.py\&.
.SS "def lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.get_description (self)"

.PP
Get global information description\&. 
.PP
\fBReturns:\fP
.RS 4
\fBGlobalInformation\fP attribute 'description'\&. 
.RE
.PP

.PP
Definition at line 169 of file global_information\&.py\&.
.SS "def lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.get_languageCode (self)"

.PP
Get global information language code\&. 
.PP
\fBReturns:\fP
.RS 4
\fBGlobalInformation\fP attribute 'languageCode'\&. 
.RE
.PP

.PP
Definition at line 41 of file global_information\&.py\&.
.SS "def lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.get_lastUpdate (self)"

.PP
Get global information last update\&. 
.PP
\fBReturns:\fP
.RS 4
\fBGlobalInformation\fP attribute 'lastUpdate'\&. 
.RE
.PP

.PP
Definition at line 141 of file global_information\&.py\&.
.SS "def lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.get_license (self)"

.PP
Get global information license\&. 
.PP
\fBReturns:\fP
.RS 4
\fBGlobalInformation\fP attribute 'license'\&. 
.RE
.PP

.PP
Definition at line 69 of file global_information\&.py\&.
.SS "def lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.get_projectName (self)"

.PP
Get global information project name\&. 
.PP
\fBReturns:\fP
.RS 4
\fBGlobalInformation\fP attribute 'projectName'\&. 
.RE
.PP

.PP
Definition at line 111 of file global_information\&.py\&.
.SS "def lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.get_version (self)"

.PP
Get global information version\&. 
.PP
\fBReturns:\fP
.RS 4
\fBGlobalInformation\fP attribute 'version'\&. 
.RE
.PP

.PP
Definition at line 55 of file global_information\&.py\&.
.SS "def lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.set_author (self, author)"

.PP
Set global information author\&. 
.PP
\fBParameters:\fP
.RS 4
\fIauthor\fP The author's name to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBGlobalInformation\fP instance\&. 
.RE
.PP

.PP
Definition at line 147 of file global_information\&.py\&.
.SS "def lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.set_characterEncoding (self, character_encoding)"

.PP
Set global information character encoding\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcharacter_encoding\fP The character encoding to use\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBGlobalInformation\fP instance\&. 
.RE
.PP

.PP
Definition at line 75 of file global_information\&.py\&.
.SS "def lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.set_creationDate (self, date)"

.PP
Set global information creation date\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdate\fP The date to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBGlobalInformation\fP instance\&. 
.RE
.PP

.PP
Definition at line 117 of file global_information\&.py\&.
.SS "def lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.set_dateCoding (self, date_coding)"

.PP
Set global information date coding\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdate_coding\fP The date coding to use\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBGlobalInformation\fP instance\&. 
.RE
.PP

.PP
Definition at line 89 of file global_information\&.py\&.
.SS "def lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.set_description (self, description)"

.PP
Set global information description\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdescription\fP The description to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBGlobalInformation\fP instance\&. 
.RE
.PP

.PP
Definition at line 161 of file global_information\&.py\&.
.SS "def lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.set_languageCode (self, language_code)"

.PP
Set global information language code\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlanguage_code\fP The language code to use\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBGlobalInformation\fP instance\&. 
.RE
.PP

.PP
Definition at line 33 of file global_information\&.py\&.
.SS "def lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.set_lastUpdate (self, date)"

.PP
Set global information last update\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdate\fP The date to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBGlobalInformation\fP instance\&. 
.RE
.PP

.PP
Definition at line 132 of file global_information\&.py\&.
.SS "def lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.set_license (self, license)"

.PP
Set global information license\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlicense\fP The license to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBGlobalInformation\fP instance\&. 
.RE
.PP

.PP
Definition at line 61 of file global_information\&.py\&.
.SS "def lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.set_projectName (self, project_name)"

.PP
Set global information project name\&. 
.PP
\fBParameters:\fP
.RS 4
\fIproject_name\fP The project name to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBGlobalInformation\fP instance\&. 
.RE
.PP

.PP
Definition at line 103 of file global_information\&.py\&.
.SS "def lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.set_version (self, version)"

.PP
Set global information version\&. 
.PP
\fBParameters:\fP
.RS 4
\fIversion\fP The version to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBGlobalInformation\fP version\&. 
.RE
.PP

.PP
Definition at line 47 of file global_information\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.author"

.PP
Definition at line 17 of file global_information\&.py\&.
.SS "lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.bibliographicCitation"

.PP
Definition at line 26 of file global_information\&.py\&.
.SS "lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.characterEncoding"

.PP
Definition at line 21 of file global_information\&.py\&.
.SS "lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.creationDate"

.PP
Definition at line 23 of file global_information\&.py\&.
.SS "lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.dateCoding"

.PP
Definition at line 22 of file global_information\&.py\&.
.SS "lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.description"

.PP
Definition at line 25 of file global_information\&.py\&.
.SS "lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.languageCode"

.PP
Definition at line 16 of file global_information\&.py\&.
.SS "lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.lastUpdate"

.PP
Definition at line 19 of file global_information\&.py\&.
.SS "lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.license"

.PP
Definition at line 20 of file global_information\&.py\&.
.SS "lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.projectName"

.PP
Definition at line 24 of file global_information\&.py\&.
.SS "lmf\&.src\&.core\&.global_information\&.GlobalInformation\&.version"

.PP
Definition at line 18 of file global_information\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
