.TH "lmf.src.core" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.core \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdefinition\fP"
.br
.ti -1c
.RI " \fBform\fP"
.br
.ti -1c
.RI " \fBform_representation\fP"
.br
.ti -1c
.RI " \fBglobal_information\fP"
.br
.ti -1c
.RI " \fBlexical_entry\fP"
.br
.ti -1c
.RI " \fBlexical_resource\fP"
.br
.ti -1c
.RI " \fBlexicon\fP"
.br
.ti -1c
.RI " \fBrepresentation\fP"
.br
.ti -1c
.RI " \fBsense\fP"
.br
.ti -1c
.RI " \fBstatement\fP"
.br
.ti -1c
.RI " \fBtext_representation\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
