.TH "lmf.src.config.tex" 3 "Thu Nov 27 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.config.tex \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBlmf_to_tex\fP"
.br
.RI "\fIFunction giving order in which information must be written in LaTeX and mapping between LMF representation and LaTeX (output) \fP"
.ti -1c
.RI "def \fBformat_lexeme\fP"
.br
.RI "\fIFunctions to process LaTeX fields (output) \fP"
.ti -1c
.RI "def \fBformat_part_of_speech\fP"
.br
.RI "\fIDisplay part of speech in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_definitions\fP"
.br
.RI "\fIGlosses are supplanted by definitions\&. \fP"
.ti -1c
.RI "def \fBformat_lt\fP"
.br
.RI "\fIDisplay 'lt' in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_sc\fP"
.br
.RI "\fIDisplay 'sc' in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_rf\fP"
.br
.RI "\fIDisplay 'rf' in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_examples\fP"
.br
.RI "\fIDisplay examples in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_usage_notes\fP"
.br
.RI "\fIDisplay usage notes in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_encyclopedic_informations\fP"
.br
.RI "\fIDisplay encyclopedic informations in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_restrictions\fP"
.br
.RI "\fIDisplay restrictions in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_lexical_functions\fP"
.br
.RI "\fIDisplay lexical functions in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_related_forms\fP"
.br
.RI "\fIDisplay related forms in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_variant_forms\fP"
.br
.RI "\fIDisplay variant forms in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_borrowed_word\fP"
.br
.RI "\fIDisplay borrowed word in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_etymology\fP"
.br
.RI "\fIDisplay etymology in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_paradigms\fP"
.br
.RI "\fIDisplay all paradigms in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_table\fP"
.br
.RI "\fIDisplay a table in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_semantic_domains\fP"
.br
.RI "\fIDisplay semantic domains in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_bibliography\fP"
.br
.RI "\fIDisplay bibliography in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_picture\fP"
.br
.RI "\fIDisplay a picture in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_notes\fP"
.br
.RI "\fIDisplay all notes in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_source\fP"
.br
.RI "\fIDisplay source in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_status\fP"
.br
.RI "\fIDisplay status in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_date\fP"
.br
.RI "\fIDo not display date in LaTeX format\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBtex_font\fP"
.br
.RI "\fIFonts to use in LaTeX format (output) \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "def lmf\&.src\&.config\&.tex\&.format_bibliography (lexical_entry, font)"

.PP
Display bibliography in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing bibliography in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 389 of file tex\&.py\&.
.SS "def lmf\&.src\&.config\&.tex\&.format_borrowed_word (lexical_entry, font)"

.PP
Display borrowed word in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing borrowed word in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 295 of file tex\&.py\&.
.SS "def lmf\&.src\&.config\&.tex\&.format_date (lexical_entry, font)"

.PP
Do not display date in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
An empty string\&. 
.RE
.PP

.PP
Definition at line 452 of file tex\&.py\&.
.SS "def lmf\&.src\&.config\&.tex\&.format_definitions (lexical_entry, font)"

.PP
Glosses are supplanted by definitions\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing glosses and definitions in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 104 of file tex\&.py\&.
.SS "def lmf\&.src\&.config\&.tex\&.format_encyclopedic_informations (lexical_entry, font)"

.PP
Display encyclopedic informations in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing encyclopedic informations in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 207 of file tex\&.py\&.
.SS "def lmf\&.src\&.config\&.tex\&.format_etymology (lexical_entry, font)"

.PP
Display etymology in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing etymology in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 309 of file tex\&.py\&.
.SS "def lmf\&.src\&.config\&.tex\&.format_examples (lexical_entry, font)"

.PP
Display examples in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing examples in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 170 of file tex\&.py\&.
.SS "def lmf\&.src\&.config\&.tex\&.format_lexeme (lexical_entry, font)"

.PP
Functions to process LaTeX fields (output) 'lx', 'hm' and 'lc' fields are flipped if 'lc' field has data\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing lexeme in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 71 of file tex\&.py\&.
.SS "def lmf\&.src\&.config\&.tex\&.format_lexical_functions (lexical_entry, font)"

.PP
Display lexical functions in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing lexical functions in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 243 of file tex\&.py\&.
.SS "def lmf\&.src\&.config\&.tex\&.format_lt (lexical_entry, font)"

.PP
Display 'lt' in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing 'lt' in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 143 of file tex\&.py\&.
.SS "def lmf\&.src\&.config\&.tex\&.format_notes (lexical_entry, font)"

.PP
Display all notes in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing all notes in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 409 of file tex\&.py\&.
.SS "def lmf\&.src\&.config\&.tex\&.format_paradigms (lexical_entry, font)"

.PP
Display all paradigms in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing all paradigms in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 322 of file tex\&.py\&.
.SS "def lmf\&.src\&.config\&.tex\&.format_part_of_speech (lexical_entry, font)"

.PP
Display part of speech in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing part of speech in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 93 of file tex\&.py\&.
.SS "def lmf\&.src\&.config\&.tex\&.format_picture (lexical_entry, font)"

.PP
Display a picture in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing a picture in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 400 of file tex\&.py\&.
.SS "def lmf\&.src\&.config\&.tex\&.format_related_forms (lexical_entry, font)"

.PP
Display related forms in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing related forms in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 256 of file tex\&.py\&.
.SS "def lmf\&.src\&.config\&.tex\&.format_restrictions (lexical_entry, font)"

.PP
Display restrictions in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing restrictions in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 225 of file tex\&.py\&.
.SS "def lmf\&.src\&.config\&.tex\&.format_rf (lexical_entry, font)"

.PP
Display 'rf' in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing 'rf' in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 161 of file tex\&.py\&.
.SS "def lmf\&.src\&.config\&.tex\&.format_sc (lexical_entry, font)"

.PP
Display 'sc' in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing 'sc' in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 152 of file tex\&.py\&.
.SS "def lmf\&.src\&.config\&.tex\&.format_semantic_domains (lexical_entry, font)"

.PP
Display semantic domains in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing semantic domains in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 374 of file tex\&.py\&.
.SS "def lmf\&.src\&.config\&.tex\&.format_source (lexical_entry, font)"

.PP
Display source in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing source in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 432 of file tex\&.py\&.
.SS "def lmf\&.src\&.config\&.tex\&.format_status (lexical_entry, font)"

.PP
Display status in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing status in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 441 of file tex\&.py\&.
.SS "def lmf\&.src\&.config\&.tex\&.format_table (lexical_entry, font)"

.PP
Display a table in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing a table in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 366 of file tex\&.py\&.
.SS "def lmf\&.src\&.config\&.tex\&.format_usage_notes (lexical_entry, font)"

.PP
Display usage notes in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing usage notes in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 189 of file tex\&.py\&.
.SS "def lmf\&.src\&.config\&.tex\&.format_variant_forms (lexical_entry, font)"

.PP
Display variant forms in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing variant forms in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 277 of file tex\&.py\&.
.SS "def lmf\&.src\&.config\&.tex\&.lmf_to_tex (lexical_entry, font = \fCtex_font\fP)"

.PP
Function giving order in which information must be written in LaTeX and mapping between LMF representation and LaTeX (output) Function to convert LMF lexical entry information to be written into LaTeX commands\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The Lexical Entry LMF instance to display\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing the lexical entry in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 15 of file tex\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "tuple lmf\&.src\&.config\&.tex\&.tex_font"
\fBInitial value:\fP
.PP
.nf
1 = dict({
2     VERNACULAR  : lambda text: "\\textbf{\ipa{" + text + "}}",
3     ENGLISH     : lambda text: text,
4     NATIONAL    : lambda text: "\\textit{\zh{" + text + "}}",
5     REGIONAL    : lambda text: "\ipa{" + text + "}"
6 })
.fi
.PP
Fonts to use in LaTeX format (output) 
.PP
Definition at line 7 of file tex\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
