.TH "lmf.src.core.sense" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.core.sense \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSense\fP"
.br
.RI "\fI'Sense is a class representing one meaning of a lexical entry\&. The Sense class allows for hierarchical senses in that a sense may be more specific than another sense of the same lexical entry\&.' (LMF) \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
