.TH "lmf.src.morphology.related_form" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.morphology.related_form \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRelatedForm\fP"
.br
.RI "\fI'Related Form is a Form subclass representing a word form or a morph that can be related to the Lexical Entry\&. There is no asumption that the Related Form is associated with the Sense class in the Lexical Entry\&.' (LMF) \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
