.TH "lmf.src.output.odt" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.output.odt \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBtextdoc\fP = OpenDocumentText()"
.br
.ti -1c
.RI "\fBs\fP = textdoc\&.styles"
.br
.ti -1c
.RI "tuple \fBh1style\fP = Style(name='Heading 1', family='paragraph')"
.br
.ti -1c
.RI "tuple \fBboldstyle\fP = Style(name='Bold', family='text')"
.br
.ti -1c
.RI "tuple \fBboldprop\fP = TextProperties(fontweight='bold', fontname='Arial', fontsize='8pt')"
.br
.ti -1c
.RI "tuple \fBh\fP = H(outlinelevel=1, stylename=\fBh1style\fP, text='My first text')"
.br
.ti -1c
.RI "tuple \fBp\fP = P(text='Hello world\&. ')"
.br
.ti -1c
.RI "tuple \fBboldpart\fP = Span(stylename=\fBboldstyle\fP, text='This part is bold\&. ')"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple lmf\&.src\&.output\&.odt\&.boldpart = Span(stylename=\fBboldstyle\fP, text='This part is bold\&. ')"

.PP
Definition at line 22 of file odt\&.py\&.
.SS "tuple lmf\&.src\&.output\&.odt\&.boldprop = TextProperties(fontweight='bold', fontname='Arial', fontsize='8pt')"

.PP
Definition at line 15 of file odt\&.py\&.
.SS "tuple lmf\&.src\&.output\&.odt\&.boldstyle = Style(name='Bold', family='text')"

.PP
Definition at line 14 of file odt\&.py\&.
.SS "tuple lmf\&.src\&.output\&.odt\&.h = H(outlinelevel=1, stylename=\fBh1style\fP, text='My first text')"

.PP
Definition at line 19 of file odt\&.py\&.
.SS "tuple lmf\&.src\&.output\&.odt\&.h1style = Style(name='Heading 1', family='paragraph')"

.PP
Definition at line 10 of file odt\&.py\&.
.SS "tuple lmf\&.src\&.output\&.odt\&.p = P(text='Hello world\&. ')"

.PP
Definition at line 21 of file odt\&.py\&.
.SS "lmf\&.src\&.output\&.odt\&.s = textdoc\&.styles"

.PP
Definition at line 9 of file odt\&.py\&.
.SS "tuple lmf\&.src\&.output\&.odt\&.textdoc = OpenDocumentText()"

.PP
Definition at line 7 of file odt\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
