.TH "lmf.src.core.lexical_entry.LexicalEntry" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.core.lexical_entry.LexicalEntry \- 
.PP
'Lexical Entry is a class representing a lexeme in a given language and is a container for managing the Form and Sense classes\&. A Lexical Entry instance can contain one to many different forms and can have from zero to many different senses\&.' (LMF)  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "def \fBset_partOfSpeech\fP"
.br
.RI "\fISet grammatical category\&. \fP"
.ti -1c
.RI "def \fBget_partOfSpeech\fP"
.br
.RI "\fIGet grammatical category\&. \fP"
.ti -1c
.RI "def \fBset_status\fP"
.br
.RI "\fISet lexical entry status\&. \fP"
.ti -1c
.RI "def \fBget_status\fP"
.br
.RI "\fIGet lexical entry status\&. \fP"
.ti -1c
.RI "def \fBget_id\fP"
.br
.RI "\fIGet Unique IDentifier\&. \fP"
.ti -1c
.RI "def \fBset_lexeme\fP"
.br
.RI "\fISet lexeme\&. \fP"
.ti -1c
.RI "def \fBget_lexeme\fP"
.br
.RI "\fIGet lexeme\&. \fP"
.ti -1c
.RI "def \fBcreate_related_form\fP"
.br
.RI "\fICreate a related form\&. \fP"
.ti -1c
.RI "def \fBadd_related_form\fP"
.br
.RI "\fIAdd a related form to the lexical entry\&. \fP"
.ti -1c
.RI "def \fBcreate_and_add_related_form\fP"
.br
.RI "\fICreate and add a related form to the lexical entry\&. \fP"
.ti -1c
.RI "def \fBfind_related_forms\fP"
.br
.RI "\fIFind related lexemes\&. \fP"
.ti -1c
.RI "def \fBget_related_forms\fP"
.br
.RI "\fIGet all related forms maintained by the lexical entry\&. \fP"
.ti -1c
.RI "def \fBget_speaker\fP"
.br
.RI "\fIGet speaker\&. \fP"
.ti -1c
.RI "def \fBget_definitions\fP"
.br
.ti -1c
.RI "def \fBget_senses\fP"
.br
.ti -1c
.RI "def \fBget_gloss\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhomonymNumber\fP"
.br
.ti -1c
.RI "\fBstatus\fP"
.br
.ti -1c
.RI "\fBdate\fP"
.br
.ti -1c
.RI "\fBpartOfSpeech\fP"
.br
.ti -1c
.RI "\fBindependentWord\fP"
.br
.ti -1c
.RI "\fBbibliography\fP"
.br
.ti -1c
.RI "\fBid\fP"
.br
.RI "\fIUID is managed at the Lexicon level\&. \fP"
.ti -1c
.RI "\fBsense\fP"
.br
.RI "\fISense instances are owned by \fBLexicalEntry\fP There is zero to many Sense instances per \fBLexicalEntry\fP\&. \fP"
.ti -1c
.RI "\fBlemma\fP"
.br
.RI "\fILemma instance is owned by \fBLexicalEntry\fP There is one Lemma instance by \fBLexicalEntry\fP instance\&. \fP"
.ti -1c
.RI "\fBrelated_form\fP"
.br
.RI "\fIRelatedForm instances are owned by \fBLexicalEntry\fP There is zero to many RelatedForm instances per \fBLexicalEntry\fP\&. \fP"
.ti -1c
.RI "\fBword_form\fP"
.br
.RI "\fIWordForm instances are owned by \fBLexicalEntry\fP There is zero to many WordForm instances per \fBLexicalEntry\fP\&. \fP"
.ti -1c
.RI "\fBstem\fP"
.br
.RI "\fIStem instances are owned by \fBLexicalEntry\fP There is zero to many Stem instances per \fBLexicalEntry\fP\&. \fP"
.ti -1c
.RI "\fBlist_of_components\fP"
.br
.RI "\fIListOfComponents instance is owned by \fBLexicalEntry\fP There is zero or one ListOfComponents instance per \fBLexicalEntry\fP\&. \fP"
.ti -1c
.RI "\fBtargets\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
'Lexical Entry is a class representing a lexeme in a given language and is a container for managing the Form and Sense classes\&. A Lexical Entry instance can contain one to many different forms and can have from zero to many different senses\&.' (LMF) 
.PP
Definition at line 9 of file lexical_entry\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.__init__ (self, id = \fC0\fP)"

.PP
Constructor\&. \fBLexicalEntry\fP instances are owned by Lexicon\&. 
.PP
\fBParameters:\fP
.RS 4
\fIid\fP Unique IDentifier\&. If not provided, default value is 0\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A \fBLexicalEntry\fP instance\&. 
.RE
.PP

.PP
Definition at line 12 of file lexical_entry\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.__del__ (self)"

.PP
Destructor\&. Release Sense, Lemma, RelatedForm, WordForm, Stem, ListOfComponents instances\&. 
.PP
Definition at line 50 of file lexical_entry\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.add_related_form (self, related_form)"

.PP
Add a related form to the lexical entry\&. 
.PP
\fBParameters:\fP
.RS 4
\fIrelated_form\fP The RelatedForm instance to add to the lexical entry\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLexicalEntry\fP instance\&. 
.RE
.PP

.PP
Definition at line 136 of file lexical_entry\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.create_and_add_related_form (self, lexeme, semantic_relation)"

.PP
Create and add a related form to the lexical entry\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexeme\fP Related lexeme\&. 
.br
\fIsemantic_relation\fP The semantic relation existing between this lexical entry and the related lexeme to create\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLexicalEntry\fP instance\&. 
.RE
.PP

.PP
Definition at line 144 of file lexical_entry\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.create_related_form (self, lexeme, semantic_relation)"

.PP
Create a related form\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexeme\fP Related lexeme\&. 
.br
\fIsemantic_relation\fP The semantic relation existing between this lexical entry and the related lexeme to create\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
RelatedForm instance\&. 
.RE
.PP

.PP
Definition at line 128 of file lexical_entry\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.find_related_forms (self, semantic_relation)"

.PP
Find related lexemes\&. This attribute is owned by RelatedForm\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsemantic_relation\fP The semantic relation to consider to retrieve the related form\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A Python list of found RelatedForm attributes 'targets'\&. 
.RE
.PP

.PP
Definition at line 153 of file lexical_entry\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.get_definitions (self)"

.PP
Definition at line 178 of file lexical_entry\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.get_gloss (self, lang)"

.PP
Definition at line 184 of file lexical_entry\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.get_id (self)"

.PP
Get Unique IDentifier\&. 
.PP
\fBReturns:\fP
.RS 4
\fBLexicalEntry\fP attribute 'id'\&. 
.RE
.PP

.PP
Definition at line 101 of file lexical_entry\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.get_lexeme (self)"

.PP
Get lexeme\&. Attribute 'lexeme' is owned by Lemma\&. 
.PP
\fBReturns:\fP
.RS 4
Lemma attribute 'lexeme' if any\&. 
.RE
.PP

.PP
Definition at line 118 of file lexical_entry\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.get_partOfSpeech (self)"

.PP
Get grammatical category\&. 
.PP
\fBReturns:\fP
.RS 4
\fBLexicalEntry\fP attribute 'partOfSpeech'\&. 
.RE
.PP

.PP
Definition at line 81 of file lexical_entry\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.get_related_forms (self)"

.PP
Get all related forms maintained by the lexical entry\&. 
.PP
\fBReturns:\fP
.RS 4
A Python set of related forms\&. 
.RE
.PP

.PP
Definition at line 165 of file lexical_entry\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.get_senses (self)"

.PP
Definition at line 181 of file lexical_entry\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.get_speaker (self)"

.PP
Get speaker\&. 
.PP
\fBReturns:\fP
.RS 4
\fBLexicalEntry\fP private attribute '__speaker'\&. 
.RE
.PP

.PP
Definition at line 172 of file lexical_entry\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.get_status (self)"

.PP
Get lexical entry status\&. 
.PP
\fBReturns:\fP
.RS 4
\fBLexicalEntry\fP attribute 'status'\&. 
.RE
.PP

.PP
Definition at line 95 of file lexical_entry\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.set_lexeme (self, lexeme)"

.PP
Set lexeme\&. Attribute 'lexeme' is owned by Lemma\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexeme\fP The lexeme to set\&. 
.RE
.PP

.PP
Definition at line 107 of file lexical_entry\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.set_partOfSpeech (self, part_of_speech)"

.PP
Set grammatical category\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpart_of_speech\fP The grammatical category to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLexicalEntry\fP instance\&. 
.RE
.PP

.PP
Definition at line 73 of file lexical_entry\&.py\&.
.SS "def lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.set_status (self, status)"

.PP
Set lexical entry status\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstatus\fP The status to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLexicalEntry\fP instance\&. 
.RE
.PP

.PP
Definition at line 87 of file lexical_entry\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.bibliography"

.PP
Definition at line 23 of file lexical_entry\&.py\&.
.SS "lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.date"

.PP
Definition at line 20 of file lexical_entry\&.py\&.
.SS "lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.homonymNumber"

.PP
Definition at line 18 of file lexical_entry\&.py\&.
.SS "lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.id"

.PP
UID is managed at the Lexicon level\&. 
.PP
Definition at line 25 of file lexical_entry\&.py\&.
.SS "lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.independentWord"

.PP
Definition at line 22 of file lexical_entry\&.py\&.
.SS "lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.lemma"

.PP
Lemma instance is owned by \fBLexicalEntry\fP There is one Lemma instance by \fBLexicalEntry\fP instance\&. 
.PP
Definition at line 31 of file lexical_entry\&.py\&.
.SS "lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.list_of_components"

.PP
ListOfComponents instance is owned by \fBLexicalEntry\fP There is zero or one ListOfComponents instance per \fBLexicalEntry\fP\&. 
.PP
Definition at line 43 of file lexical_entry\&.py\&.
.SS "lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.partOfSpeech"

.PP
Definition at line 21 of file lexical_entry\&.py\&.
.SS "lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.related_form"

.PP
RelatedForm instances are owned by \fBLexicalEntry\fP There is zero to many RelatedForm instances per \fBLexicalEntry\fP\&. 
.PP
Definition at line 34 of file lexical_entry\&.py\&.
.SS "lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.sense"

.PP
Sense instances are owned by \fBLexicalEntry\fP There is zero to many Sense instances per \fBLexicalEntry\fP\&. 
.PP
Definition at line 28 of file lexical_entry\&.py\&.
.SS "lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.status"

.PP
Definition at line 19 of file lexical_entry\&.py\&.
.SS "lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.stem"

.PP
Stem instances are owned by \fBLexicalEntry\fP There is zero to many Stem instances per \fBLexicalEntry\fP\&. 
.PP
Definition at line 40 of file lexical_entry\&.py\&.
.SS "lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.targets"

.PP
Definition at line 45 of file lexical_entry\&.py\&.
.SS "lmf\&.src\&.core\&.lexical_entry\&.LexicalEntry\&.word_form"

.PP
WordForm instances are owned by \fBLexicalEntry\fP There is zero to many WordForm instances per \fBLexicalEntry\fP\&. 
.PP
Definition at line 37 of file lexical_entry\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
