.TH "lmf.src.core.representation.Representation" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.core.representation.Representation \- 
.PP
'Representation class is an abstract class representing a Unicode string as well as, if needed, the unique attribute-value pairs that describe the specific language, script and orthography\&.' (LMF)  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIAs \fBRepresentation\fP is an abstract class, constructor raises an error\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIAs \fBRepresentation\fP is an abstract class, desctructor raises an error\&. \fP"
.ti -1c
.RI "def \fB__new__\fP"
.br
.RI "\fIPrivate initialization called from \fBRepresentation\fP subclasses\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcomment\fP"
.br
.ti -1c
.RI "\fBwrittenForm\fP"
.br
.ti -1c
.RI "\fBlanguage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
'Representation class is an abstract class representing a Unicode string as well as, if needed, the unique attribute-value pairs that describe the specific language, script and orthography\&.' (LMF) 
.PP
Definition at line 6 of file representation\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.core\&.representation\&.Representation\&.__init__ (self)"

.PP
As \fBRepresentation\fP is an abstract class, constructor raises an error\&. 
.PP
Definition at line 9 of file representation\&.py\&.
.SS "def lmf\&.src\&.core\&.representation\&.Representation\&.__del__ (self)"

.PP
As \fBRepresentation\fP is an abstract class, desctructor raises an error\&. 
.PP
Definition at line 14 of file representation\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lmf\&.src\&.core\&.representation\&.Representation\&.__new__ (self)"

.PP
Private initialization called from \fBRepresentation\fP subclasses\&. 
.PP
Definition at line 19 of file representation\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.core\&.representation\&.Representation\&.comment"

.PP
Definition at line 22 of file representation\&.py\&.
.SS "lmf\&.src\&.core\&.representation\&.Representation\&.language"

.PP
Definition at line 24 of file representation\&.py\&.
.SS "lmf\&.src\&.core\&.representation\&.Representation\&.writtenForm"

.PP
Definition at line 23 of file representation\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
