.TH "lmf.src.config.mdf" 3 "Thu Nov 27 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.config.mdf \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBset_bw\fP"
.br
.RI "\fIFunctions to process some MDF fields (input) \fP"
.ti -1c
.RI "def \fBget_bw\fP"
.br
.RI "\fIFunctions to process some MDF fields (output) \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBVERNACULAR\fP = 'ver'"
.br
.RI "\fIDefine languages\&. \fP"
.ti -1c
.RI "string \fBENGLISH\fP = 'eng'"
.br
.ti -1c
.RI "string \fBNATIONAL\fP = 'nat'"
.br
.ti -1c
.RI "string \fBREGIONAL\fP = 'reg'"
.br
.ti -1c
.RI "tuple \fBmdf_lmf\fP"
.br
.RI "\fIMapping between MDF markers and LMF representation (input) \fP"
.ti -1c
.RI "list \fBmdf_order\fP"
.br
.RI "\fIOrder in which MDF markers must be written (output) This is the standard order defined in Appendix B of 'Making Dictionaries\&. A guide to lexicography and the Multi-Dictionary Formatter', Software version 1\&.0, David F\&. \fP"
.ti -1c
.RI "tuple \fBlmf_mdf\fP"
.br
.RI "\fIMapping between LMF representation and MDF markers (output) \fP"
.ti -1c
.RI "tuple \fBps_partOfSpeech\fP"
.br
.RI "\fIMapping between 'ps' MDF marker value and LMF part of speech LexicalEntry attribute value (input) \fP"
.ti -1c
.RI "tuple \fBmdf_semanticRelation\fP"
.br
.RI "\fIMapping between MDF markers and LMF semantic relation RelatedForm attribute value (input) \fP"
.ti -1c
.RI "tuple \fBpd_person\fP"
.br
.RI "\fIMapping between 'pd' MDF markers and LMF person WordForm attribute value (input) \fP"
.ti -1c
.RI "tuple \fBpd_anymacy\fP"
.br
.RI "\fIMapping between 'pd' MDF markers and LMF anymacy WordForm attribute value (input) \fP"
.ti -1c
.RI "tuple \fBpd_grammaticalNumber\fP"
.br
.RI "\fIMapping between 'pd' MDF markers and LMF grammatical number WordForm attribute value (input) \fP"
.ti -1c
.RI "tuple \fBpd_clusivity\fP"
.br
.RI "\fIMapping between 'pd' MDF markers and LMF clusivity WordForm attribute value (input) \fP"
.ti -1c
.RI "tuple \fBpdl_paradigmLabel\fP"
.br
.RI "\fIMapping between 'pdl' MDF marker value and LMF paradigm label Paradigm attribute value (input) \fP"
.ti -1c
.RI "tuple \fBsd_range\fP"
.br
.RI "\fIPossible values allowed for 'sd' MDF marker\&. \fP"
.ti -1c
.RI "tuple \fBlf_range\fP"
.br
.RI "\fIPossible values allowed for 'lf' MDF marker\&. \fP"
.ti -1c
.RI "tuple \fBps_range\fP"
.br
.RI "\fIPossible values allowed for 'ps' MDF marker\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "def lmf\&.src\&.config\&.mdf\&.get_bw (lexical_entry)"

.PP
Functions to process some MDF fields (output) 
.PP
Definition at line 248 of file mdf\&.py\&.
.SS "def lmf\&.src\&.config\&.mdf\&.set_bw (bw, lexical_entry)"

.PP
Functions to process some MDF fields (input) 
.PP
Definition at line 10 of file mdf\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "string lmf\&.src\&.config\&.mdf\&.ENGLISH = 'eng'"

.PP
Definition at line 5 of file mdf\&.py\&.
.SS "tuple lmf\&.src\&.config\&.mdf\&.lf_range"

.PP
Possible values allowed for 'lf' MDF marker\&. 
.PP
Definition at line 513 of file mdf\&.py\&.
.SS "tuple lmf\&.src\&.config\&.mdf\&.lmf_mdf"

.PP
Mapping between LMF representation and MDF markers (output) 
.PP
Definition at line 255 of file mdf\&.py\&.
.SS "tuple lmf\&.src\&.config\&.mdf\&.mdf_lmf"

.PP
Mapping between MDF markers and LMF representation (input) 
.PP
Definition at line 22 of file mdf\&.py\&.
.SS "list lmf\&.src\&.config\&.mdf\&.mdf_order"

.PP
Order in which MDF markers must be written (output) This is the standard order defined in Appendix B of 'Making Dictionaries\&. A guide to lexicography and the Multi-Dictionary Formatter', Software version 1\&.0, David F\&. Coward, Charles E\&. Grimes, SIL International, Waxhaw, North Carolina, 2000 
.PP
Definition at line 131 of file mdf\&.py\&.
.SS "tuple lmf\&.src\&.config\&.mdf\&.mdf_semanticRelation"
\fBInitial value:\fP
.PP
.nf
1 = dict({
2     "sy" : "synonym",
3     "an" : "antonym",
4     "cf <hm>" : "homonym",
5     "cf <et>" : "etymology",
6     "se" : "subentry",
7     "mn" : "main entry",
8     "cf" : "simple link",
9     "lf" : None,
10     "ev" : None,
11     "ee" : None,
12     "en" : None,
13     "er" : None
14     # "derived form",
15     # "root",
16     # "stem",
17     # "collocation"
18 })
.fi
.PP
Mapping between MDF markers and LMF semantic relation RelatedForm attribute value (input) 
.PP
Definition at line 394 of file mdf\&.py\&.
.SS "string lmf\&.src\&.config\&.mdf\&.NATIONAL = 'nat'"

.PP
Definition at line 6 of file mdf\&.py\&.
.SS "tuple lmf\&.src\&.config\&.mdf\&.pd_anymacy"
\fBInitial value:\fP
.PP
.nf
1 = dict({
2     4 : "inanimate"
3 })
.fi
.PP
Mapping between 'pd' MDF markers and LMF anymacy WordForm attribute value (input) 
.PP
Definition at line 421 of file mdf\&.py\&.
.SS "tuple lmf\&.src\&.config\&.mdf\&.pd_clusivity"
\fBInitial value:\fP
.PP
.nf
1 = dict({
2     'i'     : "inclusive",
3     'e'     : "exclusive"
4 })
.fi
.PP
Mapping between 'pd' MDF markers and LMF clusivity WordForm attribute value (input) 
.PP
Definition at line 435 of file mdf\&.py\&.
.SS "tuple lmf\&.src\&.config\&.mdf\&.pd_grammaticalNumber"
\fBInitial value:\fP
.PP
.nf
1 = dict({
2     'd'     : "dual",
3     'p'     : "plural",
4     "pl"    : "plural",
5     's'     : "singular",
6     "sg"    : "singular"
7 })
.fi
.PP
Mapping between 'pd' MDF markers and LMF grammatical number WordForm attribute value (input) 
.PP
Definition at line 426 of file mdf\&.py\&.
.SS "tuple lmf\&.src\&.config\&.mdf\&.pd_person"
\fBInitial value:\fP
.PP
.nf
1 = dict({
2     1 : "first person",
3     2 : "second person",
4     3 : "third person"
5 })
.fi
.PP
Mapping between 'pd' MDF markers and LMF person WordForm attribute value (input) 
.PP
Definition at line 414 of file mdf\&.py\&.
.SS "tuple lmf\&.src\&.config\&.mdf\&.pdl_paradigmLabel"
\fBInitial value:\fP
.PP
.nf
1 = dict({
2     "la"        : "lexicalized affix",
3     "cc"        : "conjugation class",
4     "past"      : "theme of the past",
5     "comit"     : "comitative",
6     "constr"    : "construction",
7     "dir"       : "directional",
8     "ir"        : "irregularity"
9 })
.fi
.PP
Mapping between 'pdl' MDF marker value and LMF paradigm label Paradigm attribute value (input) 
.PP
Definition at line 441 of file mdf\&.py\&.
.SS "tuple lmf\&.src\&.config\&.mdf\&.ps_partOfSpeech"
\fBInitial value:\fP
.PP
.nf
1 = dict({
2     "adj"           : "adjective",                  # adjective
3     "adv"           : "adverb",                     # adverb(ial)
4     "class"         : "classifier",                 # classifier (MDF)
5     "clf"           : "classifier",                 # classifier (Leipzig)
6     "cnj"           : "conjunction",                # conjunction
7     "disc\&.PTCL"     : "particle",                   # discourse particle
8     "ideo"          : "ideophone",                  # ideophones
9     "intj"          : "interjection",               # interjection
10     "interj"        : "interjection",               # interjection
11     "lnk"           : "linker",                     # linker
12     "n"             : "noun",                       # noun
13     "N"             : "noun",                       # noun
14     "Np"            : "possessive pronouns",        # possessed nouns
15     "_poss\&._pref"   : "possessive pronouns",        # possessed nouns
16     "neg"           : "negation",                   # negative
17     "num"           : "numeral",                    # number
18     "prep"          : "preposition",                # preposition
19     "pro"           : "pronoun",                    # pronoun/pronominal
20     "v"             : "verb",                       # verb
21     "vi"            : "intransitive verb",          # intransitive verb
22     "vi\&.s"          : "stative intransitive verb",  # stative intransitive verb
23     "vr"            : "reflexive verb",             # reflexive/quasi-reflexive/intradirective verb
24     "vt"            : "transitive verb",            # transitive verb
25     "vt/i"          : "bitransistive verb"          # ambitransitive verb
26 })
.fi
.PP
Mapping between 'ps' MDF marker value and LMF part of speech LexicalEntry attribute value (input) 
.PP
Definition at line 366 of file mdf\&.py\&.
.SS "tuple lmf\&.src\&.config\&.mdf\&.ps_range"

.PP
Possible values allowed for 'ps' MDF marker\&. 
.PP
Definition at line 558 of file mdf\&.py\&.
.SS "string lmf\&.src\&.config\&.mdf\&.REGIONAL = 'reg'"

.PP
Definition at line 7 of file mdf\&.py\&.
.SS "tuple lmf\&.src\&.config\&.mdf\&.sd_range"

.PP
Possible values allowed for 'sd' MDF marker\&. 
.PP
Definition at line 453 of file mdf\&.py\&.
.SS "string lmf\&.src\&.config\&.mdf\&.VERNACULAR = 'ver'"

.PP
Define languages\&. 
.PP
Definition at line 4 of file mdf\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
