.TH "lmf.src.utils.error_handling.OutputError" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.utils.error_handling.OutputError \- 
.PP
Exception raised for errors in the output\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlmf\&.src\&.utils\&.error_handling\&.Error\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fBhandle\fP"
.br
.RI "\fIDefine behavior to follow in case this error is caught: display error and exit program\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmsg\fP"
.br
.ti -1c
.RI "\fBexpr\fP"
.br
.ti -1c
.RI "\fBframe_info\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Exception raised for errors in the output\&. 
.PP
Definition at line 69 of file error_handling\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.utils\&.error_handling\&.OutputError\&.__init__ (self, msg, expr = \fCNone\fP)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fImsg\fP Explanation of the error\&. 
.br
\fIexpr\fP Output expression in which the error occurred\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
An \fBOutputError\fP instance\&. 
.RE
.PP

.PP
Definition at line 72 of file error_handling\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lmf\&.src\&.utils\&.error_handling\&.OutputError\&.handle (self)"

.PP
Define behavior to follow in case this error is caught: display error and exit program\&. 
.PP
Definition at line 84 of file error_handling\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.utils\&.error_handling\&.OutputError\&.expr"

.PP
Definition at line 79 of file error_handling\&.py\&.
.SS "lmf\&.src\&.utils\&.error_handling\&.OutputError\&.frame_info"

.PP
Definition at line 82 of file error_handling\&.py\&.
.SS "lmf\&.src\&.utils\&.error_handling\&.OutputError\&.msg"

.PP
Definition at line 78 of file error_handling\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
