.TH "lmf.src.morphosyntax.paradigm.Paradigm" 3 "Thu Nov 27 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.morphosyntax.paradigm.Paradigm \- 
.PP
\fBParadigm\fP is a class representing a morphological paradigm\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "def \fBset_paradigmLabel\fP"
.br
.RI "\fISet paradigm label\&. \fP"
.ti -1c
.RI "def \fBget_paradigmLabel\fP"
.br
.RI "\fIGet paradigm label\&. \fP"
.ti -1c
.RI "def \fBset_paradigm\fP"
.br
.RI "\fISet paradigm\&. \fP"
.ti -1c
.RI "def \fBget_paradigm\fP"
.br
.RI "\fIGet paradigm\&. \fP"
.ti -1c
.RI "def \fBset_language\fP"
.br
.RI "\fISet language of the paradigm\&. \fP"
.ti -1c
.RI "def \fBget_language\fP"
.br
.RI "\fIGet paradigm language\&. \fP"
.ti -1c
.RI "def \fBset_morphology\fP"
.br
.RI "\fISet morphology\&. \fP"
.ti -1c
.RI "def \fBget_morphology\fP"
.br
.RI "\fIGet morphology\&. \fP"
.ti -1c
.RI "def \fBget_lexical_entry\fP"
.br
.RI "\fIGet pointed lexical entry\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBparadigmLabel\fP"
.br
.ti -1c
.RI "\fBparadigm\fP"
.br
.ti -1c
.RI "\fBlanguage\fP"
.br
.ti -1c
.RI "\fBmorphology\fP"
.br
.ti -1c
.RI "\fBtargets\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBParadigm\fP is a class representing a morphological paradigm\&. 
.PP
Definition at line 10 of file paradigm\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.morphosyntax\&.paradigm\&.Paradigm\&.__init__ (self)"

.PP
Constructor\&. \fBParadigm\fP instances are owned by Sense\&. 
.PP
\fBReturns:\fP
.RS 4
A \fBParadigm\fP instance\&. 
.RE
.PP

.PP
Definition at line 13 of file paradigm\&.py\&.
.SS "def lmf\&.src\&.morphosyntax\&.paradigm\&.Paradigm\&.__del__ (self)"

.PP
Destructor\&. 
.PP
Definition at line 28 of file paradigm\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lmf\&.src\&.morphosyntax\&.paradigm\&.Paradigm\&.get_language (self)"

.PP
Get paradigm language\&. 
.PP
\fBReturns:\fP
.RS 4
\fBParadigm\fP attribute 'language'\&. 
.RE
.PP

.PP
Definition at line 77 of file paradigm\&.py\&.
.SS "def lmf\&.src\&.morphosyntax\&.paradigm\&.Paradigm\&.get_lexical_entry (self)"

.PP
Get pointed lexical entry\&. 
.PP
\fBReturns:\fP
.RS 4
\fBParadigm\fP private attribute '__lexical_entry'\&. 
.RE
.PP

.PP
Definition at line 97 of file paradigm\&.py\&.
.SS "def lmf\&.src\&.morphosyntax\&.paradigm\&.Paradigm\&.get_morphology (self)"

.PP
Get morphology\&. 
.PP
\fBReturns:\fP
.RS 4
\fBParadigm\fP attribute 'morphology'\&. 
.RE
.PP

.PP
Definition at line 91 of file paradigm\&.py\&.
.SS "def lmf\&.src\&.morphosyntax\&.paradigm\&.Paradigm\&.get_paradigm (self, language = \fCNone\fP)"

.PP
Get paradigm\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlanguage\fP Language filter\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBParadigm\fP attribute 'paradigm'\&. 
.RE
.PP

.PP
Definition at line 59 of file paradigm\&.py\&.
.SS "def lmf\&.src\&.morphosyntax\&.paradigm\&.Paradigm\&.get_paradigmLabel (self)"

.PP
Get paradigm label\&. 
.PP
\fBReturns:\fP
.RS 4
\fBParadigm\fP attribute 'paradigmLabel'\&. 
.RE
.PP

.PP
Definition at line 45 of file paradigm\&.py\&.
.SS "def lmf\&.src\&.morphosyntax\&.paradigm\&.Paradigm\&.set_language (self, language)"

.PP
Set language of the paradigm\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlanguage\fP The paradigm language to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBParadigm\fP instance\&. 
.RE
.PP

.PP
Definition at line 69 of file paradigm\&.py\&.
.SS "def lmf\&.src\&.morphosyntax\&.paradigm\&.Paradigm\&.set_morphology (self, morphology)"

.PP
Set morphology\&. 
.PP
\fBParameters:\fP
.RS 4
\fImorphology\fP The morphology to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBParadigm\fP instance\&. 
.RE
.PP

.PP
Definition at line 83 of file paradigm\&.py\&.
.SS "def lmf\&.src\&.morphosyntax\&.paradigm\&.Paradigm\&.set_paradigm (self, paradigm)"

.PP
Set paradigm\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparadigm\fP The paradigm to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBParadigm\fP instance\&. 
.RE
.PP

.PP
Definition at line 51 of file paradigm\&.py\&.
.SS "def lmf\&.src\&.morphosyntax\&.paradigm\&.Paradigm\&.set_paradigmLabel (self, paradigm_label)"

.PP
Set paradigm label\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparadigm_label\fP The paradigm label to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBParadigm\fP instance\&. 
.RE
.PP

.PP
Definition at line 34 of file paradigm\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.morphosyntax\&.paradigm\&.Paradigm\&.language"

.PP
Definition at line 20 of file paradigm\&.py\&.
.SS "lmf\&.src\&.morphosyntax\&.paradigm\&.Paradigm\&.morphology"

.PP
Definition at line 21 of file paradigm\&.py\&.
.SS "lmf\&.src\&.morphosyntax\&.paradigm\&.Paradigm\&.paradigm"

.PP
Definition at line 19 of file paradigm\&.py\&.
.SS "lmf\&.src\&.morphosyntax\&.paradigm\&.Paradigm\&.paradigmLabel"

.PP
Definition at line 18 of file paradigm\&.py\&.
.SS "lmf\&.src\&.morphosyntax\&.paradigm\&.Paradigm\&.targets"

.PP
Definition at line 23 of file paradigm\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
