.TH "lmf.src.mrd.subject_field.SubjectField" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.mrd.subject_field.SubjectField \- 
.PP
'Subject Field is a class representing a text string that provides domain or status information\&.' (LMF)  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIDestructor\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlanguage\fP"
.br
.ti -1c
.RI "\fBsemanticDomain\fP"
.br
.ti -1c
.RI "\fBsubject_field\fP"
.br
.RI "\fI\fBSubjectField\fP instances are owned by \fBSubjectField\fP There is zero to many \fBSubjectField\fP instances per \fBSubjectField\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
'Subject Field is a class representing a text string that provides domain or status information\&.' (LMF) 
.PP
Definition at line 6 of file subject_field\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.mrd\&.subject_field\&.SubjectField\&.__init__ (self)"

.PP
Constructor\&. \fBSubjectField\fP instances are owned by Sense\&. 
.PP
\fBReturns:\fP
.RS 4
A \fBSubjectField\fP instance\&. 
.RE
.PP

.PP
Definition at line 9 of file subject_field\&.py\&.
.SS "def lmf\&.src\&.mrd\&.subject_field\&.SubjectField\&.__del__ (self)"

.PP
Destructor\&. Release \fBSubjectField\fP instances\&. 
.PP
Definition at line 20 of file subject_field\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.mrd\&.subject_field\&.SubjectField\&.language"

.PP
Definition at line 14 of file subject_field\&.py\&.
.SS "lmf\&.src\&.mrd\&.subject_field\&.SubjectField\&.semanticDomain"

.PP
Definition at line 15 of file subject_field\&.py\&.
.SS "lmf\&.src\&.mrd\&.subject_field\&.SubjectField\&.subject_field"

.PP
\fBSubjectField\fP instances are owned by \fBSubjectField\fP There is zero to many \fBSubjectField\fP instances per \fBSubjectField\fP\&. 
.PP
Definition at line 18 of file subject_field\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
