.TH "lmf.src.core.form_representation.FormRepresentation" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.core.form_representation.FormRepresentation \- 
.PP
'Form Representation is a class representing one variant orthography of a Form\&.' (LMF)  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Representation\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "def \fBget_speakers\fP"
.br
.RI "\fIGet speakers\&. \fP"
.ti -1c
.RI "def \fBset_writtenForm\fP"
.br
.RI "\fISet written form and script\&. \fP"
.ti -1c
.RI "def \fBget_writtenForm\fP"
.br
.RI "\fIGet written form\&. \fP"
.ti -1c
.RI "def \fBset_variantForm\fP"
.br
.RI "\fISet variant form\&. \fP"
.ti -1c
.RI "def \fBget_variantForm\fP"
.br
.RI "\fIGet variant form\&. \fP"
.ti -1c
.RI "def \fBset_type\fP"
.br
.RI "\fISet variant type\&. \fP"
.ti -1c
.RI "def \fBget_type\fP"
.br
.RI "\fIGet variant type\&. \fP"
.ti -1c
.RI "def \fBset_comment\fP"
.br
.RI "\fISet variant form comment\&. \fP"
.ti -1c
.RI "def \fBget_comment\fP"
.br
.RI "\fIGet variant form comment\&. \fP"
.ti -1c
.RI "def \fBset_language\fP"
.br
.RI "\fISet language used for comment\&. \fP"
.ti -1c
.RI "def \fBget_language\fP"
.br
.RI "\fIGet language used for comment\&. \fP"
.ti -1c
.RI "def \fBset_tone\fP"
.br
.RI "\fISet tone\&. \fP"
.ti -1c
.RI "def \fBget_tone\fP"
.br
.RI "\fIGet tone\&. \fP"
.ti -1c
.RI "def \fBset_geographicalVariant\fP"
.br
.RI "\fISet geographical variant\&. \fP"
.ti -1c
.RI "def \fBget_geographicalVariant\fP"
.br
.RI "\fIGet geographical variant\&. \fP"
.ti -1c
.RI "def \fBset_phoneticForm\fP"
.br
.RI "\fISet phonetic form\&. \fP"
.ti -1c
.RI "def \fBget_phoneticForm\fP"
.br
.RI "\fIGet phonetic form\&. \fP"
.ti -1c
.RI "def \fBset_contextualVariation\fP"
.br
.RI "\fISet contextual variation\&. \fP"
.ti -1c
.RI "def \fBget_contextualVariation\fP"
.br
.RI "\fIGet contextual variation\&. \fP"
.ti -1c
.RI "def \fBset_spellingVariant\fP"
.br
.RI "\fISet spelling variant\&. \fP"
.ti -1c
.RI "def \fBget_spellingVariant\fP"
.br
.RI "\fIGet spelling variant\&. \fP"
.ti -1c
.RI "def \fBset_citationForm\fP"
.br
.RI "\fISet citation form\&. \fP"
.ti -1c
.RI "def \fBget_citationForm\fP"
.br
.RI "\fIGet citation form\&. \fP"
.ti -1c
.RI "def \fBset_dialect\fP"
.br
.RI "\fISet dialect\&. \fP"
.ti -1c
.RI "def \fBget_dialect\fP"
.br
.RI "\fIGet dialect\&. \fP"
.ti -1c
.RI "def \fBset_transliteration\fP"
.br
.RI "\fISet transliteration\&. \fP"
.ti -1c
.RI "def \fBget_transliteration\fP"
.br
.RI "\fIGet transliteration\&. \fP"
.ti -1c
.RI "def \fBset_scriptName\fP"
.br
.RI "\fISet script name\&. \fP"
.ti -1c
.RI "def \fBget_scriptName\fP"
.br
.RI "\fIGet script name\&. \fP"
.ti -1c
.RI "def \fBcreate_audio\fP"
.br
.RI "\fICreate an Audio instance\&. \fP"
.ti -1c
.RI "def \fBget_audio\fP"
.br
.RI "\fIGet the audio resource maintained by the form representation\&. \fP"
.ti -1c
.RI "def \fBset_audio\fP"
.br
.RI "\fISet audio resource\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvariantForm\fP"
.br
.ti -1c
.RI "\fBtype\fP"
.br
.ti -1c
.RI "\fBtransliteration\fP"
.br
.ti -1c
.RI "\fBtone\fP"
.br
.ti -1c
.RI "\fBgeographicalVariant\fP"
.br
.ti -1c
.RI "\fBphoneticForm\fP"
.br
.ti -1c
.RI "\fBcontextualVariation\fP"
.br
.ti -1c
.RI "\fBspellingVariant\fP"
.br
.ti -1c
.RI "\fBcitationForm\fP"
.br
.ti -1c
.RI "\fBdialect\fP"
.br
.ti -1c
.RI "\fBaudio\fP"
.br
.RI "\fIAudio instance is owned by \fBFormRepresentation\fP There is zero or one Audio instance per \fBFormRepresentation\fP\&. \fP"
.ti -1c
.RI "\fBtargets\fP"
.br
.ti -1c
.RI "\fBwrittenForm\fP"
.br
.ti -1c
.RI "\fBcomment\fP"
.br
.ti -1c
.RI "\fBlanguage\fP"
.br
.ti -1c
.RI "\fBscriptName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
'Form Representation is a class representing one variant orthography of a Form\&.' (LMF) 
.PP
Definition at line 11 of file form_representation\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.__init__ (self)"

.PP
Constructor\&. \fBFormRepresentation\fP instances are owned by Form\&. 
.PP
\fBReturns:\fP
.RS 4
A \fBFormRepresentation\fP instance\&. 
.RE
.PP

.PP
Definition at line 14 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.__del__ (self)"

.PP
Destructor\&. Release Audio instances\&. 
.PP
Definition at line 40 of file form_representation\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.create_audio (self)"

.PP
Create an Audio instance\&. 
.PP
\fBReturns:\fP
.RS 4
Audio instance\&. 
.RE
.PP

.PP
Definition at line 297 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.get_audio (self)"

.PP
Get the audio resource maintained by the form representation\&. 
.PP
\fBReturns:\fP
.RS 4
Audio instance\&. 
.RE
.PP

.PP
Definition at line 303 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.get_citationForm (self)"

.PP
Get citation form\&. 
.PP
\fBReturns:\fP
.RS 4
\fBFormRepresentation\fP attribute 'citationForm'\&. 
.RE
.PP

.PP
Definition at line 243 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.get_comment (self, language = \fCNone\fP)"

.PP
Get variant form comment\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlanguage\fP If this argument is given, get comment only if written in this language\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The filtered Representation attribute 'comment'\&. 
.RE
.PP

.PP
Definition at line 126 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.get_contextualVariation (self)"

.PP
Get contextual variation\&. 
.PP
\fBReturns:\fP
.RS 4
\fBFormRepresentation\fP attribute 'contextualVariation'\&. 
.RE
.PP

.PP
Definition at line 211 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.get_dialect (self)"

.PP
Get dialect\&. 
.PP
\fBReturns:\fP
.RS 4
\fBFormRepresentation\fP attribute 'dialect'\&. 
.RE
.PP

.PP
Definition at line 259 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.get_geographicalVariant (self)"

.PP
Get geographical variant\&. 
.PP
\fBReturns:\fP
.RS 4
\fBFormRepresentation\fP attribute 'geographicalVariant'\&. 
.RE
.PP

.PP
Definition at line 179 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.get_language (self)"

.PP
Get language used for comment\&. 
.PP
\fBReturns:\fP
.RS 4
Representation attribute 'language'\&. 
.RE
.PP

.PP
Definition at line 147 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.get_phoneticForm (self)"

.PP
Get phonetic form\&. 
.PP
\fBReturns:\fP
.RS 4
\fBFormRepresentation\fP attribute 'phoneticForm'\&. 
.RE
.PP

.PP
Definition at line 195 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.get_scriptName (self)"

.PP
Get script name\&. 
.PP
\fBReturns:\fP
.RS 4
Representation attribute 'scriptName'\&. 
.RE
.PP

.PP
Definition at line 291 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.get_speakers (self)"

.PP
Get speakers\&. 
.PP
\fBReturns:\fP
.RS 4
\fBFormRepresentation\fP private attribute '__speaker', a Python list of Speaker instances\&. 
.RE
.PP

.PP
Definition at line 49 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.get_spellingVariant (self)"

.PP
Get spelling variant\&. 
.PP
\fBReturns:\fP
.RS 4
\fBFormRepresentation\fP attribute 'spellingVariant'\&. 
.RE
.PP

.PP
Definition at line 227 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.get_tone (self)"

.PP
Get tone\&. 
.PP
\fBReturns:\fP
.RS 4
\fBFormRepresentation\fP attribute 'tone'\&. 
.RE
.PP

.PP
Definition at line 163 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.get_transliteration (self)"

.PP
Get transliteration\&. 
.PP
\fBReturns:\fP
.RS 4
\fBFormRepresentation\fP attribute 'transliteration'\&. 
.RE
.PP

.PP
Definition at line 275 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.get_type (self)"

.PP
Get variant type\&. 
.PP
\fBReturns:\fP
.RS 4
\fBFormRepresentation\fP attribute 'type'\&. 
.RE
.PP

.PP
Definition at line 106 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.get_variantForm (self)"

.PP
Get variant form\&. 
.PP
\fBReturns:\fP
.RS 4
\fBFormRepresentation\fP attribute 'variantForm'\&. 
.RE
.PP

.PP
Definition at line 86 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.get_writtenForm (self, script_name = \fCNone\fP)"

.PP
Get written form\&. 
.PP
\fBParameters:\fP
.RS 4
\fIscript_name\fP If this argument is given, get written form only if written using this script\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The filtered Representation attribute 'writtenForm'\&. 
.RE
.PP

.PP
Definition at line 68 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.set_audio (self, media_type, file_name, author, quality, start_position, duration, external_reference, audio_file_format)"

.PP
Set audio resource\&. Attributes 'mediaType', 'fileName', 'author', 'quality', 'startPosition', 'durationOfEffectiveSpeech', 'externalReference', 'audioFileFormat' are owned by Material/Audio\&. 
.PP
\fBParameters:\fP
.RS 4
\fImedia_type\fP The media type to set\&. 
.br
\fIfile_name\fP Name of the audio file\&. 
.br
\fIauthor\fP Author of the recording\&. 
.br
\fIquality\fP Quality of the recording, in range 'quality_range' defined in '\fBcommon/range\&.py\fP'\&. 
.br
\fIstart_position\fP Start position of the form in the recording, in format 'Thh:mm:ss,msms', e\&.g\&. 'T00:05:00'\&. 
.br
\fIduration\fP Duration of the effcetive speech, in format 'PThhHmmMssS', e\&.g\&. 'PT00:05:00'\&. 
.br
\fIexternal_reference\fP Reference of the audio file, if not directly provided\&. 
.br
\fIaudio_file_format\fP Format of the audio file, e\&.g\&. 'wav'\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBFormRepresentation\fP instance\&. 
.RE
.PP

.PP
Definition at line 309 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.set_citationForm (self, citation_form)"

.PP
Set citation form\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcitation_form\fP The citation form to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBFormRepresentation\fP instance\&. 
.RE
.PP

.PP
Definition at line 233 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.set_comment (self, comment, language = \fCNone\fP)"

.PP
Set variant form comment\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcomment\fP Comment about the variant form\&. 
.br
\fIlanguage\fP Language used for the comment\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBFormRepresentation\fP instance\&. 
.RE
.PP

.PP
Definition at line 112 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.set_contextualVariation (self, contextual_variation)"

.PP
Set contextual variation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcontextualVariation\fP The contextual variation to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBFormRepresentation\fP instance\&. 
.RE
.PP

.PP
Definition at line 201 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.set_dialect (self, dialect)"

.PP
Set dialect\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdialect\fP The dialect to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBFormRepresentation\fP instance\&. 
.RE
.PP

.PP
Definition at line 249 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.set_geographicalVariant (self, geographical_variant)"

.PP
Set geographical variant\&. 
.PP
\fBParameters:\fP
.RS 4
\fIgeographical_variant\fP The geographical variant to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBFormRepresentation\fP instance\&. 
.RE
.PP

.PP
Definition at line 169 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.set_language (self, language)"

.PP
Set language used for comment\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlanguage\fP Language used for the comment\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBFormRepresentation\fP instance\&. 
.RE
.PP

.PP
Definition at line 136 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.set_phoneticForm (self, phonetic_form)"

.PP
Set phonetic form\&. 
.PP
\fBParameters:\fP
.RS 4
\fIphonetic_form\fP The phonetic form to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBFormRepresentation\fP instance\&. 
.RE
.PP

.PP
Definition at line 185 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.set_scriptName (self, script_name)"

.PP
Set script name\&. 
.PP
\fBParameters:\fP
.RS 4
\fIscript_name\fP The script name to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBFormRepresentation\fP instance\&. 
.RE
.PP

.PP
Definition at line 281 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.set_spellingVariant (self, spelling_variant)"

.PP
Set spelling variant\&. 
.PP
\fBParameters:\fP
.RS 4
\fIspelling_variant\fP The spelling variant to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBFormRepresentation\fP instance\&. 
.RE
.PP

.PP
Definition at line 217 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.set_tone (self, tone)"

.PP
Set tone\&. 
.PP
\fBParameters:\fP
.RS 4
\fItone\fP The tone to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBFormRepresentation\fP instance\&. 
.RE
.PP

.PP
Definition at line 153 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.set_transliteration (self, transliteration)"

.PP
Set transliteration\&. 
.PP
\fBParameters:\fP
.RS 4
\fItransliteration\fP The transliteration to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBFormRepresentation\fP instance\&. 
.RE
.PP

.PP
Definition at line 265 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.set_type (self, type)"

.PP
Set variant type\&. 
.PP
\fBParameters:\fP
.RS 4
\fItype\fP Type of variant, in range 'type_variant_range' defined in '\fBcommon/range\&.py\fP'\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBFormRepresentation\fP instance\&. 
.RE
.PP

.PP
Definition at line 92 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.set_variantForm (self, variant_form)"

.PP
Set variant form\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvariant_form\fP The variant form to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBFormRepresentation\fP instance\&. 
.RE
.PP

.PP
Definition at line 76 of file form_representation\&.py\&.
.SS "def lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.set_writtenForm (self, written_form, script_name = \fCNone\fP)"

.PP
Set written form and script\&. 
.PP
\fBParameters:\fP
.RS 4
\fIwritten_form\fP The written form to set\&. 
.br
\fIscript_name\fP Script used for the written form\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBFormRepresentation\fP instance\&. 
.RE
.PP

.PP
Definition at line 55 of file form_representation\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.audio"

.PP
Audio instance is owned by \fBFormRepresentation\fP There is zero or one Audio instance per \fBFormRepresentation\fP\&. 
.PP
Definition at line 33 of file form_representation\&.py\&.
.SS "lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.citationForm"

.PP
Definition at line 29 of file form_representation\&.py\&.
.SS "lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.comment"

.PP
Definition at line 121 of file form_representation\&.py\&.
.SS "lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.contextualVariation"

.PP
Definition at line 27 of file form_representation\&.py\&.
.SS "lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.dialect"

.PP
Definition at line 30 of file form_representation\&.py\&.
.SS "lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.geographicalVariant"

.PP
Definition at line 25 of file form_representation\&.py\&.
.SS "lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.language"

.PP
Definition at line 144 of file form_representation\&.py\&.
.SS "lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.phoneticForm"

.PP
Definition at line 26 of file form_representation\&.py\&.
.SS "lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.scriptName"

.PP
Definition at line 288 of file form_representation\&.py\&.
.SS "lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.spellingVariant"

.PP
Definition at line 28 of file form_representation\&.py\&.
.SS "lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.targets"

.PP
Definition at line 35 of file form_representation\&.py\&.
.SS "lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.tone"

.PP
Definition at line 24 of file form_representation\&.py\&.
.SS "lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.transliteration"

.PP
Definition at line 23 of file form_representation\&.py\&.
.SS "lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.type"

.PP
Definition at line 22 of file form_representation\&.py\&.
.SS "lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.variantForm"

.PP
Definition at line 21 of file form_representation\&.py\&.
.SS "lmf\&.src\&.core\&.form_representation\&.FormRepresentation\&.writtenForm"

.PP
Definition at line 63 of file form_representation\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
