.TH "lmf.src.resources.resource" 3 "Thu Nov 27 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.resources.resource \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBResource\fP"
.br
.RI "\fI\fBResource\fP is an abstract class representing a material or a human resource\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
