.TH "lmf.src.config.tex" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.config.tex \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBlmf_to_tex\fP"
.br
.RI "\fIFunction giving order in which information must be written in LaTeX and mapping between LMF representation and LaTeX (output) \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBpartOfSpeech_tex\fP"
.br
.RI "\fIMapping between LMF part of speech LexicalEntry attribute value and LaTeX layout (output) \fP"
.ti -1c
.RI "tuple \fBparadigmLabel_tex\fP"
.br
.RI "\fIMapping between LMF paradigmLabel Paradigm attribute value and LaTeX layout (output) \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "def lmf\&.src\&.config\&.tex\&.lmf_to_tex (lexical_entry, font = \fCNone\fP, partOfSpeech_mapping = \fCpartOfSpeech_tex\fP, languages = \fC[VERNACULAR\fP, ENGLISH, NATIONAL, REGIONAL)"

.PP
Function giving order in which information must be written in LaTeX and mapping between LMF representation and LaTeX (output) Function to convert LMF lexical entry information to be written into LaTeX commands\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The Lexical Entry LMF instance to display\&. 
.br
\fIfont\fP A Python dictionary describing fonts to use for different languages\&. 
.br
\fIpartOfSpeech_mapping\fP A Python dictionary giving abbreviations for LMF part of speech values\&. 
.br
\fIlanguages\fP A list of languages to consider for LaTeX layout (all by default)\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing the lexical entry in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 59 of file tex\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "tuple lmf\&.src\&.config\&.tex\&.paradigmLabel_tex"
\fBInitial value:\fP
.PP
.nf
1 = dict({
2 })
.fi
.PP
Mapping between LMF paradigmLabel Paradigm attribute value and LaTeX layout (output) 
.PP
Definition at line 55 of file tex\&.py\&.
.SS "tuple lmf\&.src\&.config\&.tex\&.partOfSpeech_tex"

.PP
Mapping between LMF part of speech LexicalEntry attribute value and LaTeX layout (output) 
.PP
Definition at line 8 of file tex\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
