.TH "lmf.src.utils.error_handling.Warning" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.utils.error_handling.Warning \- 
.PP
Base class for warnings in this library\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UserWarning\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fB__str__\fP"
.br
.RI "\fIBuild the string to be displayed\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmsg\fP"
.br
.ti -1c
.RI "\fBframe_info\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base class for warnings in this library\&. 
.PP
Definition at line 97 of file error_handling\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.utils\&.error_handling\&.Warning\&.__init__ (self, msg)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fImsg\fP String to be reported to user\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A \fBWarning\fP instance\&. 
.RE
.PP

.PP
Definition at line 100 of file error_handling\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lmf\&.src\&.utils\&.error_handling\&.Warning\&.__str__ (self)"

.PP
Build the string to be displayed\&. 
.PP
\fBReturns:\fP
.RS 4
A Python string\&. 
.RE
.PP

.PP
Definition at line 110 of file error_handling\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.utils\&.error_handling\&.Warning\&.frame_info"

.PP
Definition at line 108 of file error_handling\&.py\&.
.SS "lmf\&.src\&.utils\&.error_handling\&.Warning\&.msg"

.PP
Definition at line 105 of file error_handling\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
