.TH "lmf.src.mrd.subject_field.SubjectField" 3 "Thu Nov 27 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.mrd.subject_field.SubjectField \- 
.PP
'Subject Field is a class representing a text string that provides domain or status information\&.' (LMF)  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "def \fBset_semanticDomain\fP"
.br
.RI "\fISet semantic domain and language\&. \fP"
.ti -1c
.RI "def \fBget_semanticDomain\fP"
.br
.RI "\fIGet semantic domain\&. \fP"
.ti -1c
.RI "def \fBset_language\fP"
.br
.RI "\fISet language used for semantic domain\&. \fP"
.ti -1c
.RI "def \fBget_language\fP"
.br
.RI "\fIGet language used for semantic domain\&. \fP"
.ti -1c
.RI "def \fBcreate_and_add_subject_field\fP"
.br
.RI "\fICreate and add a subject field\&. \fP"
.ti -1c
.RI "def \fBget_subject_fields\fP"
.br
.RI "\fIGet all subject fields maintained by this subject field\&. \fP"
.ti -1c
.RI "def \fBset_sub_domain\fP"
.br
.RI "\fISet a sub-domain and language\&. \fP"
.ti -1c
.RI "def \fBget_sub_domains\fP"
.br
.RI "\fIGet all sub-domains\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlanguage\fP"
.br
.ti -1c
.RI "\fBsemanticDomain\fP"
.br
.ti -1c
.RI "\fBsubject_field\fP"
.br
.RI "\fI\fBSubjectField\fP instances are owned by \fBSubjectField\fP There is zero to many \fBSubjectField\fP instances per \fBSubjectField\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
'Subject Field is a class representing a text string that provides domain or status information\&.' (LMF) 
.PP
Definition at line 8 of file subject_field\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.mrd\&.subject_field\&.SubjectField\&.__init__ (self)"

.PP
Constructor\&. \fBSubjectField\fP instances are owned by Sense\&. 
.PP
\fBReturns:\fP
.RS 4
A \fBSubjectField\fP instance\&. 
.RE
.PP

.PP
Definition at line 11 of file subject_field\&.py\&.
.SS "def lmf\&.src\&.mrd\&.subject_field\&.SubjectField\&.__del__ (self)"

.PP
Destructor\&. Release \fBSubjectField\fP instances\&. 
.PP
Definition at line 22 of file subject_field\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lmf\&.src\&.mrd\&.subject_field\&.SubjectField\&.create_and_add_subject_field (self)"

.PP
Create and add a subject field\&. 
.PP
\fBReturns:\fP
.RS 4
The created \fBSubjectField\fP instance\&. 
.RE
.PP

.PP
Definition at line 67 of file subject_field\&.py\&.
.SS "def lmf\&.src\&.mrd\&.subject_field\&.SubjectField\&.get_language (self)"

.PP
Get language used for semantic domain\&. 
.PP
\fBReturns:\fP
.RS 4
\fBSubjectField\fP attribute 'language'\&. 
.RE
.PP

.PP
Definition at line 61 of file subject_field\&.py\&.
.SS "def lmf\&.src\&.mrd\&.subject_field\&.SubjectField\&.get_semanticDomain (self, language = \fCNone\fP)"

.PP
Get semantic domain\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlanguage\fP If this argument is given, get semantic domain only if written in this language\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The filtered \fBSubjectField\fP attribute 'semanticDomain'\&. 
.RE
.PP

.PP
Definition at line 43 of file subject_field\&.py\&.
.SS "def lmf\&.src\&.mrd\&.subject_field\&.SubjectField\&.get_sub_domains (self, language = \fCNone\fP)"

.PP
Get all sub-domains\&. Attribute 'semanticDomain' is owned by \fBSubjectField\fP, which is owned by \fBSubjectField\fP, etc\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlanguage\fP If this argument is given, get only semantic domains that are described using this language\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A Python list of all \fBSubjectField\fP attributes 'semanticDomain'\&. 
.RE
.PP

.PP
Definition at line 90 of file subject_field\&.py\&.
.SS "def lmf\&.src\&.mrd\&.subject_field\&.SubjectField\&.get_subject_fields (self)"

.PP
Get all subject fields maintained by this subject field\&. 
.PP
\fBReturns:\fP
.RS 4
A Python list of subject fields\&. 
.RE
.PP

.PP
Definition at line 75 of file subject_field\&.py\&.
.SS "def lmf\&.src\&.mrd\&.subject_field\&.SubjectField\&.set_language (self, language)"

.PP
Set language used for semantic domain\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlanguage\fP Language used to describe the semantic domain\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBSubjectField\fP instance\&. 
.RE
.PP

.PP
Definition at line 51 of file subject_field\&.py\&.
.SS "def lmf\&.src\&.mrd\&.subject_field\&.SubjectField\&.set_semanticDomain (self, semantic_domain, language = \fCNone\fP)"

.PP
Set semantic domain and language\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsemantic_domain\fP The semantic domain to set\&. 
.br
\fIlanguage\fP Language used to describe the semantic domain\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBSubjectField\fP instance\&. 
.RE
.PP

.PP
Definition at line 30 of file subject_field\&.py\&.
.SS "def lmf\&.src\&.mrd\&.subject_field\&.SubjectField\&.set_sub_domain (self, semantic_domain, language = \fCNone\fP)"

.PP
Set a sub-domain and language\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsemantic_domain\fP The sub-domain to set\&. 
.br
\fIlanguage\fP Language used to describe the sub-domain\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBSubjectField\fP instance\&. 
.RE
.PP

.PP
Definition at line 81 of file subject_field\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.mrd\&.subject_field\&.SubjectField\&.language"

.PP
Definition at line 16 of file subject_field\&.py\&.
.SS "lmf\&.src\&.mrd\&.subject_field\&.SubjectField\&.semanticDomain"

.PP
Definition at line 17 of file subject_field\&.py\&.
.SS "lmf\&.src\&.mrd\&.subject_field\&.SubjectField\&.subject_field"

.PP
\fBSubjectField\fP instances are owned by \fBSubjectField\fP There is zero to many \fBSubjectField\fP instances per \fBSubjectField\fP\&. 
.PP
Definition at line 20 of file subject_field\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
