.TH "lmf.src.wrapper" 3 "Thu Nov 27 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.wrapper \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBwrapper\fP"
.br
.RI "\fIWrapper function that calls another function, restoring normal behavior on error\&. \fP"
.ti -1c
.RI "def \fBread_mdf\fP"
.br
.ti -1c
.RI "def \fBread_xml_lmf\fP"
.br
.ti -1c
.RI "def \fBwrite_mdf\fP"
.br
.ti -1c
.RI "def \fBwrite_xml_lmf\fP"
.br
.ti -1c
.RI "def \fBwrite_tex\fP"
.br
.ti -1c
.RI "def \fBwrite_doc\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def lmf\&.src\&.wrapper\&.read_mdf (args, kwds)"

.PP
Definition at line 62 of file wrapper\&.py\&.
.SS "def lmf\&.src\&.wrapper\&.read_xml_lmf (args, kwds)"

.PP
Definition at line 68 of file wrapper\&.py\&.
.SS "def lmf\&.src\&.wrapper\&.wrapper (func, args, kwds)"

.PP
Wrapper function that calls another function, restoring normal behavior on error\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfunc\fP Callable object\&. 
.br
\fIargs\fP Arguments passed to 'func' as its first argument\&. 
.br
\fIkwds\fP Other arguments passed to 'func'\&. 
.RE
.PP

.PP
Definition at line 23 of file wrapper\&.py\&.
.SS "def lmf\&.src\&.wrapper\&.write_doc (args, kwds)"

.PP
Definition at line 102 of file wrapper\&.py\&.
.SS "def lmf\&.src\&.wrapper\&.write_mdf (args, kwds)"

.PP
Definition at line 78 of file wrapper\&.py\&.
.SS "def lmf\&.src\&.wrapper\&.write_tex (args, kwds)"

.PP
Definition at line 93 of file wrapper\&.py\&.
.SS "def lmf\&.src\&.wrapper\&.write_xml_lmf (args, kwds)"

.PP
Definition at line 84 of file wrapper\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
