.TH "lmf.src.morphology.stem.Stem" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.morphology.stem.Stem \- 
.PP
'Stem is a Form subclass representing a morph, thus manages the sublexme parts' (LMF)  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIDestructor\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
'Stem is a Form subclass representing a morph, thus manages the sublexme parts' (LMF) 
.PP
Definition at line 8 of file stem\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.morphology\&.stem\&.Stem\&.__init__ (self)"

.PP
Constructor\&. \fBStem\fP instances are owned by LexicalEntry\&. 
.PP
\fBReturns:\fP
.RS 4
A \fBStem\fP instance\&. 
.RE
.PP

.PP
Definition at line 11 of file stem\&.py\&.
.SS "def lmf\&.src\&.morphology\&.stem\&.Stem\&.__del__ (self)"

.PP
Destructor\&. 
.PP
Definition at line 19 of file stem\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
