.TH "lmf.src.morphology.list_of_components.ListOfComponents" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.morphology.list_of_components.ListOfComponents \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIDestructor\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcomponent\fP"
.br
.RI "\fIComponent instances are owned by \fBListOfComponents\fP There are two or more Component instances per \fBListOfComponents\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
"List of Components is a class representing the aggregative aspect of a multiword expression (MWE). The mechanism can also be applied recursively, so that an MWE way be comprised of components that are themselves MWEs. This class is used in the morphological pattern and MWE pattern packages." (LMF)

.fi
.PP
 
.PP
Definition at line 6 of file list_of_components\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.morphology\&.list_of_components\&.ListOfComponents\&.__init__ (self)"

.PP
Constructor\&. \fBListOfComponents\fP instance is owned by LexicalEntry\&. 
.PP
\fBReturns:\fP
.RS 4
A \fBListOfComponents\fP instance\&. 
.RE
.PP

.PP
Definition at line 9 of file list_of_components\&.py\&.
.SS "def lmf\&.src\&.morphology\&.list_of_components\&.ListOfComponents\&.__del__ (self)"

.PP
Destructor\&. Release Component instances\&. 
.PP
Definition at line 18 of file list_of_components\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.morphology\&.list_of_components\&.ListOfComponents\&.component"

.PP
Component instances are owned by \fBListOfComponents\fP There are two or more Component instances per \fBListOfComponents\fP\&. 
.PP
Definition at line 16 of file list_of_components\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
