.TH "lmf.src.resources" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.resources \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBaudio\fP"
.br
.ti -1c
.RI " \fBhuman_resource\fP"
.br
.ti -1c
.RI " \fBmaterial\fP"
.br
.ti -1c
.RI " \fBpicture\fP"
.br
.ti -1c
.RI " \fBresource\fP"
.br
.ti -1c
.RI " \fBspeaker\fP"
.br
.ti -1c
.RI " \fBvideo\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
