.TH "lmf.src.morphology.lemma.Lemma" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.morphology.lemma.Lemma \- 
.PP
'Lemma is a Form subclass representing a form chosen by convention to designate the Lexical Entry\&. The lemma is usually equivalent to one of the inflected forms, the root, stem or compound phrase\&.' (LMF)\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "def \fBset_lexeme\fP"
.br
.RI "\fISet lexeme\&. \fP"
.ti -1c
.RI "def \fBget_lexeme\fP"
.br
.RI "\fIGet lexeme\&. \fP"
.ti -1c
.RI "def \fBcreate_form_representation\fP"
.br
.RI "\fICreate a form representation\&. \fP"
.ti -1c
.RI "def \fBadd_form_representation\fP"
.br
.RI "\fIAdd a form representation to the lemma\&. \fP"
.ti -1c
.RI "def \fBfind_form_representations\fP"
.br
.RI "\fIFind variant forms\&. \fP"
.ti -1c
.RI "def \fBget_form_representations\fP"
.br
.RI "\fIGet all form representations maintained by the lemma\&. \fP"
.ti -1c
.RI "def \fBget_form_representation\fP"
.br
.RI "\fIGet a given form representation maintained by the lemma\&. \fP"
.ti -1c
.RI "def \fBset_variant_form\fP"
.br
.RI "\fISet variant form and type\&. \fP"
.ti -1c
.RI "def \fBget_variant_forms\fP"
.br
.RI "\fIGet all variant forms of specified type\&. \fP"
.ti -1c
.RI "def \fBset_variant_comment\fP"
.br
.RI "\fISet variant comment and language\&. \fP"
.ti -1c
.RI "def \fBset_tone\fP"
.br
.RI "\fISet tone\&. \fP"
.ti -1c
.RI "def \fBget_tones\fP"
.br
.RI "\fIGet all tones\&. \fP"
.ti -1c
.RI "def \fBset_geographical_variant\fP"
.br
.RI "\fISet geographical variant\&. \fP"
.ti -1c
.RI "def \fBset_phonetic_form\fP"
.br
.RI "\fISet phonetic form\&. \fP"
.ti -1c
.RI "def \fBget_phonetic_forms\fP"
.br
.RI "\fIGet all phonetic forms\&. \fP"
.ti -1c
.RI "def \fBset_contextual_variation\fP"
.br
.RI "\fISet contextual variation\&. \fP"
.ti -1c
.RI "def \fBget_contextual_variations\fP"
.br
.RI "\fIGet all contextual variations\&. \fP"
.ti -1c
.RI "def \fBset_spelling_variant\fP"
.br
.RI "\fISet spelling variant\&. \fP"
.ti -1c
.RI "def \fBget_spelling_variants\fP"
.br
.RI "\fIGet all spelling variants\&. \fP"
.ti -1c
.RI "def \fBset_citation_form\fP"
.br
.RI "\fISet citation form\&. \fP"
.ti -1c
.RI "def \fBget_citation_forms\fP"
.br
.RI "\fIGet all citation forms\&. \fP"
.ti -1c
.RI "def \fBset_dialect\fP"
.br
.RI "\fISet dialect\&. \fP"
.ti -1c
.RI "def \fBset_transliteration\fP"
.br
.RI "\fISet transliteration\&. \fP"
.ti -1c
.RI "def \fBget_transliterations\fP"
.br
.RI "\fIGet all transliterations\&. \fP"
.ti -1c
.RI "def \fBset_script_name\fP"
.br
.RI "\fISet script name\&. \fP"
.ti -1c
.RI "def \fBset_audio\fP"
.br
.RI "\fISet audio resource\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhyphenation\fP"
.br
.ti -1c
.RI "\fBlexeme\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
'Lemma is a Form subclass representing a form chosen by convention to designate the Lexical Entry\&. The lemma is usually equivalent to one of the inflected forms, the root, stem or compound phrase\&.' (LMF)\&. 
.PP
Definition at line 9 of file lemma\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.__init__ (self)"

.PP
Constructor\&. \fBLemma\fP instance is owned by LexicalEntry\&. 
.PP
\fBReturns:\fP
.RS 4
A \fBLemma\fP instance\&. 
.RE
.PP

.PP
Definition at line 12 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.__del__ (self)"

.PP
Destructor\&. 
.PP
Definition at line 22 of file lemma\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.add_form_representation (self, form_representation)"

.PP
Add a form representation to the lemma\&. 
.PP
\fBParameters:\fP
.RS 4
\fIform_representation\fP The FormRepresentation instance to add to the lemma\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLemma\fP instance\&. 
.RE
.PP

.PP
Definition at line 47 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.create_form_representation (self)"

.PP
Create a form representation\&. 
.PP
\fBReturns:\fP
.RS 4
FormRepresentation instance\&. 
.RE
.PP

.PP
Definition at line 41 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.find_form_representations (self, type)"

.PP
Find variant forms\&. This attribute is owned by FormRepresentation\&. 
.PP
\fBParameters:\fP
.RS 4
\fItype\fP The type to consider to retrieve the variant form\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A Python list of found FormRepresentation attributes 'variantForm'\&. 
.RE
.PP

.PP
Definition at line 55 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.get_citation_forms (self, script_name = \fCNone\fP)"

.PP
Get all citation forms\&. This attribute is owned by FormRepresentation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIscript_name\fP If provided, get only citation forms that are written using this script\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A Python list of FormRepresentation attributes 'citationForm'\&. 
.RE
.PP

.PP
Definition at line 299 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.get_contextual_variations (self)"

.PP
Get all contextual variations\&. This attribute is owned by FormRepresentation\&. 
.PP
\fBReturns:\fP
.RS 4
A Python list of FormRepresentation attributes 'contextualVariation'\&. 
.RE
.PP

.PP
Definition at line 236 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.get_form_representation (self, index)"

.PP
Get a given form representation maintained by the lemma\&. 
.PP
\fBParameters:\fP
.RS 4
\fIindex\fP The index of the wanted form representation\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The wanted FormRepresentation instance\&. 
.RE
.PP

.PP
Definition at line 73 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.get_form_representations (self)"

.PP
Get all form representations maintained by the lemma\&. 
.PP
\fBReturns:\fP
.RS 4
A Python list of form representations\&. 
.RE
.PP

.PP
Definition at line 67 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.get_lexeme (self)"

.PP
Get lexeme\&. 
.PP
\fBReturns:\fP
.RS 4
\fBLemma\fP attribute 'lexeme'\&. 
.RE
.PP

.PP
Definition at line 35 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.get_phonetic_forms (self, script_name = \fCNone\fP)"

.PP
Get all phonetic forms\&. This attribute is owned by FormRepresentation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIscript_name\fP If provided, get only phonetic forms that are written using this script\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A Python list of FormRepresentation attributes 'phoneticForm'\&. 
.RE
.PP

.PP
Definition at line 205 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.get_spelling_variants (self)"

.PP
Get all spelling variants\&. This attribute is owned by FormRepresentation\&. 
.PP
\fBReturns:\fP
.RS 4
A Python list of FormRepresentation attributes 'spellingVariant'\&. 
.RE
.PP

.PP
Definition at line 266 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.get_tones (self)"

.PP
Get all tones\&. This attribute is owned by FormRepresentation\&. 
.PP
\fBReturns:\fP
.RS 4
A Python list of FormRepresentation attributes 'tone'\&. 
.RE
.PP

.PP
Definition at line 153 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.get_transliterations (self)"

.PP
Get all transliterations\&. This attribute is owned by FormRepresentation\&. 
.PP
\fBReturns:\fP
.RS 4
A Python list of FormRepresentation attributes 'transliteration'\&. 
.RE
.PP

.PP
Definition at line 349 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.get_variant_forms (self, type = \fC'unspecified'\fP)"

.PP
Get all variant forms of specified type\&. This attribute is owned by FormRepresentation\&. 
.PP
\fBReturns:\fP
.RS 4
A Python list of FormRepresentation attributes 'variantForm' if type matches\&. 
.RE
.PP

.PP
Definition at line 103 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.set_audio (self, media_type, file_name, author, quality, start_position, duration, external_reference, audio_file_format)"

.PP
Set audio resource\&. Attributes 'mediaType', 'fileName', 'author', 'quality', 'startPosition', 'durationOfEffectiveSpeech', 'externalReference', 'audioFileFormat' are owned by Material/Audio, which is owned by FormRepresentation\&. 
.PP
\fBParameters:\fP
.RS 4
\fImedia_type\fP The media type to set\&. 
.br
\fIfile_name\fP Name of the audio file\&. 
.br
\fIauthor\fP Author of the recording\&. 
.br
\fIquality\fP Quality of the recording, in range 'quality_range' defined in '\fBcommon/range\&.py\fP'\&. 
.br
\fIstart_position\fP Start position of the form in the recording, in format 'Thh:mm:ss,msms', e\&.g\&. 'T00:05:00'\&. 
.br
\fIduration\fP Duration of the effcetive speech, in format 'PThhHmmMssS', e\&.g\&. 'PT00:05:00'\&. 
.br
\fIexternal_reference\fP Reference of the audio file, if not directly provided\&. 
.br
\fIaudio_file_format\fP Format of the audio file, e\&.g\&. 'wav'\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLemma\fP instance\&. 
.RE
.PP

.PP
Definition at line 379 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.set_citation_form (self, citation_form, script_name = \fCNone\fP)"

.PP
Set citation form\&. This attribute is owned by FormRepresentation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcitation_form\fP The citation form to set\&. 
.br
\fIscript_name\fP The name of the script used to write the citation form, e\&.g\&. devanagari\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLemma\fP instance\&. 
.RE
.PP

.PP
Definition at line 277 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.set_contextual_variation (self, contextual_variation)"

.PP
Set contextual variation\&. This attribute is owned by FormRepresentation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcontextual_variation\fP The contextual variation to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLemma\fP instance\&. 
.RE
.PP

.PP
Definition at line 217 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.set_dialect (self, dialect)"

.PP
Set dialect\&. This attribute is owned by FormRepresentation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdialect\fP The dialect to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLemma\fP instance\&. 
.RE
.PP

.PP
Definition at line 311 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.set_geographical_variant (self, geographical_variant)"

.PP
Set geographical variant\&. This attribute is owned by FormRepresentation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIgeographical_variant\fP The geographical variant to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLemma\fP instance\&. 
.RE
.PP

.PP
Definition at line 164 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.set_lexeme (self, lexeme)"

.PP
Set lexeme\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexeme\fP The lexeme to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLemma\fP instance\&. 
.RE
.PP

.PP
Definition at line 27 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.set_phonetic_form (self, phonetic_form, script_name = \fCNone\fP)"

.PP
Set phonetic form\&. This attribute is owned by FormRepresentation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIphonetic_form\fP The phonetic form to set\&. 
.br
\fIscript_name\fP The name of the script used to write the phonetic form, e\&.g\&. pinyin\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLemma\fP instance\&. 
.RE
.PP

.PP
Definition at line 183 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.set_script_name (self, script_name)"

.PP
Set script name\&. This attribute is owned by FormRepresentation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIscript_name\fP The script name to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLemma\fP instance\&. 
.RE
.PP

.PP
Definition at line 360 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.set_spelling_variant (self, spelling_variant)"

.PP
Set spelling variant\&. This attribute is owned by FormRepresentation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIspelling_variant\fP The spelling variant to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLemma\fP instance\&. 
.RE
.PP

.PP
Definition at line 247 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.set_tone (self, tone)"

.PP
Set tone\&. This attribute is owned by FormRepresentation\&. 
.PP
\fBParameters:\fP
.RS 4
\fItone\fP The tone to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLemma\fP instance\&. 
.RE
.PP

.PP
Definition at line 134 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.set_transliteration (self, transliteration)"

.PP
Set transliteration\&. This attribute is owned by FormRepresentation\&. 
.PP
\fBParameters:\fP
.RS 4
\fItransliteration\fP The transliteration to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLemma\fP instance\&. 
.RE
.PP

.PP
Definition at line 330 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.set_variant_comment (self, comment, language = \fCNone\fP)"

.PP
Set variant comment and language\&. These attributes are owned by FormRepresentation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcomment\fP Variant comment\&. 
.br
\fIlanguage\fP Language of comment\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLemma\fP instance\&. 
.RE
.PP

.PP
Definition at line 114 of file lemma\&.py\&.
.SS "def lmf\&.src\&.morphology\&.lemma\&.Lemma\&.set_variant_form (self, variant_form, type = \fC'unspecified'\fP)"

.PP
Set variant form and type\&. These attributes are owned by FormRepresentation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvariant_form\fP Variant form\&. 
.br
\fItype\fP Type of variant, in range 'type_variant_range' defined in '\fBcommon/range\&.py\fP'\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLemma\fP instance\&. 
.RE
.PP

.PP
Definition at line 83 of file lemma\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.morphology\&.lemma\&.Lemma\&.hyphenation"

.PP
Definition at line 19 of file lemma\&.py\&.
.SS "lmf\&.src\&.morphology\&.lemma\&.Lemma\&.lexeme"

.PP
Definition at line 20 of file lemma\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
