.TH "lmf.src.core.lexicon" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.core.lexicon \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLexicon\fP"
.br
.RI "\fI'Lexicon is a class containing all the lexical entries of a given language within the entire resource\&.' (LMF) \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
