.TH "lmf.src.resources.material.Material" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.resources.material.Material \- 
.PP
\fBMaterial\fP is a Resource subclass\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Resource\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIAs \fBMaterial\fP is an abstract class, constructor raises an error\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIAs \fBMaterial\fP is an abstract class, desctructor raises an error\&. \fP"
.ti -1c
.RI "def \fB__new__\fP"
.br
.RI "\fIPrivate initialization called from \fBMaterial\fP subclasses\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmediaType\fP"
.br
.ti -1c
.RI "\fBfileName\fP"
.br
.ti -1c
.RI "\fBauthor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBMaterial\fP is a Resource subclass\&. 

\fBMaterial\fP is an abstract class representing an audiovisual resource: an audio recording, a picture or a video\&. The \fBMaterial\fP class allows subclasses\&. 
.PP
Definition at line 8 of file material\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.resources\&.material\&.Material\&.__init__ (self)"

.PP
As \fBMaterial\fP is an abstract class, constructor raises an error\&. 
.PP
Definition at line 11 of file material\&.py\&.
.SS "def lmf\&.src\&.resources\&.material\&.Material\&.__del__ (self)"

.PP
As \fBMaterial\fP is an abstract class, desctructor raises an error\&. 
.PP
Definition at line 16 of file material\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lmf\&.src\&.resources\&.material\&.Material\&.__new__ (self)"

.PP
Private initialization called from \fBMaterial\fP subclasses\&. \fBMaterial\fP subinstances are owned by FormRepresentation\&. 
.PP
Definition at line 21 of file material\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.resources\&.material\&.Material\&.author"

.PP
Definition at line 27 of file material\&.py\&.
.SS "lmf\&.src\&.resources\&.material\&.Material\&.fileName"

.PP
Definition at line 26 of file material\&.py\&.
.SS "lmf\&.src\&.resources\&.material\&.Material\&.mediaType"

.PP
Definition at line 25 of file material\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
