.TH "lmf.src.resources.resource.Resource" 3 "Thu Nov 27 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.resources.resource.Resource \- 
.PP
\fBResource\fP is an abstract class representing a material or a human resource\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIAs \fBResource\fP is an abstract class, constructor raises an error\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIAs \fBResource\fP is an abstract class, desctructor raises an error\&. \fP"
.ti -1c
.RI "def \fB__call__\fP"
.br
.RI "\fIPrivate initialization called from \fBResource\fP subclasses\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBResource\fP is an abstract class representing a material or a human resource\&. 

The \fBResource\fP class allows subclasses\&. 
.PP
Definition at line 6 of file resource\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.resources\&.resource\&.Resource\&.__init__ (self)"

.PP
As \fBResource\fP is an abstract class, constructor raises an error\&. 
.PP
Definition at line 9 of file resource\&.py\&.
.SS "def lmf\&.src\&.resources\&.resource\&.Resource\&.__del__ (self)"

.PP
As \fBResource\fP is an abstract class, desctructor raises an error\&. 
.PP
Definition at line 14 of file resource\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lmf\&.src\&.resources\&.resource\&.Resource\&.__call__ (self)"

.PP
Private initialization called from \fBResource\fP subclasses\&. \fBResource\fP subinstances are owned by LexicalResource\&. 
.PP
Definition at line 19 of file resource\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
