.TH "lmf.src.morphosyntax.paradigm.Paradigm" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.morphosyntax.paradigm.Paradigm \- 
.PP
\fBParadigm\fP is a class representing a morphological paradigm\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "def \fBget_lexical_entry\fP"
.br
.RI "\fIGet pointed lexical entry\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBparadigmLabel\fP"
.br
.ti -1c
.RI "\fBparadigm\fP"
.br
.ti -1c
.RI "\fBlanguage\fP"
.br
.ti -1c
.RI "\fBmorphology\fP"
.br
.ti -1c
.RI "\fBtargets\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBParadigm\fP is a class representing a morphological paradigm\&. 
.PP
Definition at line 6 of file paradigm\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.morphosyntax\&.paradigm\&.Paradigm\&.__init__ (self)"

.PP
Constructor\&. \fBParadigm\fP instances are owned by Sense\&. 
.PP
\fBReturns:\fP
.RS 4
A \fBParadigm\fP instance\&. 
.RE
.PP

.PP
Definition at line 9 of file paradigm\&.py\&.
.SS "def lmf\&.src\&.morphosyntax\&.paradigm\&.Paradigm\&.__del__ (self)"

.PP
Destructor\&. 
.PP
Definition at line 24 of file paradigm\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lmf\&.src\&.morphosyntax\&.paradigm\&.Paradigm\&.get_lexical_entry (self)"

.PP
Get pointed lexical entry\&. 
.PP
\fBReturns:\fP
.RS 4
\fBParadigm\fP private attribute '__lexical_entry'\&. 
.RE
.PP

.PP
Definition at line 30 of file paradigm\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.morphosyntax\&.paradigm\&.Paradigm\&.language"

.PP
Definition at line 16 of file paradigm\&.py\&.
.SS "lmf\&.src\&.morphosyntax\&.paradigm\&.Paradigm\&.morphology"

.PP
Definition at line 17 of file paradigm\&.py\&.
.SS "lmf\&.src\&.morphosyntax\&.paradigm\&.Paradigm\&.paradigm"

.PP
Definition at line 15 of file paradigm\&.py\&.
.SS "lmf\&.src\&.morphosyntax\&.paradigm\&.Paradigm\&.paradigmLabel"

.PP
Definition at line 14 of file paradigm\&.py\&.
.SS "lmf\&.src\&.morphosyntax\&.paradigm\&.Paradigm\&.targets"

.PP
Definition at line 19 of file paradigm\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
