.TH "lmf.src.output.tex" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.output.tex \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBfile_read\fP"
.br
.RI "\fIRead file contents\&. \fP"
.ti -1c
.RI "def \fBinsert_references\fP"
.br
.RI "\fIInsert references to paradigms\&. \fP"
.ti -1c
.RI "def \fBtex_write\fP"
.br
.RI "\fIWrite a LaTeX file\&. \fP"
.ti -1c
.RI "def \fBhandle_font\fP"
.br
.RI "\fIFunctions to process LaTeX layout\&. \fP"
.ti -1c
.RI "def \fBhandle_reserved\fP"
.br
.ti -1c
.RI "def \fBhandle_fi\fP"
.br
.ti -1c
.RI "def \fBhandle_fv\fP"
.br
.ti -1c
.RI "def \fBhandle_fn\fP"
.br
.ti -1c
.RI "def \fBhandle_pinyin\fP"
.br
.ti -1c
.RI "def \fBhandle_caps\fP"
.br
.ti -1c
.RI "def \fBhandle_quotes\fP"
.br
.ti -1c
.RI "def \fBformat_uid\fP"
.br
.RI "\fIFunctions to process LaTeX fields (output) \fP"
.ti -1c
.RI "def \fBformat_link\fP"
.br
.RI "\fIDisplay hyperlink to a lexical entry in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_lexeme\fP"
.br
.RI "\fI'lx', 'hm' and 'lc' fields are flipped if 'lc' field has data\&. \fP"
.ti -1c
.RI "def \fBformat_audio\fP"
.br
.RI "\fIEmbed sound file into PDF\&. \fP"
.ti -1c
.RI "def \fBformat_part_of_speech\fP"
.br
.RI "\fIDisplay part of speech in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_definitions\fP"
.br
.RI "\fIGlosses are supplanted by definitions\&. \fP"
.ti -1c
.RI "def \fBformat_lt\fP"
.br
.RI "\fIDisplay 'lt' in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_sc\fP"
.br
.RI "\fIDisplay 'sc' in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_rf\fP"
.br
.RI "\fIDisplay 'rf' in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_examples\fP"
.br
.RI "\fIDisplay examples in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_usage_notes\fP"
.br
.RI "\fIDisplay usage notes in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_encyclopedic_informations\fP"
.br
.RI "\fIDisplay encyclopedic informations in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_restrictions\fP"
.br
.RI "\fIDisplay restrictions in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_lexical_functions\fP"
.br
.RI "\fIDisplay lexical functions in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_related_forms\fP"
.br
.RI "\fIDisplay related forms in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_variant_forms\fP"
.br
.RI "\fIDisplay variant forms in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_borrowed_word\fP"
.br
.RI "\fIDisplay borrowed word in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_etymology\fP"
.br
.RI "\fIDisplay etymology in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_paradigms\fP"
.br
.RI "\fIDisplay all paradigms in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_table\fP"
.br
.RI "\fIDisplay a table in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_semantic_domains\fP"
.br
.RI "\fIDisplay semantic domains in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_bibliography\fP"
.br
.RI "\fIDisplay bibliography in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_picture\fP"
.br
.RI "\fIDisplay a picture in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_notes\fP"
.br
.RI "\fIDisplay all notes in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_source\fP"
.br
.RI "\fIDisplay source in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_status\fP"
.br
.RI "\fIDisplay status in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBformat_date\fP"
.br
.RI "\fIDo not display date in LaTeX format\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "def lmf\&.src\&.output\&.tex\&.file_read (filename)"

.PP
Read file contents\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP The name of the file with full path containing information to read, for instance the LaTeX header of the document: 'user/config/japhug\&.tex'\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A Python string containing read information\&. 
.RE
.PP

.PP
Definition at line 13 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_audio (lexical_entry, font)"

.PP
Embed sound file into PDF\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string embedding sound in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 346 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_bibliography (lexical_entry, font)"

.PP
Display bibliography in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing bibliography in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 728 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_borrowed_word (lexical_entry, font)"

.PP
Display borrowed word in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing borrowed word in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 634 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_date (lexical_entry, font)"

.PP
Do not display date in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
An empty string\&. 
.RE
.PP

.PP
Definition at line 791 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_definitions (sense, font, languages = \fCNone\fP)"

.PP
Glosses are supplanted by definitions\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsense\fP The current Sense LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.br
\fIlanguages\fP A list of languages to consider for definitions and glosses (all by default)\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing glosses and definitions in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 421 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_encyclopedic_informations (sense, font)"

.PP
Display encyclopedic informations in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsense\fP The current Sense LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing encyclopedic informations in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 533 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_etymology (lexical_entry, font)"

.PP
Display etymology in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing etymology in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 648 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_examples (sense, font, languages = \fCNone\fP)"

.PP
Display examples in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsense\fP The current Sense LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.br
\fIlanguages\fP A list of languages to consider for examples (all by default)\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing examples in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 489 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_lexeme (lexical_entry, font)"

.PP
'lx', 'hm' and 'lc' fields are flipped if 'lc' field has data\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing lexeme in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 318 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_lexical_functions (lexical_entry, font)"

.PP
Display lexical functions in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing lexical functions in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 567 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_link (lexical_entry, font)"

.PP
Display hyperlink to a lexical entry in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The targeted Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing the hyperlink in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 306 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_lt (sense, font)"

.PP
Display 'lt' in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsense\fP The current Sense LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing 'lt' in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 462 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_notes (lexical_entry, font)"

.PP
Display all notes in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing all notes in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 748 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_paradigms (lexical_entry, font)"

.PP
Display all paradigms in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing all paradigms in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 661 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_part_of_speech (lexical_entry, font, mapping = \fCpartOfSpeech_tex\fP, language = \fCNone\fP)"

.PP
Display part of speech in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.br
\fImapping\fP A Python dictionary giving the mapping between LMF part of speech LexicalEntry attribute value and LaTeX layout\&. 
.br
\fIlanguage\fP Language to consider to display part of speech\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing part of speech in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 402 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_picture (lexical_entry, font)"

.PP
Display a picture in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing a picture in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 739 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_related_forms (lexical_entry, font)"

.PP
Display related forms in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing related forms in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 580 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_restrictions (sense, font)"

.PP
Display restrictions in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsense\fP The current Sense LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing restrictions in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 550 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_rf (sense, font)"

.PP
Display 'rf' in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Sense LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing 'rf' in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 480 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_sc (sense, font)"

.PP
Display 'sc' in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsense\fP The current Sense LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing 'sc' in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 471 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_semantic_domains (lexical_entry, font)"

.PP
Display semantic domains in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing semantic domains in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 713 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_source (lexical_entry, font)"

.PP
Display source in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing source in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 771 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_status (lexical_entry, font)"

.PP
Display status in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing status in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 780 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_table (lexical_entry, font)"

.PP
Display a table in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing a table in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 705 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_uid (lexical_entry, font)"

.PP
Functions to process LaTeX fields (output) Transform unique identifier of a lexical entry in ASCII format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The targeted Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing the unique identifier in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 290 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_usage_notes (sense, font)"

.PP
Display usage notes in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsense\fP The current Sense LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing usage notes in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 516 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.format_variant_forms (lexical_entry, font)"

.PP
Display variant forms in LaTeX format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The current Lexical Entry LMF instance\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing variant forms in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 616 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.handle_caps (text)"

.PP
.nf
Handle small caps.
Replace '°xxx' by '\textsc{xxx}' in translated examples.

.fi
.PP
 
.PP
Definition at line 262 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.handle_fi (text)"

.PP
.nf
Replace 'fi:xxx' and '|fi{xxx}' by \\textit{xxx}.

.fi
.PP
 
.PP
Definition at line 217 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.handle_fn (text, font)"

.PP
.nf
Replace 'fn:xxx' and '|fn{xxx}' by font[NATIONAL](xxx).

.fi
.PP
 
.PP
Definition at line 242 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.handle_font (text)"

.PP
Functions to process LaTeX layout\&. 
.PP
.nf
Replace '{xxx}' by '\ipa{xxx}' in 'un', 'xn', 'gn', 'dn', 'en'.

.fi
.PP
 
.PP
Definition at line 188 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.handle_fv (text, font)"

.PP
.nf
Replace 'fv:xxx' and '|fv{xxx}' by font[VERNACULAR](xxx).

.fi
.PP
 
.PP
Definition at line 229 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.handle_pinyin (text)"

.PP
.nf
Replace '@xxx' by '\\textcolor{gray}{xxx}' in 'lx', 'dv', 'xv' fields (already in API).
.fi
.PP
 
.PP
Definition at line 254 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.handle_quotes (text)"

.PP
.nf
Hanlde quotation marks.
Replace each "xxx" by ``xxx".

.fi
.PP
 
.PP
Definition at line 272 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.handle_reserved (text)"

.PP
.nf
Handle reserved characters $ & % # _ ^ except \ { }.

.fi
.PP
 
.PP
Definition at line 197 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.insert_references (lexical_entry)"

.PP
Insert references to paradigms\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexical_entry\fP The targeted Lexical Entry LMF instance\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A string representing the references in LaTeX format\&. 
.RE
.PP

.PP
Definition at line 25 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.tex_write (object, filename, preamble = \fCNone\fP, introduction = \fCNone\fP, lmf2tex = \fClmf_to_tex\fP, font = \fCNone\fP, items = \fClambda lexical_entry: lexical_entry\&.get_lexeme()\fP, sort_order = \fCNone\fP, paradigms = \fC[]\fP, tables = \fC[]\fP)"

.PP
Write a LaTeX file\&. Note that the lexicon must already be ordered at this point\&. Here, parameters 'items' and 'sort_order' are only used to define chapters\&. 
.PP
\fBParameters:\fP
.RS 4
\fIobject\fP The LMF instance to convert into LaTeX output format\&. 
.br
\fIfilename\fP The name of the LaTeX file to write with full path, for instance 'user/output\&.tex'\&. 
.br
\fIpreamble\fP The name of the LaTeX file with full path containing the LaTeX header of the document, for instance 'user/config/japhug\&.tex'\&. Deafult value is None\&. 
.br
\fIlmf2tex\fP A function giving the mapping from LMF representation information that must be written to LaTeX commands, in a defined order\&. Default value is 'lmf_to_tex' function defined in '\fBsrc/config/tex\&.py\fP'\&. Please refer to it as an example\&. 
.br
\fIfont\fP A Python dictionary giving the vernacular, national, regional fonts to apply to a text in LaTeX format\&. 
.br
\fIitems\fP Lambda function giving the item to sort\&. Default value is 'lambda lexical_entry: lexical_entry\&.get_lexeme()', which means that the items to sort are lexemes\&. 
.br
\fIsort_order\fP Default value is 'None', which means that the LaTeX output is alphabetically ordered\&. 
.br
\fIparadigms\fP A Python list of LaTeX filenames with full path containing the paradigms in LaTeX format\&. Default value is an empty list\&. 
.RE
.PP

.PP
Definition at line 53 of file tex\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
