.TH "lmf.src.core.statement.Statement" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.core.statement.Statement \- 
.PP
'Statement is a class representating a narrative description that refines or complements Definition\&.' (LMF)  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fB__del__\fP"
.br
.RI "\fIDestructor\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnoteType\fP"
.br
.ti -1c
.RI "\fBnote\fP"
.br
.ti -1c
.RI "\fBlanguage\fP"
.br
.ti -1c
.RI "\fBencyclopedicInformation\fP"
.br
.ti -1c
.RI "\fBusageNote\fP"
.br
.ti -1c
.RI "\fBrestriction\fP"
.br
.ti -1c
.RI "\fBderivation\fP"
.br
.ti -1c
.RI "\fBborrowedWord\fP"
.br
.ti -1c
.RI "\fBwrittenForm\fP"
.br
.ti -1c
.RI "\fBsense\fP"
.br
.ti -1c
.RI "\fBetymology\fP"
.br
.ti -1c
.RI "\fBetymologyComment\fP"
.br
.ti -1c
.RI "\fBetymologyGloss\fP"
.br
.ti -1c
.RI "\fBetymologySource\fP"
.br
.ti -1c
.RI "\fBtermSourceLanguage\fP"
.br
.ti -1c
.RI "\fBtargetLexicalEntry\fP"
.br
.ti -1c
.RI "\fBscientificName\fP"
.br
.ti -1c
.RI "\fBtext_representation\fP"
.br
.RI "\fITextRepresentation instances are owned by \fBStatement\fP There is zero to many TextRepresentation instances per \fBStatement\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
'Statement is a class representating a narrative description that refines or complements Definition\&.' (LMF) 
.PP
Definition at line 6 of file statement\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lmf\&.src\&.core\&.statement\&.Statement\&.__init__ (self)"

.PP
Constructor\&. \fBStatement\fP instances are owned by Definition\&. 
.PP
\fBReturns:\fP
.RS 4
A \fBStatement\fP instance\&. 
.RE
.PP

.PP
Definition at line 9 of file statement\&.py\&.
.SS "def lmf\&.src\&.core\&.statement\&.Statement\&.__del__ (self)"

.PP
Destructor\&. Release TextRepresentation instances\&. 
.PP
Definition at line 35 of file statement\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lmf\&.src\&.core\&.statement\&.Statement\&.borrowedWord"

.PP
Definition at line 21 of file statement\&.py\&.
.SS "lmf\&.src\&.core\&.statement\&.Statement\&.derivation"

.PP
Definition at line 20 of file statement\&.py\&.
.SS "lmf\&.src\&.core\&.statement\&.Statement\&.encyclopedicInformation"

.PP
Definition at line 17 of file statement\&.py\&.
.SS "lmf\&.src\&.core\&.statement\&.Statement\&.etymology"

.PP
Definition at line 24 of file statement\&.py\&.
.SS "lmf\&.src\&.core\&.statement\&.Statement\&.etymologyComment"

.PP
Definition at line 25 of file statement\&.py\&.
.SS "lmf\&.src\&.core\&.statement\&.Statement\&.etymologyGloss"

.PP
Definition at line 26 of file statement\&.py\&.
.SS "lmf\&.src\&.core\&.statement\&.Statement\&.etymologySource"

.PP
Definition at line 27 of file statement\&.py\&.
.SS "lmf\&.src\&.core\&.statement\&.Statement\&.language"

.PP
Definition at line 16 of file statement\&.py\&.
.SS "lmf\&.src\&.core\&.statement\&.Statement\&.note"

.PP
Definition at line 15 of file statement\&.py\&.
.SS "lmf\&.src\&.core\&.statement\&.Statement\&.noteType"

.PP
Definition at line 14 of file statement\&.py\&.
.SS "lmf\&.src\&.core\&.statement\&.Statement\&.restriction"

.PP
Definition at line 19 of file statement\&.py\&.
.SS "lmf\&.src\&.core\&.statement\&.Statement\&.scientificName"

.PP
Definition at line 30 of file statement\&.py\&.
.SS "lmf\&.src\&.core\&.statement\&.Statement\&.sense"

.PP
Definition at line 23 of file statement\&.py\&.
.SS "lmf\&.src\&.core\&.statement\&.Statement\&.targetLexicalEntry"

.PP
Definition at line 29 of file statement\&.py\&.
.SS "lmf\&.src\&.core\&.statement\&.Statement\&.termSourceLanguage"

.PP
Definition at line 28 of file statement\&.py\&.
.SS "lmf\&.src\&.core\&.statement\&.Statement\&.text_representation"

.PP
TextRepresentation instances are owned by \fBStatement\fP There is zero to many TextRepresentation instances per \fBStatement\fP\&. 
.PP
Definition at line 33 of file statement\&.py\&.
.SS "lmf\&.src\&.core\&.statement\&.Statement\&.usageNote"

.PP
Definition at line 18 of file statement\&.py\&.
.SS "lmf\&.src\&.core\&.statement\&.Statement\&.writtenForm"

.PP
Definition at line 22 of file statement\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
