.TH "lmf.src.output.tex" 3 "Thu Nov 27 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmf.src.output.tex \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBcompute_header\fP"
.br
.RI "\fICreate LaTeX header\&. \fP"
.ti -1c
.RI "def \fBtex_write\fP"
.br
.RI "\fIWrite a LaTeX file\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "def lmf\&.src\&.output\&.tex\&.compute_header (preamble)"

.PP
Create LaTeX header\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpreamble\fP The name of the LaTeX file with full path containing the LaTeX header of the document, for instance 'user/config/japhug\&.tex'\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A Python string containing read information\&. 
.RE
.PP

.PP
Definition at line 7 of file tex\&.py\&.
.SS "def lmf\&.src\&.output\&.tex\&.tex_write (object, filename, preamble = \fCNone\fP, lmf2tex = \fClmf_to_tex\fP)"

.PP
Write a LaTeX file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIobject\fP The LMF instance to convert into LaTeX output format\&. 
.br
\fIfilename\fP The name of the LaTeX file to write with full path, for instance 'user/output\&.tex'\&. 
.br
\fIpreamble\fP The name of the LaTeX file with full path containing the LaTeX header of the document, for instance 'user/config/japhug\&.tex'\&. Deafult value is None\&. 
.br
\fIlmf2tex\fP A function giving the mapping from LMF representation information that must be written to LaTeX commands, in a defined order\&. Default value is 'lmf_to_tex' function defined in '\fBsrc/config/tex\&.py\fP'\&. Please refer to it as an example\&. 
.RE
.PP

.PP
Definition at line 19 of file tex\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
