.TH "/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/output/mdf.py" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/output/mdf.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlmf\&.src\&.output\&.mdf\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.mdf\&.mdf_write\fP"
.br
.RI "\fIWrite an MDF file\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.mdf\&.parse_list\fP"
.br
.RI "\fIParse a group of markers and write them into an MDF file\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.mdf\&.write_line\fP"
.br
.RI "\fIWrite a line into an MDF file\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
