.TH "/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/output/odt.py" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/output/odt.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlmf\&.src\&.output\&.odt\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBlmf\&.src\&.output\&.odt\&.textdoc\fP = OpenDocumentText()"
.br
.ti -1c
.RI "\fBlmf\&.src\&.output\&.odt\&.s\fP = textdoc\&.styles"
.br
.ti -1c
.RI "tuple \fBlmf\&.src\&.output\&.odt\&.h1style\fP = Style(name='Heading 1', family='paragraph')"
.br
.ti -1c
.RI "tuple \fBlmf\&.src\&.output\&.odt\&.boldstyle\fP = Style(name='Bold', family='text')"
.br
.ti -1c
.RI "tuple \fBlmf\&.src\&.output\&.odt\&.boldprop\fP = TextProperties(fontweight='bold', fontname='Arial', fontsize='8pt')"
.br
.ti -1c
.RI "tuple \fBlmf\&.src\&.output\&.odt\&.h\fP = H(outlinelevel=1, stylename=h1style, text='My first text')"
.br
.ti -1c
.RI "tuple \fBlmf\&.src\&.output\&.odt\&.p\fP = P(text='Hello world\&. ')"
.br
.ti -1c
.RI "tuple \fBlmf\&.src\&.output\&.odt\&.boldpart\fP = Span(stylename=boldstyle, text='This part is bold\&. ')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
