.TH "/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/morphosyntax/paradigm.py" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/morphosyntax/paradigm.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlmf\&.src\&.morphosyntax\&.paradigm\&.Paradigm\fP"
.br
.RI "\fI\fBParadigm\fP is a class representing a morphological paradigm\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlmf\&.src\&.morphosyntax\&.paradigm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
