.TH "/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/common/range.py" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/common/range.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlmf\&.src\&.common\&.range\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBlmf\&.src\&.common\&.range\&.partOfSpeech_range\fP"
.br
.RI "\fIPossible values allowed for LMF part of speech LexicalEntry attribute\&. \fP"
.ti -1c
.RI "tuple \fBlmf\&.src\&.common\&.range\&.type_variant_range\fP"
.br
.RI "\fIPossible values allowed for LMF variant type FormRepresentation attribute\&. \fP"
.ti -1c
.RI "tuple \fBlmf\&.src\&.common\&.range\&.noteType_range\fP"
.br
.RI "\fIPossible values allowed for LMF note type Statement attribute\&. \fP"
.ti -1c
.RI "tuple \fBlmf\&.src\&.common\&.range\&.grammaticalNumber_range\fP"
.br
.RI "\fIPossible values allowed for LMF grammatical number WordForm attribute\&. \fP"
.ti -1c
.RI "tuple \fBlmf\&.src\&.common\&.range\&.grammaticalGender_range\fP"
.br
.RI "\fIPossible values allowed for LMF grammatical gender WordForm attribute\&. \fP"
.ti -1c
.RI "tuple \fBlmf\&.src\&.common\&.range\&.person_range\fP"
.br
.RI "\fIPossible values allowed for LMF grammatical person WordForm attribute\&. \fP"
.ti -1c
.RI "tuple \fBlmf\&.src\&.common\&.range\&.anymacy_range\fP"
.br
.RI "\fIPossible values allowed for LMF anymacy WordForm attribute\&. \fP"
.ti -1c
.RI "tuple \fBlmf\&.src\&.common\&.range\&.clusivity_range\fP"
.br
.RI "\fIPossible values allowed for LMF clusivity WordForm attribute\&. \fP"
.ti -1c
.RI "tuple \fBlmf\&.src\&.common\&.range\&.tense_range\fP"
.br
.RI "\fIPossible values allowed for LMF grammatical tense WordForm attribute\&. \fP"
.ti -1c
.RI "tuple \fBlmf\&.src\&.common\&.range\&.voice_range\fP"
.br
.RI "\fIPossible values allowed for LMF voice WordForm attribute\&. \fP"
.ti -1c
.RI "tuple \fBlmf\&.src\&.common\&.range\&.verbFormMood_range\fP"
.br
.RI "\fIPossible values allowed for LMF verb form mood WordForm attribute\&. \fP"
.ti -1c
.RI "tuple \fBlmf\&.src\&.common\&.range\&.degree_range\fP"
.br
.RI "\fIPossible values allowed for LMF degree WordForm attribute\&. \fP"
.ti -1c
.RI "tuple \fBlmf\&.src\&.common\&.range\&.semanticRelation_range\fP"
.br
.RI "\fIPossible values allowed for semantic relation RelatedForm attribute\&. \fP"
.ti -1c
.RI "tuple \fBlmf\&.src\&.common\&.range\&.paradigmLabel_range\fP"
.br
.RI "\fIPossible values allowed for paradigm label Paradigm attribute\&. \fP"
.ti -1c
.RI "tuple \fBlmf\&.src\&.common\&.range\&.type_example_range\fP"
.br
.RI "\fIPossible values allowed for example type Context attribute\&. \fP"
.ti -1c
.RI "tuple \fBlmf\&.src\&.common\&.range\&.mediaType_range\fP"
.br
.RI "\fIPossible values allowed for media type Material attribute\&. \fP"
.ti -1c
.RI "tuple \fBlmf\&.src\&.common\&.range\&.quality_range\fP"
.br
.RI "\fIPossible values allowed for quality Audio attribute\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
