.TH "/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/core/representation.py" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/core/representation.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlmf\&.src\&.core\&.representation\&.Representation\fP"
.br
.RI "\fI'Representation class is an abstract class representing a Unicode string as well as, if needed, the unique attribute-value pairs that describe the specific language, script and orthography\&.' (LMF) \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlmf\&.src\&.core\&.representation\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
