.TH "/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/resources/resource.py" 3 "Thu Nov 27 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/resources/resource.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlmf\&.src\&.resources\&.resource\&.Resource\fP"
.br
.RI "\fI\fBResource\fP is an abstract class representing a material or a human resource\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlmf\&.src\&.resources\&.resource\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
