.TH "/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/core/sense.py" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/core/sense.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlmf\&.src\&.core\&.sense\&.Sense\fP"
.br
.RI "\fI'Sense is a class representing one meaning of a lexical entry\&. The Sense class allows for hierarchical senses in that a sense may be more specific than another sense of the same lexical entry\&.' (LMF) \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlmf\&.src\&.core\&.sense\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
