.TH "src.core.sense.Sense" 3 "Thu Sep 18 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.core.sense.Sense \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsenseNumber\fP"
.br
.ti -1c
.RI "\fBid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file sense\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.core\&.sense\&.Sense\&.__init__ (self)"

.PP
Definition at line 4 of file sense\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "src\&.core\&.sense\&.Sense\&.id"

.PP
Definition at line 6 of file sense\&.py\&.
.SS "src\&.core\&.sense\&.Sense\&.senseNumber"

.PP
Definition at line 5 of file sense\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
