.TH "src.core.representation.Representation" 3 "Thu Sep 18 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.core.representation.Representation \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcomment\fP"
.br
.ti -1c
.RI "\fBwrittenForm\fP"
.br
.ti -1c
.RI "\fBlanguage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file representation\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.core\&.representation\&.Representation\&.__init__ (self)"

.PP
Definition at line 4 of file representation\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "src\&.core\&.representation\&.Representation\&.comment"

.PP
Definition at line 5 of file representation\&.py\&.
.SS "src\&.core\&.representation\&.Representation\&.language"

.PP
Definition at line 7 of file representation\&.py\&.
.SS "src\&.core\&.representation\&.Representation\&.writtenForm"

.PP
Definition at line 6 of file representation\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
