.TH "src.output.writer.Writer" 3 "Mon Sep 8 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.output.writer.Writer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBoutput_file\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1 of file writer\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.output\&.writer\&.Writer\&.__init__ (self)"

.PP
Definition at line 2 of file writer\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "src\&.output\&.writer\&.Writer\&.output_file"

.PP
Definition at line 3 of file writer\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
