.TH "src.core.form.Form" 3 "Thu Sep 18 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.core.form.Form \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvariantForm\fP"
.br
.ti -1c
.RI "\fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file form\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.core\&.form\&.Form\&.__init__ (self)"

.PP
Definition at line 4 of file form\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "src\&.core\&.form\&.Form\&.type"

.PP
Definition at line 6 of file form\&.py\&.
.SS "src\&.core\&.form\&.Form\&.variantForm"

.PP
Definition at line 5 of file form\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
