.TH "src.core.definition.Definition" 3 "Thu Sep 18 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.core.definition.Definition \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlanguage\fP"
.br
.ti -1c
.RI "\fBdefinition\fP"
.br
.ti -1c
.RI "\fBgloss\fP"
.br
.ti -1c
.RI "\fBliterally\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file definition\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.core\&.definition\&.Definition\&.__init__ (self)"

.PP
Definition at line 4 of file definition\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "src\&.core\&.definition\&.Definition\&.definition"

.PP
Definition at line 6 of file definition\&.py\&.
.SS "src\&.core\&.definition\&.Definition\&.gloss"

.PP
Definition at line 7 of file definition\&.py\&.
.SS "src\&.core\&.definition\&.Definition\&.language"

.PP
Definition at line 5 of file definition\&.py\&.
.SS "src\&.core\&.definition\&.Definition\&.literally"

.PP
Definition at line 8 of file definition\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
