.TH "src.resources.picture.Picture" 3 "Thu Sep 18 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.resources.picture.Picture \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Material\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfilename\fP"
.br
.ti -1c
.RI "\fBreference\fP"
.br
.ti -1c
.RI "\fBwidth\fP"
.br
.ti -1c
.RI "\fBheight\fP"
.br
.ti -1c
.RI "\fBformat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file picture\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.resources\&.picture\&.Picture\&.__init__ (self)"

.PP
Definition at line 6 of file picture\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "src\&.resources\&.picture\&.Picture\&.filename"

.PP
Definition at line 7 of file picture\&.py\&.
.SS "src\&.resources\&.picture\&.Picture\&.format"

.PP
Definition at line 11 of file picture\&.py\&.
.SS "src\&.resources\&.picture\&.Picture\&.height"

.PP
Definition at line 10 of file picture\&.py\&.
.SS "src\&.resources\&.picture\&.Picture\&.reference"

.PP
Definition at line 8 of file picture\&.py\&.
.SS "src\&.resources\&.picture\&.Picture\&.width"

.PP
Definition at line 9 of file picture\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
