.TH "src.core.global_information.GlobalInformation" 3 "Thu Sep 18 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.core.global_information.GlobalInformation \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlanguageCode\fP"
.br
.ti -1c
.RI "\fBauthor\fP"
.br
.ti -1c
.RI "\fBversion\fP"
.br
.ti -1c
.RI "\fBlastUpdate\fP"
.br
.ti -1c
.RI "\fBlicense\fP"
.br
.ti -1c
.RI "\fBcharacterEncoding\fP"
.br
.ti -1c
.RI "\fBdateCoding\fP"
.br
.ti -1c
.RI "\fBcreationDate\fP"
.br
.ti -1c
.RI "\fBprojectName\fP"
.br
.ti -1c
.RI "\fBdescription\fP"
.br
.ti -1c
.RI "\fBbibliographicCitation\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file global_information\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.core\&.global_information\&.GlobalInformation\&.__init__ (self)"

.PP
Definition at line 4 of file global_information\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "src\&.core\&.global_information\&.GlobalInformation\&.author"

.PP
Definition at line 6 of file global_information\&.py\&.
.SS "src\&.core\&.global_information\&.GlobalInformation\&.bibliographicCitation"

.PP
Definition at line 15 of file global_information\&.py\&.
.SS "src\&.core\&.global_information\&.GlobalInformation\&.characterEncoding"

.PP
Definition at line 10 of file global_information\&.py\&.
.SS "src\&.core\&.global_information\&.GlobalInformation\&.creationDate"

.PP
Definition at line 12 of file global_information\&.py\&.
.SS "src\&.core\&.global_information\&.GlobalInformation\&.dateCoding"

.PP
Definition at line 11 of file global_information\&.py\&.
.SS "src\&.core\&.global_information\&.GlobalInformation\&.description"

.PP
Definition at line 14 of file global_information\&.py\&.
.SS "src\&.core\&.global_information\&.GlobalInformation\&.languageCode"

.PP
Definition at line 5 of file global_information\&.py\&.
.SS "src\&.core\&.global_information\&.GlobalInformation\&.lastUpdate"

.PP
Definition at line 8 of file global_information\&.py\&.
.SS "src\&.core\&.global_information\&.GlobalInformation\&.license"

.PP
Definition at line 9 of file global_information\&.py\&.
.SS "src\&.core\&.global_information\&.GlobalInformation\&.projectName"

.PP
Definition at line 13 of file global_information\&.py\&.
.SS "src\&.core\&.global_information\&.GlobalInformation\&.version"

.PP
Definition at line 7 of file global_information\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
