.TH "src.input.ite.Ite" 3 "Fri Sep 12 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.input.ite.Ite \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits null\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1 of file ite\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.input\&.ite\&.Ite\&.__init__ (self)"

.PP
Definition at line 2 of file ite\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
