.TH "src.mrd.subject_field.SubjectField" 3 "Thu Sep 18 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.mrd.subject_field.SubjectField \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlanguage\fP"
.br
.ti -1c
.RI "\fBsemanticDomain\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file subject_field\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.mrd\&.subject_field\&.SubjectField\&.__init__ (self)"

.PP
Definition at line 4 of file subject_field\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "src\&.mrd\&.subject_field\&.SubjectField\&.language"

.PP
Definition at line 5 of file subject_field\&.py\&.
.SS "src\&.mrd\&.subject_field\&.SubjectField\&.semanticDomain"

.PP
Definition at line 6 of file subject_field\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
