.TH "src.output.xml_lmf" 3 "Thu Sep 18 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.output.xml_lmf \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBxml_lmf_write\fP"
.br
.RI "\fIWrite an XML LMF file\&. \fP"
.ti -1c
.RI "def \fBbuild_sub_elements\fP"
.br
.RI "\fICreate XML sub-elements to an existing XML element by parsing an LMF object instance\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "def src\&.output\&.xml_lmf\&.build_sub_elements (object, element)"

.PP
Create XML sub-elements to an existing XML element by parsing an LMF object instance\&. 
.PP
\fBParameters:\fP
.RS 4
\fIobject\fP An LMF object instance\&. 
.br
\fIelement\fP XML element for which sub-elements have to be created according to LMF object attributes\&. 
.RE
.PP

.PP
Definition at line 17 of file xml_lmf\&.py\&.
.SS "def src\&.output\&.xml_lmf\&.xml_lmf_write (object, filename)"

.PP
Write an XML LMF file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIobject\fP The LMF instance to write as XML\&. 
.br
\fIfilename\fP The name of the XML LMF file to write with full path, for instance 'user/output\&.xml'\&. 
.RE
.PP

.PP
Definition at line 5 of file xml_lmf\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
