.TH "src.morphosyntax.lexical_entry.LexicalEntry" 3 "Mon Sep 8 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.morphosyntax.lexical_entry.LexicalEntry \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhomonymNumber\fP"
.br
.ti -1c
.RI "\fBstatus\fP"
.br
.ti -1c
.RI "\fBdate\fP"
.br
.ti -1c
.RI "\fBpartOfSpeech\fP"
.br
.ti -1c
.RI "\fBindependentWord\fP"
.br
.ti -1c
.RI "\fBbibliography\fP"
.br
.ti -1c
.RI "\fBid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1 of file lexical_entry\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.morphosyntax\&.lexical_entry\&.LexicalEntry\&.__init__ (self)"

.PP
Definition at line 2 of file lexical_entry\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "src\&.morphosyntax\&.lexical_entry\&.LexicalEntry\&.bibliography"

.PP
Definition at line 8 of file lexical_entry\&.py\&.
.SS "src\&.morphosyntax\&.lexical_entry\&.LexicalEntry\&.date"

.PP
Definition at line 5 of file lexical_entry\&.py\&.
.SS "src\&.morphosyntax\&.lexical_entry\&.LexicalEntry\&.homonymNumber"

.PP
Definition at line 3 of file lexical_entry\&.py\&.
.SS "src\&.morphosyntax\&.lexical_entry\&.LexicalEntry\&.id"

.PP
Definition at line 9 of file lexical_entry\&.py\&.
.SS "src\&.morphosyntax\&.lexical_entry\&.LexicalEntry\&.independentWord"

.PP
Definition at line 7 of file lexical_entry\&.py\&.
.SS "src\&.morphosyntax\&.lexical_entry\&.LexicalEntry\&.partOfSpeech"

.PP
Definition at line 6 of file lexical_entry\&.py\&.
.SS "src\&.morphosyntax\&.lexical_entry\&.LexicalEntry\&.status"

.PP
Definition at line 4 of file lexical_entry\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
