.TH "src.resources.speaker.Speaker" 3 "Thu Sep 18 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.resources.speaker.Speaker \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits HumanResource\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBspeakerID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file speaker\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.resources\&.speaker\&.Speaker\&.__init__ (self)"

.PP
Definition at line 6 of file speaker\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "src\&.resources\&.speaker\&.Speaker\&.speakerID"

.PP
Definition at line 7 of file speaker\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
