.TH "src.morphology.stem.Stem" 3 "Thu Sep 18 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.morphology.stem.Stem \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file stem\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.morphology\&.stem\&.Stem\&.__init__ (self)"

.PP
Definition at line 6 of file stem\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
