.TH "src.resources.video.Video" 3 "Thu Sep 18 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.resources.video.Video \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Material\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdescription\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file video\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.resources\&.video\&.Video\&.__init__ (self)"

.PP
Definition at line 6 of file video\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "src\&.resources\&.video\&.Video\&.description"

.PP
Definition at line 7 of file video\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
