.TH "src.input.reader.Reader" 3 "Mon Sep 8 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.input.reader.Reader \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1 of file reader\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.input\&.reader\&.Reader\&.__init__ (self)"

.PP
Definition at line 2 of file reader\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
