.TH "src.morphology.related_form.RelatedForm" 3 "Thu Sep 18 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.morphology.related_form.RelatedForm \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsemanticRelation\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file related_form\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.morphology\&.related_form\&.RelatedForm\&.__init__ (self)"

.PP
Definition at line 6 of file related_form\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "src\&.morphology\&.related_form\&.RelatedForm\&.semanticRelation"

.PP
Definition at line 7 of file related_form\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
