.TH "src.resources.form_representation.FormRepresentation" 3 "Fri Sep 12 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.resources.form_representation.FormRepresentation \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits null\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtransliteration\fP"
.br
.ti -1c
.RI "\fBtone\fP"
.br
.ti -1c
.RI "\fBgeographicalVariant\fP"
.br
.ti -1c
.RI "\fBphoneticForm\fP"
.br
.ti -1c
.RI "\fBcontextualVariation\fP"
.br
.ti -1c
.RI "\fBspellingVariant\fP"
.br
.ti -1c
.RI "\fBcitationForm\fP"
.br
.ti -1c
.RI "\fBdialect\fP"
.br
.ti -1c
.RI "\fBlanguage\fP"
.br
.ti -1c
.RI "\fBscriptName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1 of file form_representation\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.resources\&.form_representation\&.FormRepresentation\&.__init__ (self)"

.PP
Definition at line 2 of file form_representation\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "src\&.resources\&.form_representation\&.FormRepresentation\&.citationForm"

.PP
Definition at line 9 of file form_representation\&.py\&.
.SS "src\&.resources\&.form_representation\&.FormRepresentation\&.contextualVariation"

.PP
Definition at line 7 of file form_representation\&.py\&.
.SS "src\&.resources\&.form_representation\&.FormRepresentation\&.dialect"

.PP
Definition at line 10 of file form_representation\&.py\&.
.SS "src\&.resources\&.form_representation\&.FormRepresentation\&.geographicalVariant"

.PP
Definition at line 5 of file form_representation\&.py\&.
.SS "src\&.resources\&.form_representation\&.FormRepresentation\&.language"

.PP
Definition at line 11 of file form_representation\&.py\&.
.SS "src\&.resources\&.form_representation\&.FormRepresentation\&.phoneticForm"

.PP
Definition at line 6 of file form_representation\&.py\&.
.SS "src\&.resources\&.form_representation\&.FormRepresentation\&.scriptName"

.PP
Definition at line 12 of file form_representation\&.py\&.
.SS "src\&.resources\&.form_representation\&.FormRepresentation\&.spellingVariant"

.PP
Definition at line 8 of file form_representation\&.py\&.
.SS "src\&.resources\&.form_representation\&.FormRepresentation\&.tone"

.PP
Definition at line 4 of file form_representation\&.py\&.
.SS "src\&.resources\&.form_representation\&.FormRepresentation\&.transliteration"

.PP
Definition at line 3 of file form_representation\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
