.TH "src.config" 3 "Thu Sep 18 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.config \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmdf\fP"
.br
.ti -1c
.RI " \fBtex\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
