.TH "src.morphology.component.Component" 3 "Thu Sep 18 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.morphology.component.Component \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBposition\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file component\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.morphology\&.component\&.Component\&.__init__ (self)"

.PP
Definition at line 4 of file component\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "src\&.morphology\&.component\&.Component\&.position"

.PP
Definition at line 5 of file component\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
