.TH "src.morphology.word_form.WordForm" 3 "Thu Sep 18 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.morphology.word_form.WordForm \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBgrammaticalNumber\fP"
.br
.ti -1c
.RI "\fBgrammaticalGender\fP"
.br
.ti -1c
.RI "\fBperson\fP"
.br
.ti -1c
.RI "\fBanymacy\fP"
.br
.ti -1c
.RI "\fBclusivity\fP"
.br
.ti -1c
.RI "\fBtense\fP"
.br
.ti -1c
.RI "\fBcase\fP"
.br
.ti -1c
.RI "\fBdegree\fP"
.br
.ti -1c
.RI "\fBvoice\fP"
.br
.ti -1c
.RI "\fBverbFormMood\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file word_form\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.morphology\&.word_form\&.WordForm\&.__init__ (self)"

.PP
Definition at line 6 of file word_form\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "src\&.morphology\&.word_form\&.WordForm\&.anymacy"

.PP
Definition at line 10 of file word_form\&.py\&.
.SS "src\&.morphology\&.word_form\&.WordForm\&.case"

.PP
Definition at line 13 of file word_form\&.py\&.
.SS "src\&.morphology\&.word_form\&.WordForm\&.clusivity"

.PP
Definition at line 11 of file word_form\&.py\&.
.SS "src\&.morphology\&.word_form\&.WordForm\&.degree"

.PP
Definition at line 14 of file word_form\&.py\&.
.SS "src\&.morphology\&.word_form\&.WordForm\&.grammaticalGender"

.PP
Definition at line 8 of file word_form\&.py\&.
.SS "src\&.morphology\&.word_form\&.WordForm\&.grammaticalNumber"

.PP
Definition at line 7 of file word_form\&.py\&.
.SS "src\&.morphology\&.word_form\&.WordForm\&.person"

.PP
Definition at line 9 of file word_form\&.py\&.
.SS "src\&.morphology\&.word_form\&.WordForm\&.tense"

.PP
Definition at line 12 of file word_form\&.py\&.
.SS "src\&.morphology\&.word_form\&.WordForm\&.verbFormMood"

.PP
Definition at line 16 of file word_form\&.py\&.
.SS "src\&.morphology\&.word_form\&.WordForm\&.voice"

.PP
Definition at line 15 of file word_form\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
