.TH "src.morphosyntax.paradigm.Paradigm" 3 "Thu Sep 18 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.morphosyntax.paradigm.Paradigm \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBparadigmLabel\fP"
.br
.ti -1c
.RI "\fBparadigm\fP"
.br
.ti -1c
.RI "\fBlanguage\fP"
.br
.ti -1c
.RI "\fBmorphology\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file paradigm\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.morphosyntax\&.paradigm\&.Paradigm\&.__init__ (self)"

.PP
Definition at line 4 of file paradigm\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "src\&.morphosyntax\&.paradigm\&.Paradigm\&.language"

.PP
Definition at line 7 of file paradigm\&.py\&.
.SS "src\&.morphosyntax\&.paradigm\&.Paradigm\&.morphology"

.PP
Definition at line 8 of file paradigm\&.py\&.
.SS "src\&.morphosyntax\&.paradigm\&.Paradigm\&.paradigm"

.PP
Definition at line 6 of file paradigm\&.py\&.
.SS "src\&.morphosyntax\&.paradigm\&.Paradigm\&.paradigmLabel"

.PP
Definition at line 5 of file paradigm\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
