.TH "src.mrd.equivalent.Equivalent" 3 "Thu Sep 18 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.mrd.equivalent.Equivalent \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlanguage\fP"
.br
.ti -1c
.RI "\fBtranslation\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file equivalent\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.mrd\&.equivalent\&.Equivalent\&.__init__ (self)"

.PP
Definition at line 4 of file equivalent\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "src\&.mrd\&.equivalent\&.Equivalent\&.language"

.PP
Definition at line 5 of file equivalent\&.py\&.
.SS "src\&.mrd\&.equivalent\&.Equivalent\&.translation"

.PP
Definition at line 6 of file equivalent\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
