.TH "src.output.xml_lp.XmlLp" 3 "Fri Sep 12 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.output.xml_lp.XmlLp \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits null\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1 of file xml_lp\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.output\&.xml_lp\&.XmlLp\&.__init__ (self)"

.PP
Definition at line 2 of file xml_lp\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
