.TH "src.morphology.lemma.Lemma" 3 "Thu Sep 18 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src.morphology.lemma.Lemma \- 
.PP
This class represents a lemma\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "def \fBset_lexeme\fP"
.br
.RI "\fISet lexeme\&. \fP"
.ti -1c
.RI "def \fBget_lexeme\fP"
.br
.RI "\fIGet lexeme\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhyphenation\fP"
.br
.ti -1c
.RI "\fBlexeme\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class represents a lemma\&. 
.PP
Definition at line 8 of file lemma\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def src\&.morphology\&.lemma\&.Lemma\&.__init__ (self)"

.PP
Constructor\&. 
.PP
\fBReturns:\fP
.RS 4
A \fBLemma\fP instance\&. 
.RE
.PP

.PP
Definition at line 11 of file lemma\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def src\&.morphology\&.lemma\&.Lemma\&.get_lexeme (self)"

.PP
Get lexeme\&. 
.PP
\fBReturns:\fP
.RS 4
\fBLemma\fP attribute 'lexeme'\&. 
.RE
.PP

.PP
Definition at line 26 of file lemma\&.py\&.
.SS "def src\&.morphology\&.lemma\&.Lemma\&.set_lexeme (self, lexeme)"

.PP
Set lexeme\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlexeme\fP The lexeme to set\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBLemma\fP instance\&. 
.RE
.PP

.PP
Definition at line 18 of file lemma\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "src\&.morphology\&.lemma\&.Lemma\&.hyphenation"

.PP
Definition at line 15 of file lemma\&.py\&.
.SS "src\&.morphology\&.lemma\&.Lemma\&.lexeme"

.PP
Definition at line 16 of file lemma\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
