.TH "/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/core/statement.py" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/core/statement.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlmf\&.src\&.core\&.statement\&.Statement\fP"
.br
.RI "\fI'Statement is a class representating a narrative description that refines or complements Definition\&.' (LMF) \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlmf\&.src\&.core\&.statement\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
