.TH "/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/mrd/subject_field.py" 3 "Fri Oct 3 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/mrd/subject_field.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlmf\&.src\&.mrd\&.subject_field\&.SubjectField\fP"
.br
.RI "\fI'Subject Field is a class representing a text string that provides domain or status information\&.' (LMF) \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlmf\&.src\&.mrd\&.subject_field\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
