.TH "/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/output/tex.py" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/output/tex.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlmf\&.src\&.output\&.tex\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.file_read\fP"
.br
.RI "\fIRead file contents\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.insert_references\fP"
.br
.RI "\fIInsert references to paradigms\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.tex_write\fP"
.br
.RI "\fIWrite a LaTeX file\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.handle_font\fP"
.br
.RI "\fIFunctions to process LaTeX layout\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.handle_reserved\fP"
.br
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.handle_fi\fP"
.br
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.handle_fv\fP"
.br
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.handle_fn\fP"
.br
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.handle_pinyin\fP"
.br
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.handle_caps\fP"
.br
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.handle_quotes\fP"
.br
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_uid\fP"
.br
.RI "\fIFunctions to process LaTeX fields (output) \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_link\fP"
.br
.RI "\fIDisplay hyperlink to a lexical entry in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_lexeme\fP"
.br
.RI "\fI'lx', 'hm' and 'lc' fields are flipped if 'lc' field has data\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_audio\fP"
.br
.RI "\fIEmbed sound file into PDF\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_part_of_speech\fP"
.br
.RI "\fIDisplay part of speech in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_definitions\fP"
.br
.RI "\fIGlosses are supplanted by definitions\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_lt\fP"
.br
.RI "\fIDisplay 'lt' in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_sc\fP"
.br
.RI "\fIDisplay 'sc' in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_rf\fP"
.br
.RI "\fIDisplay 'rf' in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_examples\fP"
.br
.RI "\fIDisplay examples in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_usage_notes\fP"
.br
.RI "\fIDisplay usage notes in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_encyclopedic_informations\fP"
.br
.RI "\fIDisplay encyclopedic informations in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_restrictions\fP"
.br
.RI "\fIDisplay restrictions in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_lexical_functions\fP"
.br
.RI "\fIDisplay lexical functions in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_related_forms\fP"
.br
.RI "\fIDisplay related forms in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_variant_forms\fP"
.br
.RI "\fIDisplay variant forms in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_borrowed_word\fP"
.br
.RI "\fIDisplay borrowed word in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_etymology\fP"
.br
.RI "\fIDisplay etymology in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_paradigms\fP"
.br
.RI "\fIDisplay all paradigms in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_table\fP"
.br
.RI "\fIDisplay a table in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_semantic_domains\fP"
.br
.RI "\fIDisplay semantic domains in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_bibliography\fP"
.br
.RI "\fIDisplay bibliography in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_picture\fP"
.br
.RI "\fIDisplay a picture in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_notes\fP"
.br
.RI "\fIDisplay all notes in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_source\fP"
.br
.RI "\fIDisplay source in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_status\fP"
.br
.RI "\fIDisplay status in LaTeX format\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.tex\&.format_date\fP"
.br
.RI "\fIDo not display date in LaTeX format\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
