.TH "/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/morphology/word_form.py" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/morphology/word_form.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlmf\&.src\&.morphology\&.word_form\&.WordForm\fP"
.br
.RI "\fI'Word Form is a Form subclass representing a form that a lexeme can take when used in a sentence or a phrase\&.' (LMF) \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlmf\&.src\&.morphology\&.word_form\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
