.TH "/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/config/xml.py" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/config/xml.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlmf\&.src\&.config\&.xml\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBlmf\&.src\&.config\&.xml\&.sort_order_read\fP"
.br
.RI "\fIRead an XML file giving sort order\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.config\&.xml\&.config_read\fP"
.br
.RI "\fIRead an XML file giving the user configuration\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
