.TH "/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/output/xml_lmf.py" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/output/xml_lmf.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlmf\&.src\&.output\&.xml_lmf\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.xml_lmf\&.xml_lmf_write\fP"
.br
.RI "\fIWrite an XML LMF file\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.xml_lmf\&.build_sub_elements\fP"
.br
.RI "\fICreate XML sub-elements to an existing XML element by parsing an LMF object instance\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.xml_lmf\&.add_link\fP"
.br
.RI "\fIFunctions to process XML/XHTML layout\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.xml_lmf\&.handle_reserved\fP"
.br
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.xml_lmf\&.handle_fv\fP"
.br
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.xml_lmf\&.handle_fn\fP"
.br
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.xml_lmf\&.handle_font\fP"
.br
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.xml_lmf\&.handle_pinyin\fP"
.br
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.xml_lmf\&.handle_caps\fP"
.br
.ti -1c
.RI "def \fBlmf\&.src\&.output\&.xml_lmf\&.handle_tones\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
