.TH "/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/utils/xml_format.py" 3 "Fri Jul 24 2015" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/utils/xml_format.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlmf\&.src\&.utils\&.xml_format\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBlmf\&.src\&.utils\&.xml_format\&.prettify\fP"
.br
.RI "\fIReturn a pretty-printed XML string for the given XML element\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.utils\&.xml_format\&.write_result\fP"
.br
.RI "\fIWrite an XML element into a pretty XML output file\&. \fP"
.ti -1c
.RI "def \fBlmf\&.src\&.utils\&.xml_format\&.parse_xml\fP"
.br
.RI "\fIParse an XML file\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
