.TH "/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/output/xml_lmf.py" 3 "Thu Sep 18 2014" "LMF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/celine/Work/CNRS/workspace/HimalCo/dev/lib/lmf/src/output/xml_lmf.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsrc\&.output\&.xml_lmf\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBsrc\&.output\&.xml_lmf\&.xml_lmf_write\fP"
.br
.RI "\fIWrite an XML LMF file\&. \fP"
.ti -1c
.RI "def \fBsrc\&.output\&.xml_lmf\&.build_sub_elements\fP"
.br
.RI "\fICreate XML sub-elements to an existing XML element by parsing an LMF object instance\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LMF library from the source code\&.
